<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>You need more than just a <strong> web hosting </strong><span>you needs a partner.</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 
 <div class="wraper">    

 <div class="pricing_option pricing_option3">
   <ul>
    <li>
     <h4>Reseller Hosting</h4>
     <div class="price">Starting From<strong>&#36;</strong><span>150</span><sup>.00</sup><em>Annually</em></div>
     <img src="/images/web-hosting/reseller-hosting.png" class="wp1_3 slide1_bot" alt="reseller hosting">
     <p><a class="btn_m" href="<?php echo $this->url(array('module' => 'default','controller' => 'hosting','action' => 'reseller-hosting'));?>">View Plans</a></p>
    </li>
    
    <li class="active">
    <div class="active_bg">
     <h4>Shared Web Hosting</h4>
     <div class="price">Starting From<strong>&#36;</strong><span>25</span><sup>.00</sup><em>Annually</em></div>
     <img src="/images/web-hosting/web-hosting.png" class="wp1_3 slide1_bot" alt="web hosting">		 
     <p><a class="btn_m" href="<?php echo $this->url(array('module' => 'default','controller' => 'hosting','action' => 'shared-hosting'));?>">View Plans</a></p>
    </div>
    </li>
    
    <li>
     <h4>Dedicated Servers</h4>
     <div class="price">Starting From<strong>&#36;</strong><span>250</span><sup>.00</sup><em>Monthly</em></div>
     <img src="/images/web-hosting/dedicated-server.png" class="wp1_3 slide1_bot" alt="dedicated server">
     <p><a class="btn_m" href="<?php echo $this->url(array('module' => 'default','controller' => 'hosting','action' => 'dedicated-server'));?>">View Plans</a></p>
    </li>
   </ul>
  </div>
  </div>
  
  
  <div class="wraper">  
  <div class="features_block">
   <ul>
    <li class="design">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>24x7 Live Support</span></h4>
     <p>Lid est laborum dolo rumes fugats untras. Et harums ser quidem sit rerum facilis est dolores nemis uns.  </p>
    </li>
    <li class="flexible">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>Security Enhancements</span></h4>
     <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium dolorem que laudantium totam</p>
    </li>
    <li class="support">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>Easy to Use Control Panel</span></h4>
     <p>Nemo enim ipsam voluptatem uns quia voluptas sit aspernatur aut odit aut fugit, sed quia consequunturs.</p>
    </li>
    <li class="easy">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span> &nbsp;&nbsp;&nbsp;  Highly Scalable &nbsp;&nbsp; </span></h4>
     <p>Neque porro qusquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit sed quia nons.</p>
    </li>
    <li class="seo">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>1-click Script Installation</span></h4>
     <p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis voluptas uns sadips doloreusi.</p>
    </li>
   </ul>
  </div>
  
  

  <div class="features2_block services_option">
   <h4>Web Hosting Features</h4>
   <div id="h_tabs" class="c_after">
   <ul class="tab_select left_list">
    <li class="sitemanagement">
     <a class="tlink" href="#htab-1">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Site Management</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="emailfeatures">
     <a class="tlink" href="#htab-2">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Email Features</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="customersupport">
     <a class="tlink" href="#htab-3">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Customer Support</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="scriptsupport<">
     <a class="tlink" href="#htab-4">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Script Support</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="statistics">
     <a class="tlink" href="#htab-6">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Statistics</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="datacenter">
     <a class="tlink" href="#htab-7">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Data Center</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>

    
    
   </ul>
   <div id="htab-1" class="right_desc">
    <p><em><strong>Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_8.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-2" class="right_desc">
    <p><em><strong>Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_9.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-3" class="right_desc">
    <p><em><strong>500+ Fonts Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_10.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-4" class="right_desc">
    <p><em><strong>Ultra Responsive Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_11.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-5" class="right_desc">
    <p><em><strong>Superb Support Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_12.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-6" class="right_desc">
    <p><em><strong>Easy To Customize Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_13.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-7" class="right_desc">
    <p><em><strong>Choose Your Color Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_14.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>

    </ul>
   </div>
   <div id="htab-8" class="right_desc">
    <p><em><strong>Constant Updates Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_15.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   </div>
  </div>
  
  
  
  
  
   <!-- features_block -->
  <div class="features2_block features3_block features6_block">
   <ul>
   
    <li class="design">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Web Hosting</h4>
     <p><span>Your Hosting Partner</span></p>
     <p>WinWinHost Provides hosting servies at right rates and all the features that should be there with respect to present technology around the web. You can choose from many packages that suits you best.</p>
    </li>
    
    <li class="flexible">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Domains</h4>
     <p><span>World Wide Domains</span></p>
     <p>Register you Brand Names with Us , Domain Names is the gateway to your business on the web. Register today with the lowest rates around and we will help you further you setup your site quickly.</p>
    </li>
    
     <li class="support">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Design</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Lid est laborum dolos rumes fustsirs sit untras. Et harums ser quidem sit rerums facilis est dolores uni nemis sad untras voluptas uners sits amets.  </p>
    </li>
    
    <li class="easy">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Web Apps</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>We are extremely proficient at setting up solutions for our clients. We offer Basic Web sites to Mobile Application Development, Cloud Computing solutions , and many other types of software development services.</p>
    </li>
    
    <li class="updates">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Native Apps</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>At WinWinHost we are now developing Mobile optimized websites and apps for both Android and IOS. Mobile industry is againing shares in the Tech World rapidly , make your Identity in the Mobile World with us.</p>
    </li>
    
    <li class="color">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>SEO</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Search Engine Optimization refers to optimize your site to be easily found by search engines and we have experts who can make your site on top of Google's results , giving your organic traffic so you dont have to spend anything monthly </p>
    </li>
    
    <li class="fonts">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Internet Marketing</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Let the experts get you the largest possible ROI. WinWinHost.com can conduct your Email Marketing Campaigns, manage your PPC campaigns, setup CPA affiliate systems, and even design print advertising.</p>
    </li>
    
    <li class="ultra">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Open Source</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>We are working to provide best Open Source programs to his customers and not only this but now we are offering some open source projects and we hope in future to increase their number and of course to add new features to the existing projects.</p>
    </li>

   </ul>
  </div> 
  
  
 </div>
 
</div>






