<head>

<meta name="description" content="">

 		<?php echo $this->headLink()->prependStylesheet('/../stylesheets/style.css'); ?> 
        <?php echo $this->headLink()->prependStylesheet('/stylesheets/responsive.css'); ?> 
        <?php echo $this->headLink()->prependStylesheet('/stylesheets/jquery.onebyone.css'); ?> 
        <?php echo $this->headLink()->prependStylesheet('/stylesheets/pfold.css'); ?> 
        <?php echo $this->headLink()->prependStylesheet('/stylesheets/custom1.css'); ?> 

        <?php echo $this->headScript()->appendFile('/scripts/modernizr.custom.79639.js') ?>
        <?php echo $this->headScript()->appendFile('/scripts/jquery.onebyone.min.js') ?>
        <?php echo $this->headScript()->appendFile('/scripts/jquery.touchwipe.min.js') ?>
        <?php echo $this->headScript()->appendFile('/scripts/js_func.js') ?>
        <?php echo $this->headScript()->appendFile('/scripts/jquery.pfold.js') ?>
        
        <link rel="stylesheet" href="http://www.merijuana.la/stylesheets/style.css"> 
        <link rel="stylesheet" href="/stylesheets/responsive.css"> 
        <link rel="stylesheet" href="/stylesheets/jquery.onebyone.css">
                
        <link rel="stylesheet" type="/text/css" href="/stylesheets/pfold.css" />
        <link rel="stylesheet" type="/text/css" href="/stylesheets/custom2.css" />
        <link rel="stylesheet" type="/text/css" href="/stylesheets/custom1.css" />

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

        <script src="/scripts/modernizr.custom.79639.js"></script>
        <script src="/scripts/jquery.onebyone.min.js"></script>              
        <script src="/scripts/jquery.touchwipe.min.js"></script> 
        <script src="/scripts/js_func.js"></script>
        <script src="/scripts/jquery.pfold.js"></script>
        
        <style>

					#obo_slider .oneByOne_item{
	position: absolute;
	width: 960px;
	height: 345px;
	overflow: hidden;
	left: 10px;
					}
					
					.arrowButton{    
						cursor: pointer;  
					}            
					.arrowButton .prevArrow{
						background: url(obo/prev.png) no-repeat; 
						width: 60px;
						height: 60px;      
						position: absolute;
						top: 127px;	 
						left: 50px;        
					} 
					.arrowButton .nextArrow{                 
						background: url(obo/next.png) no-repeat;
						width: 60px;
						height: 60px;
						position: absolute;
						top: 127px;
						right: 50px;
					}

		
		</style>
        
</head>


<div class="wrape homeone">
		<div class="fallback"><img src="images/sliders/home_page_1/home_page_1_fallback.jpg" alt="" /></div>
		    
</div>


<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>You need more than just a <strong> web hosting </strong><span>you needs a partner.</span></h2>
   <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">Pages</a></li>
    <li>Pricing</li>
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 
 <div class="wraper">    
 
 <div id="obo_slider" >  				
		<div class="oneByOne_item">
			<img src="/images/shared-hosting/web-hosting.png" class="wp1_3 slide1_bot" alt="">		            
			<span class="txt1">with WinWinHost </span>			
			<span class="txt2 blue txt_left2">Web Hosting</span>												
			<span class="txt2 ">Setup your site</span>			
            <span class="txt3">at right price and we promise ,there are no hidden charges </span>										
</div>
                                                                                        
		
		</div>
        

      
  <div class="pricing_option pricing_option2">
   <ul>
    <li>
     <h4>Windows Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>25</span><sup>.00</sup><em>monthly</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>1 Domain Allowed</p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>

     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </li>
    <li>
     <h4>Linux Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>25</span><sup>.00</sup><em>annually</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>1 Domain Allowed</p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </li>
    <li class="active">
    <div class="active_bg">
     <h4>Unlimited Windows Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>50</span><sup>.00</sup><em>annually</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </div>
    </li>
    <li>
     <h4>Unlimited Linux Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>50</span><sup>.00</sup><em>annually</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </li>
   </ul>
  </div>
  
 </div>
 
</div>

<div class="wraper">
<div class="services_option2 vertical_tabs">
   <h4>Features</h4>
	<div id="tabs">
     <ul class="tab_select">
      <li><a href="#tab-1">Site Management</a></li>
      <li><a href="#tab-2">Programming and Database</a></li>
      <li><a href="#tab-3">Email Features</a></li>
      <li><a href="#tab-4">Customer Support</a></li>
      <li><a href="#tab-5">Statistics</a></li>
      <li><a href="#tab-6">Quick Scripts</a></li>
     </ul>
     
     
     <div id="tab-1">
      <h3>Site Management</h3>
      <h5>Manage all things with ease </h5>
    
      <ul>
       <li>Direct Admin Web Control Panel</li>
       <li>Unlimited FTP Accounts (create FTP accounts and set directory permissions for each account.  Anonymous FTP is also supported)</li>
       <li>Online File Manager (A user-friendly and fast alternative to FTP.  Includes every feature needed to build and maintain a web site)</li>
       <li>Subdomains (list, create, delete, and get statistics on subdomains)</li>
       <li>DNS Menu.(add and remove records, change MX settings, and anything else that goes with full DNS control) </li>
       <li>Password Protected Directories</li>
       <li>Site Backup (powerful tool,backup and restore only what they want to.  For example, account data but not web site files)</li>
       <li>High Performance Load Balanced Servers </li>

      </ul>
      <!-- <p><a class="learn_more btn_m" href="#">Learn More</a></p> -->
     </div>
     
     
     <div id="tab-2">
      <h3>Language & Database Support</h3>
      <h5>No Matter what technology you used to make your apps , we host them all</h5>
      <p></p>
      <ul>
      <li>PHP 5.2 & PHP 5.3	</li>	 
	  <li>CGI, Fast CGI</li>
      <li>Perl </li>
      <li>MySQL Databases with phpMyAdmin Access</li>
      <li>ASP 3.0 (Classic ASP)</li>
	  <li>ASP.NET (.NET 1.1)</li>
      <li>MS SQL Server</li>
      <li>FrontPage Extensions.</li>
      <li>SSH Access and Cron Job Scheduling</li>

      </ul>

     </div>
     

     <div id="tab-3">
      <h3>Email Features</h3>
      <h5>Make a Win with WinWinHost Super Email Services </h5>
            <p>Create POP/IMAP accounts, catch-all e-mail addresses, forwarders, mailing lists, autoresponders, and webmail.  Filters allow users to block mail by domain, keyword, and size.  Adult Filter is also available.</p>
      <ul>
       <li>Unlimited Email Accounts</li>
       <li>Email Addresses at Your Domain (yourname@yourbusiness.com)</li>
       <li>WebMail (Checking Your Mail Online)</li>
       <li>Auto Responders</li>
       <li>Unlimited Mailing Lists</li>
       <li>Mail Spam Filters</li>
       <li>SMTP/POP3/IMAP</li>
       <li>Mail Forwards</li>
       </ul>
     </div>
     
     
     <div id="tab-4">
      <h3>Customer Support</h3>
      <h5>Providing Unbeatable Support</h5>

      <ul>
       <li>24/7 Technical Support ( Ticket Support System , Email , Live Chat , Phone )</li>
       <li>Online User Manuals</li> 
       <li>24/7 Server Monitoring</li>
       <li>99.9% Uptime Guarantee</li>
      </ul>
      
     </div>
     
     
     <div id="tab-5">
      <h3>Statistics</h3>
      <h5>Get idea about what your site is worth of?</h5>
      <p>Have available every possible statistic about their account.  More advanced options and Webalizer are also included. </p>
      <ul>
       <li>Visitor Statistics/Site Traffic Reporting</li>
       <li>Bandwidth Usage</li>
       <li>Error Logs</li>
       <li>Raw Access Logs</li>
      </ul>

     </div>
     
     
     
     <div id="tab-6">
      <h3>Advanced Tools + Install Quick Scripts  </h3>
      <h5>Dont bother about downloading and  than uploading commonly used Applications</h5>
	  <ul>
      
      <li>Install SSL certificates</li>
      <li>View sever information, installed perl modules</li>
      <li>Set cron jobs, mime types, and apache handlers</li>
      <li>Enable site redirection and domain pointers</li>
      <li>WordPress Hosting - Host your WordPress sites with ease</li>
	  <li>Joomla Hosting & Drupal Hosting </li>
	  <li>Magento Hosting - Free E-commerce platform for your online store</li>	
       
      </ul>
     <!--  <p><a class="learn_more btn_m" href="#">Learn More</a></p> -->

     </div>
     
     
     
     
     
    </div>
  </div>
  
 <!--<div class="features2_block services_option">
   <h4>Web Hosting Features</h4>
   <div id="h_tabs" class="c_after">
   <ul class="tab_select left_list">
    <li class="sitemanagement">
     <a class="tlink" href="#htab-1">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Site Management</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="emailfeatures">
     <a class="tlink" href="#htab-2">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Email Features</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="customersupport">
     <a class="tlink" href="#htab-3">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Customer Support</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="scriptsupport<">
     <a class="tlink" href="#htab-4">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Script Support</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="statistics">
     <a class="tlink" href="#htab-6">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Statistics</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="datacenter">
     <a class="tlink" href="#htab-7">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Data Center</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>

    
    
   </ul>
   <div id="htab-1" class="right_desc">
    <p><em><strong>Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_8.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-2" class="right_desc">
    <p><em><strong>Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_9.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-3" class="right_desc">
    <p><em><strong>500+ Fonts Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_10.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-4" class="right_desc">
    <p><em><strong>Ultra Responsive Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_11.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-5" class="right_desc">
    <p><em><strong>Superb Support Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_12.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-6" class="right_desc">
    <p><em><strong>Easy To Customize Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_13.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-7" class="right_desc">
    <p><em><strong>Choose Your Color Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_14.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-8" class="right_desc">
    <p><em><strong>Constant Updates Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_15.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   </div>
  </div> -->
  </div>


 
 
 
 
 
 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  