<head>

<meta name="description" content="">

        
        <style>
		
		#obo_slider {
			height:305px;
		
		}
		
		.oneByOne1{	
	margin: 0;
	width: 100%;
	height:305px;   
	background: #fff;    
	position: relative;
	overflow: hidden;

} 



					 .oneByOne_item{
	position: absolute;
	width: 960px;
	height: 305px;
	overflow: hidden;
	left: 10px;
					}
					
					.arrowButton{    
						cursor: pointer;  
					}            
					.arrowButton .prevArrow{
						background: url(obo/prev.png) no-repeat; 
						width: 60px;
						height: 60px;      
						position: absolute;
						top: 127px;	 
						left: 50px;        
					} 
					.arrowButton .nextArrow{                 
						background: url(obo/next.png) no-repeat;
						width: 60px;
						height: 60px;
						position: absolute;
						top: 127px;
						right: 50px;
					}

		
		</style>
        
</head>


<div class="wrape homeone">
	 
</div>


<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>You need more than just a <strong> web hosting </strong><span>you needs a partner.</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 
 <div class="wraper">    
 
 <div id="obo_slider" >  				
		<div class="oneByOne_item">
			<img src="http://new.winwinhost.com/wwwroot/images/shared-hosting/web-hosting.png" class="wp1_3 slide1_bot" alt="Web Hosting">		            
			<span class="txt1">with WinWinHost </span>			
			<span class="txt2 blue txt_left2">Web Hosting Fullfill </span>												
			<span class="txt2 ">Your Hosting Needs</span>			
            <span class="txt3">at right price and we promise ,there are no hidden charges </span>										
</div>
                                                                                        
		
		</div>

  <div class="pricing_option pricing_option2" s>
   <h4 class="bord">Plans and Prices</h4>
   
   
   
   <ul>
    <li>
     <h4>Windows Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>25</span><sup>.00</sup><em>monthly</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>1 Domain Allowed</p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>

     <p>&nbsp;</p>
     <p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="MXAZGBSUZD3L4">
<input class="btn_m" type="submit" value="Subcribe"  name="submit" >
</form></p>
    </li>
    
    
    
    
    <li>
     <h4>Linux Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>25</span><sup>.00</sup><em>annually</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>1 Domain Allowed</p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="2LV7XPU8PGHKA">
<input class="btn_m" type="submit" value="Subcribe"  name="submit" >
</form></p>
    </li>
    
    
    
    
    <li class="active">
    <div class="active_bg">
     <h4>Unlimited Windows Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>50</span><sup>.00</sup><em>annually</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="7GBMPA6X5BBVU">
<input class="btn_m" type="submit" value="Subcribe"  name="submit" >
</form></p>
    </div>
    </li>
    
    
    
    
    <li>
     <h4>Unlimited Linux Hosting</h4>
     <div class="price"><strong>&#36;</strong><span>50</span><sup>.00</sup><em>annually</em></div>
     <p>Direct Admin Control Panel</p>
     <p>1 GB Disk Space</p>
     <p>Unlimited Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="ZY8AQBVXXGCXE">
<input class="btn_m" type="submit" value="Subcribe"  name="submit" >
</form></p>
    </li>
    
    
    
    
   </ul>
  </div>
  
 </div>
 
</div>

<div class="wraper">


<div class="wraper">
  <!-- left_nav -->
  <div class="left_nav">
	<div id="tabs" class="c_after">
    
     <ul class="tab_select">
      <li><a href="#tab-1">Site Management</a></li>
      <li><a href="#tab-2">Programming & Database</a></li>
      <li><a href="#tab-3">Email Features</a></li>
      <li><a href="#tab-4">Customer Support</a></li>
      <li><a href="#tab-5">Statistics</a></li>
      <li><a href="#tab-6">Install Quick Apps</a></li>
     </ul>
     
     <div id="tab-1">
       <h3>Site Management</h3>
       <h5>Manage all things with ease </h5>
      <p>
      <ul>
       <li>Direct Admin Web Control Panel</li>
       <li>Unlimited FTP Accounts (create FTP accounts and set directory permissions for each account.  Anonymous FTP is also supported)</li>
       <li>Online File Manager (A user-friendly and fast alternative to FTP.  Includes every feature needed to build and maintain a web site)</li>
       <li>Subdomains (list, create, delete, and get statistics on subdomains)</li>
       <li>DNS Menu.(add and remove records, change MX settings, and anything else that goes with full DNS control) </li>
       <li>Password Protected Directories</li>
       <li>Site Backup (powerful tool,backup and restore only what they want to.  For example, account data but not web site files)</li>
       <li>High Performance Load Balanced Servers </li>
      </ul>
      </p>
      
     </div>
     
     
     <div id="tab-2">
       <h3>Programming & Database</h3>
      <h5>No Matter what technology you used to make your apps , we host them all</h5>
      <p></p>
      <ul>
      <li>PHP 5.2 & PHP 5.3	</li>	 
	  <li>CGI, Fast CGI</li>
      <li>Perl </li>
      <li>MySQL Databases with phpMyAdmin Access</li>
      <li>ASP 3.0 (Classic ASP)</li>
	  <li>ASP.NET (.NET 1.1)</li>
      <li>MS SQL Server</li>
      <li>FrontPage Extensions.</li>
      <li>SSH Access and Cron Job Scheduling</li>
      </ul>
     </div>
     
     
     <div id="tab-3">
      <h3>Email Features</h3>
      <h5>Make a Win with WinWinHost Super Email Services </h5>
            <p>Create POP/IMAP accounts, catch-all e-mail addresses, forwarders, mailing lists, autoresponders, and webmail.  Filters allow users to block mail by domain, keyword, and size.  Adult Filter is also available.</p>
      <ul>
       <li>Unlimited Email Accounts</li>
       <li>Email Addresses at Your Domain (yourname@yourbusiness.com)</li>
       <li>WebMail (Checking Your Mail Online)</li>
       <li>Auto Responders</li>
       <li>Unlimited Mailing Lists</li>
       <li>Mail Spam Filters</li>
       <li>SMTP/POP3/IMAP</li>
       <li>Mail Forwards</li>
       </ul>
     </div>
     

     
     
     
     <div id="tab-4">
     <h3>Customer Support</h3>
      <h5>Providing Unbeatable Support</h5>
      <ul>
       <li>24/7 Technical Support ( Ticket Support System , Email , Live Chat , Phone )</li>
       <li>Online User Manuals</li> 
       <li>24/7 Server Monitoring</li>
       <li>99.9% Uptime Guarantee</li>
      </ul>
     </div>
     
     
     <div id="tab-5">
       <h3>Statistics</h3>
      <h5>Get idea about How your site is being used?</h5>
      <p>Have available every possible statistic about their account.  More advanced options and Webalizer are also included. </p>
      <ul>
       <li>Visitor Statistics/Site Traffic Reporting</li>
       <li>Bandwidth Usage</li>
       <li>Error Logs</li>
       <li>Raw Access Logs</li>
      </ul>
     </div>
     
     
     <div id="tab-6">
      <h3>Install Quick Apps</h3>
      <h5>Dont bother about downloading and  than uploading commonly used Applications</h5>
	  <ul>     
      <li>Install SSL certificates</li>
      <li>View sever information, installed perl modules</li>
      <li>Set cron jobs, mime types, and apache handlers</li>
      <li>Enable site redirection and domain pointers</li>
      <li>WordPress Hosting - Host your WordPress sites with ease</li>
	  <li>Joomla Hosting & Drupal Hosting </li>
	  <li>Magento Hosting - Free E-commerce platform for your online store</li>	
      </ul>
     </div>
     
     </div>

    </div>
  </div>
  <!-- /left_nav -->

 </div>  
  


  
  
  
  
  
  
  
  
  