<head>

</head>

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>Affiliate Systems</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 <div class="wraper">
 
<div class="intro_text">
   <div class="bwWrapper" style="border:0;"><img src="http://new.winwinhost.com/wwwroot/images/marketing/affiliate-systems.jpg" alt="affiliate systems" title="web design stack" /></div>
   <div class="desc">
    <h4>Affiliate Systems</h4>
    <p>We are working on new ways to market our products constantly! I am very exicted to say that we are launching our affiliate system. WinWinHost.com is probably the only web hosting company with a lifetime revshare affiliate network in mind. See, most affiliate marketing stragies for web hosting companies include paying out a commission of over 100% the sale price. They do this because most web hosting clients are lifetime customers. This becomes a residual revenue stream! We are new startup and we want to give you that opportunity to share in our growth! This offer is sure to expire as, but for now WinWinHost.com is happy to provide our affiliates wit a 25% lifetime revenue share. You can sign up right now, and start promoting us and several of our chosen companies.</p>
    
    <br />
    <!-- <a href="#"> Our Affiliate System</a> -->
</p>
   </div>
  </div>
  
  
  </div>
   
 
</div>