<head>

</head>

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>The Email Marketing <span> that Means Business. </span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 <div class="wraper">
 
<div class="intro_text">
   <div class="bwWrapper" style="border:0;"><img src="http://new.winwinhost.com/wwwroot/images/marketing/email-marketing.jpg" alt="web design Stack" title="web design stack" /></div>
   <div class="desc">
    <h4>WinWinHost is full service email agency that will generate you more loyalty and revenue.</h4>
    <p>When we turn to email marketing techniques the big problem is that we must be very careful not to be considered as spammers. Email marketing techniques most commonly used are newsletters, promotions, annoncements and the advantage is that these are offering immediate results.<p>
<br />
<p>At WinWinHost we are experts in email marketing, that's a fact, we've been pushing the boundaries in this industry since many years. Nowadays, there is a splendid array of digital marketing tools to include in our stack of solutions, such as SEO , social media, PPC, mobile and more. They all need to work directly with your email marketing to generate better results for your business.</p>
</p>
   </div>
  </div>
  
  <div class="why_choose_explore">
   <h4>Let's see some basic things that we need to do when starting an email campaign?</h4>
  <!-- why choose -->
  <div class="why_choose">
   <ul>
    <li><h5>1</h5></li>
    <p>Build a list of contacts: this you can start directly from your email address that you already have and is a very good start in a email campaign.</p>
    
    <li><h5>2</h5></li>
    <p>Find out the email addresses of persons who have agreed to use their data for various campaigns of some existing companies. This you can do by contacting these companies and negotiate a price.</p>
    
    <li><h5>3</h5></li>
    <P>If you are member of some online groups then you can use that group emails. Often this can be considered spam in an email campaign but there are plenty of exceptions.</P>

    <li><h5>4</h5></li>
    <p>Get email addresses from the internet. This is easily to be dome because many visitors leave their email addresses when they register on different sites or directories form but you must be careful because this is definitely considered spam.<p>
    
    <li><h5>5</h5></li>
    <p>Get email addresses from the internet. This is easily to be dome because many visitors leave their email addresses when they register on different sites or directories form but you must be careful because this is definitely considered spam.<p>
    
    <li><h5>6</h5></li>
    <p>Promote your own email newsletter: It is a great way when you want those who receive your emails to subscribe and receive your newsletter.<p>
    
    <li><h5>7</h5></li>
    <p>Notify and promote your newsletter on other websites or get together with other companies to promote your business through their newsletter because for a certain amount of money you can get a few words about your company in their email campaign.<p>

   </ul>
   </div>

  <!-- /why choose -->
   
  <!-- features_explore -->
  <div class="features_explore">
   <ul>
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/marketing/email-marketing-cycle.jpg"  alt="User Experience" /></a></div>
     <p><h5>How WinWinhost helps you</h5>One of our main service at WinWinhost is email marketing and that's what we're experts in. We know that today it os not the one-size fits all solution and are able to 'join-up' your message across the full digital web.</p>
     
<br />
<br />

<p><h5>We work with you closely</h5>We work with our clients to develop, plan and run their email marketing campaign and support them with all of your digital presence to maximise return on their investment.</p>
    </li>
   </ul>
  </div>

  <!-- /features_explore -->
  
  </div>
  </div>
  
  <div class="wraper">
  
  <p>WinWinHost can help you in organizing a well structured email campaign that will bring you a lot of subscribers and customers simultaneously. All you need to do is contact us and we will provide your company with our knowledge and our rental list for your email marketing campaign..</p>
  
  </div>
  
  <div class="wraper">
  
    <div class="send_quote send_quote_marg">
   <h4>Would you like us to run email campaign for you?</h4>
   <p>Click the button, fill out the form and we'll be right with you!<a class="btn_col" href="#">Contact Now</a></p>
  </div>
  
 </div>
 
</div>