
<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
  <h2> Privacy Policy <span></span></h2>

  </div>
 </div>
 <!-- /top_title -->
 <div class="wraper wraper_typ">
 
 <h2>Our Privacy Policy</h2>
   <p>WinWinhost collect the minimum amount of information about you that is necceessary for providing you with a satisfactory services. The purpose of this Privacy Policy to let you understand which personal information of yours is being collected by WinWinhost , how and when WinWinhost might use your information, who has access to this information, and how you can correct any inaccuracies in the information. To better protect your privacy, we provide this notice explaining our online information practices and the choices you can make about the way your information is collected and used. To make this notice easy to find, we make it available on our website.</p>

 <br />
 
 <div class="columns">
   <div class="col_2">
    <p><strong>Information Collected</strong></p>
    <p>We may collect any or all of the information that via both automated means such as communications profiles and cookies. Personal Information you give us depends on the type of service, support, or sale inqury, that may include your name, address, telephone number, fax number and email address, date of service provided, types of services provided, payments history, manner of payments, amount of payment, date of payment, domain name , credit cards or other payment information. The financial information will be transferred only be used to bill you for the products and services you purchased. If you purchase by credit card, this information may be forwarded to your credit card provider. All sensitive information is collected on a secure server and data is transferred .
</p>

<p><strong>Information Use</strong></p>
    <p>The information collected is used for billing and to provide service and support to our customers. We may also study this information to determine our customers needs and provide better support for our customers. All reasonable security measures and precautions are taken to prevent unauthorised access to this information. This safeguard may require you to provide additional forms of identity should you wish to obtain information about your account details. WinWinHost may email its monthly newsletter to the primary contact e-mail if you have subscribed to our news letter form , but customers are able to opt out of this newsletter at any time.</p>
    
    
<p><strong>Disclosing Information</p></strong>
<p>WinWinHost do not disclose any personal information obtained about users from this website to third parties. This does not apply to affiliates that provide services to you based on links provided within your CPanel/Direct Admin access and control, wherein information will be shared to facilitate your use of additional amenities included with your hosting account</p>

<p>We may use personal information to keep in contact with you and inform you of developments associated with our business. We may also disclose aggregate, anonymous data based on information collected from users to potential partners, our affiliates, and reputable third parties. We take all available measures to select affiliates and service providers that are ethical and provide similar privacy protection to their customers and the community. We do not make any representations about the practices and policies about these companies.</p>


  <p><strong>Correcting/Updating Personal Information</strong></p>
  <p>If a user's personally identification information changes, or if a user no longer desires our services, we will endeavor to provide a way to correct, update or remove that user's personal data in our records. This can be achieved by contacting us at support@winwinhost.com</p>

    
    <p><strong>IP(Internet Protocol) Address</strong></p>
     <p>We use IP addresses to analyze trends, administer our site and servers, track access, and gather broad demographic information for aggregate use. IP addresses are not linked to personally identifiable information. It is possible that personal information about a customer may be included in the log files due to the normal functions of IP addresses and Web browsing.</p>
     
     
       <p><strong>Changes to this Policy</strong></p>
  <p>Any changes to WinWinHost's Privacy Policy will be placed here and will supersede this version of WinWinHost's Policy. We will take reasonable steps to draw user's attention to any changes in our Policy. However, to be on the safe side, we suggest that user read this document each time they use the website to ensure that it still meets with their approval.</p>
     
     

   </div>
   
   
   
   <div class="col_2">
    <p><strong>Cookies</strong></p>
    <p>WinWinHost uses cookies provided by third parties which allows us to deliver customized marketing to our visitors based on their site usage and avoid delivering irrelevant marketing to visitors.This helps us to collect information about use of this Site, such as how often users visit the Site, what pages they visit when they do so, and what other sites(refering sites) they used prior to coming to WinWinHost's Site.
</p>
    
    
<div class="bullets_lists c_after">

   <ul class="arrows_list">
    <li>Google Analytics: </li>
    <p> </p>
    <p>We use a web tool called &ldquo;Google Analytics&rdquo; to collect information about use of this Site, such as how often users visit the Site, what pages they visit when they do so, and what other sites(refering sites) they used prior to coming to this Site.  Google Analytics collects only the IP address assigned to visitors on the date visitor visit this Site, rather than visitor's name or other identifying information. </p>
    
    <p>Google Analytics plants a permanent cookie on visitor's web browser to identify visitor as a unique user the next time visitor visits this Site.  This cookie cannot be used by anyone but Google, Inc.  The information generated by the cookie will be transmitted to and stored by Google on servers in the United States.</p>
    
    <p>We use the information received from Google Analytics only to improve services on this Site , understand how people interact with the Site, and help us to optimize Site performance, usability and users' experience .  We do not combine the information collected through the use of Google Analytics with personally identifiable information. </p>
    
    
    <p>Google&rsquo;s ability to use and share information collected by Google Analytics about your visits to this Site is restricted by the <a href="http://www.google.com/policies/privacy/">Google Privacy Policy</a>.  You can prevent Google Analytics from recognizing you on return visits to this Site by <a href="https://tools.google.com/dlpage/gaoptout/">disabling the Google Analytics cookie</a> on your browser.</p>
    
    <li>Google Adwords: </li><p>Allow us to deliver targeted information to users who look for our Service.</p>
    
    <li>Google Adsense: </li><p>Allow us to monitize our website and help us understand the statics about advertisements.</p>
    
    <li>Statcounter : </li><p>Allows us to understand how people interact with the Site, and help us to optimize Site performance, usability and users' experience in real time.	</p>
    
   </ul>
   
  </div>
  
 	<p>&nbsp;</p>
  
  <p><strong>Contacting Us</strong></p>
  <p>If you have any questions about our Privacy Policy, or if you want to know what information we have collected about you, please email us at support@winwinhost.com. You can also correct any factual errors in that information or require us to remove your details from any list under our system. </p>
  


 
   </div>
   
   
  </div>

 </div>
</div>












