
<!-- <?php $role = Zend_Auth::getInstance()->getIdentity()->member_role; ?> -->
<!--

	 	  <?php foreach($this->data as $dd): ?> 
		  <?php echo $dd['members_location_lati'] ?><?php echo $dd['members_location_longi'] ?>
		  <?php endforeach; ?>
 
	 36.44090201 -115.5987506	
	  -->
 
    
    <?php foreach($this->datachild as $datachild): ?> 	

<?php endforeach; ?>
    
    <head>

    
<script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
      var line;
	  
	  var symbolOne = {
		  path: 'M -2,0 0,-2 2,0 0,2 z',
		  strokeColor: '#F00',
		  fillColor: '#F00',
		  fillOpacity: 1
		};
		
		var symbolTwo = {
		  path: 'M -2,-2 2,2 M 2,-2 -2,2',
		  strokeColor: '#292',
		  strokeWeight: 1,
		  scale:1
		};
		
		var symbolThree = {
		  path: google.maps.SymbolPath.CIRCLE,
		  rotation: 0,
		  scale:7,
          strokeColor: '#F00'
		};
		
		var symbolZero = {
		  path: google.maps.SymbolPath.CIRCLE,
		  strokeColor: '#8CCE39',
		  rotation: 0,
		  scale:7,
          
		};

      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(<?php echo $dd['members_location_lati'] ?>,<?php echo $dd['members_location_longi'] ?>),
          zoom:10,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById('map_canvas'),
            mapOptions);

        var lineCoordinates = [

		  <?php foreach($this->data as $dd): ?> 
		  new google.maps.LatLng(<?php echo $dd['members_location_lati'] ?>,<?php echo $dd['members_location_longi'] ?>),
		  <?php endforeach; ?>

        ];
		
		var flightPlanCoordinates = [
		<?php foreach($this->data as $dd): ?>
		new google.maps.LatLng(<?php echo $dd['members_location_lati'] ?>,<?php echo $dd['members_location_longi'] ?>) , 
		<?php endforeach; ?>];
		
		  var flightPath = new google.maps.Polyline({
			path: flightPlanCoordinates,
			strokeColor: "#000",
			strokeOpacity: 1.0,
			strokeWeight: 4
		  });
		
		  flightPath.setMap(map);
  

        var lineSymbol = {
          path: google.maps.SymbolPath.CIRCLE,
          scale: 8,
          strokeColor: '#C00'
        };

        line = new google.maps.Polyline({
          path: lineCoordinates,
          icons: [{
    icon: symbolOne,
    offset: '0%'
    },{
      icon: symbolZero,
      offset: '0%'},{ icon: symbolTwo,offset: '05%'},{icon: symbolTwo,offset: '10%'},{ icon: symbolTwo,offset: '15%'},{icon: symbolTwo,offset: '20%'},
	  { icon: symbolTwo,offset: '25%'},{icon: symbolTwo,offset: '30%'},{ icon: symbolTwo,offset: '35%'},{icon: symbolTwo,offset: '40%'},
	  { icon: symbolTwo,offset: '45%'},{icon: symbolTwo,offset: '50%'},{ icon: symbolTwo,offset: '55%'},{icon: symbolTwo,offset: '60%'},
	  { icon: symbolTwo,offset: '65%'},{icon: symbolTwo,offset: '70%'},{ icon: symbolTwo,offset: '75%'},{icon: symbolTwo,offset: '80%'},
	  { icon: symbolTwo,offset: '85%'},{icon: symbolTwo,offset: '90%'},{ icon: symbolTwo,offset: '95%'},
	  {
      icon: symbolThree,
      offset: '100%'
    }
  ],
          map: map
        });
      }

      function animateCircle() {
          var count = 0;
          offsetId = window.setInterval(function() {
            count = (count + 1) % 200;

            var icons = line.get('icons');
            icons[0].offset = (count / 2) + '%';
            line.set('icons', icons);
        }, 200);
      }
	  
	  
	  
	  

	  </script> 
      
     
    
      
   
</head>

<body onLoad="initialize(); animateCircle();">


<section id="content" class="container clearfix">

	<header class="page-header">
		
			
      
<h1 class="page-title">Recent Movement Track  of 
			
			<?php echo $this->childName; ?> 
            
             </h1>
			
		</header><!-- end .page-header -->
	
	
    
<h3 class="title"> Your Recent Movement Track </h3>
				<h5> Please zoom out if track is larger than the map screen , you can also see street view by click the human figure on map controls </h5>
               <p></p>
               <!-- ui-dialog -->
		
			<div id="map_canvas"></div>

			</div>
            
            
            <form name="location" action="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>" method="post" >
            <table id="customers">
            <tbody>
            <tr>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Action</th>
            </tr>
            <tr>
            
                <td><input style="width:80%; max-width:90;" type="text" id="datepicker3" name="start_date" width="100%" value="Select" /></td>
                <td><input style="width:80%; max-width:90;" type="text" id="datepicker4" name="end_date" width="100%" value="Select" /></td>	
                <td><input style="width:80%; max-width:90;" type="submit" value="Go"/></td>
            </tr>
            </tbody>	
            </table> 
            </form>

            
		</article>
        
        <p class="info"><strong>Services :</strong> You can also view the following logs for <strong><?php echo $this->childName; ?> </strong></p>
<section id="main">
    <article class="entry single clearfix">
        
        
        
        <?php if ($role == 2 ): ?>
    
    
    <section id="portfolio-items" class="clearfix">

        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-location.png" alt="">
        
                    <a class="project-meta" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">
                        <h5 class="title">Latest Location</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
	
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-tracks.png" alt="">
        
                    
                    <a class="project-meta" title="Recent Movement Track" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Movement Tracks</h5>
                    </a>
                    
                 </article>
                 
                 <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a class="project-meta" title="view Safety Maps" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Safty Maps</h5>
                    </a>
                    
                 </article>
                 
                 <!-- end .one-fourth (Altered) -->
       <!-- <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a href="#" class="project-meta">
                        <h5 class="title">Safty Map</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                <!-- <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-surfing.png" alt="">
        
                    <a href="#" class="project-meta">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 
                 
                 
                 <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-surfing.png" alt="">
        
        
                    <a class="project-meta" title="Web Browsing History of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 
                 
                 
       <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">Phone Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">

                        <h5 class="title">Email Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
     <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-calllog.png" alt="">
        
                    <a class="project-meta" title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">In-Coming/Outgoing Call Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <!-- end .one-fourth (Altered) -->
        
        
         <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-texts.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">In-Coming/Outing SMS Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-video.png" alt="">
        
                    <a class="project-meta" title="View Video files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Video Track List</h5>
                    </a>
                    
                 </article>
                 
                 
              
                 
              <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-audio.png" alt="">
        
                    <a class="project-meta" title="Listen Audio files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Audio Files</h5>
                    </a>
                    
                 </article>
                 
                 
        
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-multimedia.png" alt="">
        
                   <a class="project-meta" title="View Image files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Image Files List</h5>
                    </a>
                    
                 </article>
                 

		

	</section>
    
    
    <?php elseif ($role == 3 ): ?>
    
    <section id="portfolio-items" class="clearfix">

        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-location.png" alt="">
        
                    <a class="project-meta" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">
                        <h5 class="title">Latest Location</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
	
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-tracks.png" alt="">
        
                    
                    <a class="project-meta" title="Recent Movement Track" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Movement Tracks</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 <!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a class="project-meta" title="view Safety Maps" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Safty Maps</h5>
                    </a>
                    
                 </article>

                 
                 
                 <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-surfing.png" alt="">
        
        
                    <a class="project-meta" title="Web Browsing History of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 
                 
                 
       <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">Phone Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Email Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
     <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-calllog.png" alt="">
        
                    <a class="project-meta" title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">In-Coming/Outgoing Call Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <!-- end .one-fourth (Altered) -->
        
        
         <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-texts.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">In-Coming/Outing SMS Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 
                 
                  <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-hotwords.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'showhword','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">SMS including Hot Words</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->

                 
        <!-- end .one-fourth (Altered) -->
      <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-video.png" alt="">
        
                    <a class="project-meta" title="View Video files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Video Track List</h5>
                    </a>
                    
                 </article>
                 
                 
              
                 
              <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-audio.png" alt="">
        
                    <a class="project-meta" title="Listen Audio files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Audio Files</h5>
                    </a>
                    
                 </article>
                 
                 
        
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-multimedia.png" alt="">
        
                   <a class="project-meta" title="View Image files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Image Files List</h5>
                    </a>
                    
                 </article>
                 

		

	</section>
    
    
    
    <?php elseif ($role == 5 ): ?>
    
    <section id="portfolio-items" class="clearfix">

        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-location.png" alt="">
        
                    <a class="project-meta" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">
                        <h5 class="title">Latest Location</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
	
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-tracks.png" alt="">
        
                    
                    <a class="project-meta" title="Recent Movement Track" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Movement Tracks</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 <!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a class="project-meta" title="view Safety Maps" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Safty Maps</h5>
                    </a>
                    
                 </article>

                 
                 
                 <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-surfing.png" alt="">
        
        
                    <a class="project-meta" title="Web Browsing History of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 
                 
                 
       <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">Phone Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Email Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
     <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-calllog.png" alt="">
        
                    <a class="project-meta" title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">In-Coming/Outgoing Call Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <!-- end .one-fourth (Altered) -->
        
        
         <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-texts.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">In-Coming/Outing SMS Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 
                 
                  <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-hotwords.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'showhword','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">SMS including Hot Words</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->

                 
        <!-- end .one-fourth (Altered) -->
      <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-video.png" alt="">
        
                    <a class="project-meta" title="View Video files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Video Track List</h5>
                    </a>
                    
                 </article>
                 
                 
              
                 
              <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-audio.png" alt="">
        
                    <a class="project-meta" title="Listen Audio files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Audio Files</h5>
                    </a>
                    
                 </article>
                 
                 
        
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-multimedia.png" alt="">
        
                   <a class="project-meta" title="View Image files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Image Files List</h5>
                    </a>
                    
                 </article>
                 

		

	</section>
    
      <?php endif; ?> 
        
        

	</section><!-- end #main -->

	<aside id="sidebar">
    
    
    
    
  
            

            
            <div class="widget">
    <p class="info"><strong>other Family Members </strong></p>        



	<?php foreach($this->datachild2 as $datachild2): ?> 		
 
 
        <ul class="circle">
				
				<li><h4 class="name"><a title="view phone data of <?php echo $datachild2->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'child','action' => 'index', 'id'=>$datachild2->id, 'name'=> $datachild2->child_name));?>"><?php echo $datachild2->child_name; ?></a></h4></li>
                
				
			</ul>
 
			<?php endforeach; ?>
			
			</div>

		<!-- end .widget -->



	</aside><!-- end #sidebar -->
	
</section>