<head>

<meta name="description" content="Track mobile phone call details from the Phone of your concerned person , you can now keep close eye on all the incoming and outgoing calls with Phone Tracker.">
        
</head>

<section id="content" class="container clearfix">

	<article class="single-project">

		<header class="page-header">

			<h1 class="page-title align-left">Phone-tracker features</h1>
			
			<a class="button no-bg medium align-right" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'index'));?>
            							">
				All Features <img src="/images/icon-grid.png" alt="" class="icon">
			</a>

			<hr />

			<h2 class="project-title">In-coming / Out-going Call Log</h2>

			<ul class="portfolio-pagination">
				<li class="prev"><a class="button medium no-bg" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'webbrowsingtracking'));?>
            							"><span class="arrow left">&raquo;</span> Previous</a></li>
				<li class="next"><a class="button medium no-bg" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'gpslocationtracking'));?>
            							">Next <span class="arrow">&raquo;</span></a></li>
			</ul><!-- end .portfolio-pagination -->
			
		</header><!-- end .page-header -->

		<div id="main">
		
			<div class="image-gallery-slider">

				<ul>

					<li>
						
							<img src="/images/phone-calls-tracking.jpg" alt="track In-Coming/ Out-going Call logs">
			
					</li>
                    
                    <li>
						
							<img src="/images/phone-calls-tracking-2.jpg" alt="track In-Coming/ Out-going Call logs">
			
					</li>




				</ul>
                
                <p>&nbsp;</p>
                
				
			</div><!-- end .image-gallery-slider -->
<p><span class="dropcap">C</span>all logs can be handy for keeping in touch with recent in-coming and outgoing calls weather use it for yourself or to keep aware of your children or anyother person. Now you can even View call or recent days , weeks and Months <p>		    		
		</div><!-- end #main -->

		<div id="sidebar">

			<h4>Overview</h4>

			<p>C</span>all logs can be handy for keeping in touch with recent in-coming and outgoing calls weather use it for yourself or to keep aware of your children or anyother person. <p>

			

			<p>
				<a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'register'));?>
            							">Sign-Up Now</a>
			</p>
			<div class="widget">
                   
                    
                            
            </div>
            
            <script type="text/javascript">
			
			<!--
			google_ad_client = "ca-pub-4906488699730089";
			/* phonetracker real sqaure */
			google_ad_slot = "9271220908";
			google_ad_width = 200;
			google_ad_height = 200;
			//-->
			
			</script>
			<script type="text/javascript"
			src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
			
             <div class="infobox">
                    
                                <h3>Have you not Downloaded the Phone Tracker's Android app Yet?</h3>
                    
                               <p><a target="_blank" title="Phone Track app free download" href="https://play.google.com/store/apps/details?id=com.mobiletracker"><img src="/images/androidmarket.png" alt="Download phone tracker android app from Google Play" title="Download phone tracker android app from Google Play"></a>
                                   
                                </p>
                    
                            </div>


		</div><!-- end #sidebar -->
		
	</article><!-- end .single-project -->
	
</section>