<head>

<meta name="description" content="Mobile phone spy features of Phone Tracker allows you to keep close on the concerned person's GPS location, movement tracks , phone numbers , email addresses , all incoming and outgoing calls  , all incoming and outgoing sms , hotword out of sms  , and even web browsing..">
        
</head>


<section id="content" class="container clearfix">

	<header class="page-header">
	
		<h1 class="page-title">Features Empowering Phone-Tracker</h1>

		<ul id="portfolio-items-filter">

			<li>Showing</li>
			<li><a data-categories="*">All</a></li>
			<li><a data-categories="location">Location</a></li>
			<li><a data-categories="contacts">Contacts</a></li>
            <li><a data-categories="log">Log</a></li>
			<li><a data-categories="multimedia">Multimedia </a></li>
			<li><a data-categories="internet">Internet</a></li>
            

		</ul><!-- end #portfolio-items-filter -->
		
	</header><!-- end .page-header -->

	<section id="portfolio-items" class="clearfix">

		<article class="one-third" data-categories="location">

			
				<img img src="/images/phone-gps-tracking_thumb.jpg" alt="Latest Location" width="300">
			

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'gpslocationtracking'));?>" class="project-meta">
				<h5 class="title">Location</h5>
				<span class="categories">Location</span>
			</a>
			
		</article><!-- end .one-third  -->

		<article class="one-third" data-categories="location">

			 
				<img src="/images/location-movement-tracking_thumb.jpg" alt="Location Movement Tracks" width="300">
		 

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'locationmovementtracking'));?>" class="project-meta">
				<h5 class="title">Movement Tracks</h5>
				<span class="categories">Location</span>
			</a>
			
		</article><!-- end .one-third  -->



		<article class="one-third" data-categories="location">

		 
				<img src="/images/tracking-neigbourhood-dangers_thumb.jpg" alt="Tracking Neigbourhood Dangers" width="300">
	 

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'trackingneigbourhooddangers'));?>" class="project-meta">
				<h5 class="title">Nearby Safety Map</h5>
				<span class="categories">Location</span>
			</a>
			
		</article><!-- end .one-third  -->


		<article class="one-third" data-categories="log">

	
				<img src="/images/phone-texts-tracking_thumb.jpg" alt="SMS Tracking" width="300">


			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'texttracking'));?>" class="project-meta">
				<h5 class="title">SMS Log</h5>
				<span class="categories">Texts</span>
			</a>
			
		</article><!-- end .one-third-->





		<article class="one-third" data-categories="contacts">

			 
				<img src="/images/phone-contacts-tracking_thumb.jpg" alt="Tracking Contacts" width="300">
			 

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'contactstracking'));?>" class="project-meta">
				<h5 class="title">Phone Contacts </h5>
				<span class="categories">Contacts</span>
			</a>
			
		</article><!-- end .one-third -->
        
        
        
        <article class="one-third" data-categories="contacts">

			 
				<img src="/images/phone-contacts-tracking_thumb.jpg" alt="Tracking Contacts" width="300">
			 

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'contactstracking'));?>" class="project-meta">
				<h5 class="title">Email Contacts </h5>
				<span class="categories">Contacts</span>
			</a>
			
		</article><!-- end .one-third -->
        
        

		<article class="one-third" data-categories="multimedia">

			 
				<img src="/images/phone-multimedia-tracking_thumb.jpg" alt="Multimedia Tracking" width="300">
	 

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'multimediatracking'));?>" class="project-meta">
				<h5 class="title">Multimedia </h5>
				<span class="categories">Multimedia </span>
			</a>
			
		</article><!-- end .one-third  -->




		<article class="one-third" data-categories="internet">

  
				<img src="/images/phone-internet-surfing-tracking_thumb.jpg" alt="Internet Surfing Tracking" width="300">
 

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'webbrowsingtracking'));?>" class="project-meta">
				<h5 class="title">Web Browsing History</h5>
				<span class="categories">Internet</span>
			</a>
			
		</article><!-- end .one-third -->

		<article class="one-third" data-categories="log">

			 
				<img src="/images/phone-calls-tracking_thumb.jpg" alt="Call Log" width="300">
 

			<a href="<?php echo $this->url(array('module' => 'default','controller' => 'features','action' => 'calllogstracking'));?>" class="project-meta">
				<h5 class="title">Call Log</h5>
				<span class="categories">Calls</span>
			</a>
			
		</article><!-- end .one-third -->



	</section><!-- end #portfolio-items -->
	
</section>
