<head>

<meta name="description" content="Track GPS movement tracks of the mobile phone of the concerned person , you can now keep close eye on all the past movement tracks with Phone Tracker.">
        
</head>

<section id="content" class="container clearfix">

	<article class="single-project">

		<header class="page-header">

			<h1 class="page-title align-left">Phone-tracker features</h1>
			
			<a class="button no-bg medium align-right" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'index'));?>
            							">
				All Features <img src="/images/icon-grid.png" alt="" class="icon">
			</a>

			<hr />

			<h2 class="project-title">Movement Tracks</h2>

			<ul class="portfolio-pagination">
				<li class="prev"><a class="button medium no-bg" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'gpslocationtracking'));?>
            							"><span class="arrow left">&raquo;</span> Previous</a></li>
				<li class="next"><a class="button medium no-bg" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'trackingneigbourhooddangers'));?>
            							">Next <span class="arrow">&raquo;</span></a></li>
			</ul><!-- end .portfolio-pagination -->
			
		</header><!-- end .page-header -->

		<div id="main">
		
			<div class="image-gallery-slider">

				<ul>

					<li>
						<img src="/images/location-movement-tracking.jpg" alt="Location Movement Tracks">
					
					</li>

					<li>
						<img src="/images/location-movement-tracking-2.jpg" alt="Location Movement Tracks">
					
					</li>

				</ul>
                
                <p>&nbsp;</p>
                
				
			</div><!-- end .image-gallery-slider -->
<p><span class="dropcap">V</span>iew tracks of your conerned people whenever you get time. View tracks of past days and weeks and see where they have been and ensure they lie to you.<p>

				<p>Suppose your company provides mobile phones to your employees in the field. How do you know if they are traveling to their assigned destinations? Or image your child tells you they are visiting a friend's house that you approve but instead goes somewhere you told them not to go. With Mobile Spy Smartphone Monitoring Software you will know exactly where your employees or children are when they are away.<p>		    		
		</div><!-- end #main -->

		<div id="sidebar">

			<h4>Overview</h4>

			<p>View tracks of your conerned people whenever you get time. View tracks of past days and weeks and see where they have been and ensure they lie to you.<p>
 
			<p>
				<a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'register'));?>
            							">Sign-Up Now</a>
			</p>
			<div class="widget">
                   
                    <script type="text/javascript">
			
			<!--
			google_ad_client = "ca-pub-4906488699730089";
			/* phonetracker real sqaure */
			google_ad_slot = "9271220908";
			google_ad_width = 200;
			google_ad_height = 200;
			//-->
			
			</script>
			<script type="text/javascript"
			src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
			
            
            <div class="infobox">
                    
                                <h3>Have you not Downloaded the Phone Tracker's Android app Yet?</h3>
                    
                               <p><a target="_blank" title="Phone Track app free download" href="https://play.google.com/store/apps/details?id=com.mobiletracker"><img src="/images/androidmarket.png" alt="Download phone tracker android app from Google Play" title="Download phone tracker android app from Google Play"></a>
                                   
                                </p>
                    
                            </div>
             
                            
            </div>
		</div><!-- end #sidebar -->
		
	</article><!-- end .single-project -->
	
</section>