<head>

<meta name="description" content="spy on mobile phone image , audio , video files on cell Phone of your concerned person , you can now keep close eye on all media files with Phone Tracker.">
        
</head>

<section id="content" class="container clearfix">

	<article class="single-project">

		<header class="page-header">

			<h1 class="page-title align-left">Phone-tracker features</h1>
			
			<a class="button no-bg medium align-right" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'index'));?>
            							">
				All Features <img src="/images/icon-grid.png" alt="" class="icon">
			</a>

			<hr />

			<h2 class="project-title"> Images / Audio / Video </h2>

			<ul class="portfolio-pagination">
				<li class="prev"><a class="button medium no-bg" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'contactstracking'));?>
            							"><span class="arrow left">&raquo;</span> Previous</a></li>
				<li class="next"><a class="button medium no-bg" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'features',
    									'action' => 'webbrowsingtracking'));?>
            							">Next <span class="arrow">&raquo;</span></a></li>
			</ul><!-- end .portfolio-pagination -->
			
		</header><!-- end .page-header -->

		<div id="main">
		
			<div class="image-gallery-slider">

				<ul>

					<li>
						
							<img src="/images/phone-multimedia-tracking.jpg" alt="Images / Audio / Video file tracking">
					
					</li>
                    
                    <li>
						
							<img src="/images/phone-multimedia-tracking-2.jpg" alt="Images / Audio / Video file tracking">
					
					</li>
                    <li>
						
							<img src="/images/phone-multimedia-tracking-3.jpg" alt="Images / Audio / Video file tracking">
					
					</li>
                    <li>
						
							<img src="/images/phone-multimedia-tracking-4.jpg" alt="Images / Audio / Video file tracking">
					
					</li>


				</ul>
                
                <p>&nbsp;</p>
                
				
			</div><!-- end .image-gallery-slider -->
<p><span class="dropcap">M</span>ultimedia files lists like images , audio files , video files , having a list of these at one place help you manage your content. In case of child it would let you know his/her interests and much more. You can listen audio files , view images , and play videos online even you download them , its like have a virtual Harddisk/memory at internet. <p>		    		
		</div><!-- end #main -->

		<div id="sidebar">

			<h4>Overview</h4>

			<p>Multimedia files lists like images , audio files , video files , having a list of these at one place help you manage your content. In case of child it would let you know his/her interests and much more<p>

			

			<p>
				<a class="button" href="<?php echo $this->url(array(
    									'module' => 'default',
    									'controller' => 'user',
    									'action' => 'register'));?>
            							">Sign-Up Now</a>
			</p>
			<div class="widget">
                   
                    <script type="text/javascript">
			
			<!--
			google_ad_client = "ca-pub-4906488699730089";
			/* phonetracker real sqaure */
			google_ad_slot = "9271220908";
			google_ad_width = 200;
			google_ad_height = 200;
			//-->
			
			</script>
			<script type="text/javascript"
			src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
            
            
            <div class="infobox">
                    
                                <h3>Have you not Downloaded the Phone Tracker's Android app Yet?</h3>
                    
                               <p><a target="_blank" title="Phone Track app free download" href="https://play.google.com/store/apps/details?id=com.mobiletracker"><img src="/images/androidmarket.png" alt="Download phone tracker android app from Google Play" title="Download phone tracker android app from Google Play"></a>
                                   
                                </p>
                    
                            </div>
			
             
                            
            </div>
		</div><!-- end #sidebar -->
		
	</article><!-- end .single-project -->
	
</section>