<section id="content" class="container clearfix">

	<header class="page-header">
	
		<h1 class="page-title"> Sign in with your Phone-Tracker Account </h1>
		
	</header><!-- end .page-header -->
	
	<section id="main">



        <article class="entry clearfix">

			
        <div style="margin-left: auto;">
        
     
        
        <?php echo $this->form; ?>

        
        </div>
        
        </article>
        


	</section><!-- end #main -->

	<aside id="sidebar">
    			

		<div class="widget">
        
		<script type="text/javascript"><!--
google_ad_client = "ca-pub-4906488699730089";
/* phonetracker real sqaure */
google_ad_slot = "9271220908";
google_ad_width = 200;
google_ad_height = 200;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
		
        <div class="fb-like-box" data-href="http://www.facebook.com/phonetrackerdotnet" data-width="240" data-show-faces="true" data-border-color="white" data-stream="false" data-header="true"></div>

		</div><!-- end .widget -->

		
		
	</aside><!-- end #sidebar -->
	
</section>






