<head>

<meta name="description" content="You can change your Phone Tracker's account password here">

</head>

<section id="content" class="clearfix">

	<div class="container clearfix">

		<header class="page-header">
		
			<h1 class="page-title">Please Change Your Password here </h1>
			
		</header><!-- end .page-header -->

	</div><!-- end .container -->


	<div class="container clearfix">
		
		<!-- end .one-fourth -->
		
		<div class="three-fourth last">
        
        <?php echo $this->form; ?>

			
		</div><!-- end .three-fourth.last -->

	</div><!-- end .container -->
		
</section>


