<head>
<meta name="description" content="Sign Up for Family Phone Tracker account in which you get 1 Mobile ID to Track with all the services of Phone Tracking except hotwords and some safety maps">
</head>


<script type="text/javascript">

// Get value of id - integer appended to dynamic form field names and ids
var id = $("#id").val();
 
// Retrieve new element's html from controller
function ajaxAddField() {
  $.ajax(
    {
      type: "POST",
      url: "<?php $this->url(array('action' => 'newfield', 'format' => 'html'));?>",
      data: "id=" + id,
      success: function(newElement) {
	  alert(newElement);
        // Insert new element before the Add button
        $("#account_type-label").before(newElement);
 
        // Increment and store id
        $("#id").val(++id);
      }
    }
  );
}
 
function removeField() {
 
  // Get the last used id
  var lastId = $("#id").val() - 1;
 
  // Build the attribute search string.  This will match the last added  dt and dd elements.  
  // Specifically, it matches any element where the id begins with 'newName<int>-'.
  searchString = '*[id^=newName' + lastId + '-]';
 
  // Remove the elements that match the search string.
  $(searchString).remove()
 
  // Decrement and store id
  $("#id").val(--id);
}
</script>
<section id="content" class="container clearfix">

	<header class="page-header">
	
		<h1 class="page-title"> Your free account on Phone Tracker is just one step away.</h1>
		
	</header><!-- end .page-header -->
	
	<section id="main">



        <article class="entry clearfix">

			
        <div style="margin-left: auto;">
        
     
        
        <?php echo $this->form; ?>

        
        </div>
        
        </article>
        


	</section><!-- end #main -->

	<aside id="sidebar">
    			

		<div class="widget">
        
        <div class="infobox">
                    
                                <h3>Have you not Download the phone app Yet?</h3>
                    
                                <p><a target="_blank" title="Phone Track app free download" href="https://play.google.com/store/apps/details?id=com.mobiletracker"><img src="/images/androidmarket.png" alt="Download phone tracker android app from Google Play" title="Download phone tracker android app from Google Play"></a>
                                   
                                </p>
                    
                    
                            </div>
                            
                            
        
		<script type="text/javascript"><!--
google_ad_client = "ca-pub-4906488699730089";
/* phonetracker real sqaure */
google_ad_slot = "9271220908";
google_ad_width = 200;
google_ad_height = 200;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
		
        <div class="fb-like-box" data-href="http://www.facebook.com/phonetrackerdotnet" data-width="240" data-show-faces="true" data-border-color="white" data-stream="false" data-header="true"></div>

		</div><!-- end .widget -->

		
		
	</aside><!-- end #sidebar -->
	
</section>






