<head>
<meta name="description" content="Sign Up for any Phone Tracker Service Package ie free Phone Tracker account ,family Phone Tracker account and Business Phone Tracker account">
</head>

<section id="content" class="container clearfix">

	<header class="page-header">

		<h1 class="page-title">Sign Up for any Phone Tracker Service Package</h1>

		<hr />

		<h2 class="page-description">With Different Account Type you Get Different things</h2>
		
	</header><!-- end .page-header -->
	
    
       
       
       <div class="one-third">
  		<div class="pricing_option pricing_option3">
   
   <ul>
    <li>
     <h4>Free Account </h4>
     <div class="price"><strong>&#36;</strong><span>0</span><sup>00</sup><em>monthly</em></div>
    		<p> Up to 1 Child ID </p>
            <p> Current Location , Safety Maps  </p>
            <p> Phone Numbers , Email Address </p>
            <p> Call Details , SMS Details </p>
            <p> Web Browsing History </p>
            <p> Image , Audio , video files </p>
      
     <p><a class="button" title="Sign Up now for account on Phone Tracker"  href="<?php echo $this->url(array('module' => 'default','controller' => 'user','action' => 'freeregister'));?>" >Sign Up</a></p>
    </li>

  </div>
       </div>
    
  <!--  <div class="one-third"> 
		<div class="pricing_option pricing_option3">
   
   <ul>
     
    <li >
     
     <h4>Family Account </h4>
     <div class="price"><strong>&#36;</strong><span>4</span><sup>99</sup><em>monthly</em></div>
     		<p> Up to 5 Child IDs </p>
            <p> Current Location , Safety Maps , Past Travel Tracks </p>
            <p> Phone Numbers , Email Address </p>
            <p> Call Details , SMS Details , Hotword out of SMS </p>
            <p> Web Browsing History </p>
            <p> Image , Audio , video files </p>
      
     <p><a class="button" title="Sign Up now for account on Phone Tracker"  href="<?php echo $this->url(array('module' => 'default','controller' => 'user','action' => 'familyregister'));?>" >Sign Up</a></p>
     
    </li>
     
    
    
   </ul>
  </div>
	   </div>
    
  	   <div class="one-third last">
   		<div class="pricing_option pricing_option3">
    
   <ul>
    
    <li>
     <h4>Business Account </h4>
     <div class="price"><strong>&#36;</strong><span>24</span><sup>99</sup><em>monthly</em></div>
     		<p> Up to 50 Child IDs </p>
            <p> Current Location , Past Travel Tracks , Safety Maps  </p>
            <p> Phone Numbers , Email Address </p>
            <p> Call Details , SMS Details , Hotword out of SMS </p>
            <p> Web Browsing History </p>
            <p> Image , Audio , video files </p>

      
     <p><a class="button" title="Sign Up now for account on Phone Tracker"  href="<?php echo $this->url(array('module' => 'default','controller' => 'user','action' => 'businessregister'));?>" >Sign Up</a></p>
    </li>
    
    
   </ul>
  </div>
       </div>  -->
    

	
    <hr />
    
</section>


