<div style="width:100%; height:100%; background-image:url(/); background-repeat:no-repeat; background-position:">
    <div class="layout-2cols">
        <div class="content grid_8">
            <div class="project-detail">
                <div class="project-tab-detail tabbable accordion">
                    <ul class="nav nav-tabs clearfix">
                      <li class="active"><a href="#">Find Skillful people </a></li>
                      <li><a href="#" class="be-fc-orange">Find Skill Hunters </a></li>
                    
                    </ul>
                    <div class="tab-content">
                        <div>
                            <h3 class="rs alternate-tab accordion-label">Find Skillful people</h3>
                            <div class="tab-pane accordion-content active">
                                    <div class="tab_wrapper">
                                <div class="for_sale tab_block tab_block_1 active"> 
                                <form action="search-results.html" />
                                <div> 
                                <input placeholder="Find" type="text" /> 
                               <select><option value="" disabled="disabled" selected="selected" /><option />Job Seeker<option />Investment Seeker<option /></select> 
                               
                                <input type="submit" value="" />
                               </div> 
                               </form>
                               </div>  
                            </div>
                            </div><!--end: .tab-pane -->
                        </div>
                        <div>
                            <h3 class="rs alternate-tab accordion-label">Find Skill Hunters</h3>
                            <div class="tab-pane accordion-content">
                              <div class="tab_wrapper">
                                <div class="for_sale tab_block tab_block_1 active"> 
                                <form action="search-results.html" />
                                <div> 
                                <input placeholder="Find" type="text" /> 
                                
                                <select><option value="" disabled="disabled" selected="selected" /><option />Hire Humans<option />Invest in a project<option /></select> 
                                <input type="submit" value="" />
                               </div> 
                               </form>
                               </div>  
                            </div>   
                            </div>
                        </div>
                        
                      </div>
                </div><!--end: .project-tab-detail -->
            </div>
        </div><!--end: .content -->
        <div class="sidebar grid_4">
        <div class="project-author">
          
                        <a href="/"><img src="/images/discover.png" alt="Hire Remote"/></a>
         </div>
            
            <div class="box-gray project-author">
                      
                <h5 class="title-box">Welcome to HireRemote!</h5>
                <p class="description rs">Hire a professional , Hire a Team , even Hire a ship.. or invest in the products of tomarrow</p>
                
            </div><!--end: .project-author -->
        </div><!--end: .sidebar -->
    </div>
    </div>