<div class="gerneralmain">





<div id="gerneralleftside">
<h1>How Phone Tracker works</h1>

<h2>Getting started</h2>

<p>
To use Phone Tracker ,user have create a account. Registration takes only a minute or two minutes or so. All system will ask for is a username, password, and a valid email address. 



</p>


<p>Next, user will have install a Phone Tracker application on your GPS-enabled phone with Andriod operating system. When user runs the application, it periodically sends your GPS coordinates to Phone Tracker servers. 

</p>



<p>
User can Login to his/her Phone Tracker account, and can will see the current location of his/her phone plotted on an interactive Google map. The map updates automatically every few seconds.Plus much more like previous day's tracks or check your family members status or update your status to to your family members , even you can see which of your family member or friend is near.

</p>

If user want to share your location with friends and family, users are allowed to embed a map with your location on a web page, blog, or your Facebook profile,Google Plus...
</p>

</div>
</div>