
 <section id="content" class="container clearfix">

	<header class="page-header">
		
			<h1 class="page-title">Switch your account to full access
            
             </h1>
			
		</header><!-- end .page-header -->
	
	<section id="main">
    <article class="entry single clearfix">
    
<h3 class="title"><a href="#"></a></h3>
				<h6><a href="#">with full access, you can view and manager sms hot word</a></h6>
                
<script>
function validateForm()
{
var x=document.forms["swpayacc"]["paypalacc"].value;
var atpos=x.indexOf("@");
var dotpos=x.lastIndexOf(".");
if (atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length)
  {
  alert("Not a valid paypal account");
  return false;
  }
}

</script>                

<form name="swpayacc" action="<?php echo $this->url(array('module'=>'dashboard', 'controller'=>'swpayacc', 'action'=>'index')); ?>" method="post" onsubmit="return validateForm()" >
<table id="customers">
<tbody><tr>
<th>Please Enter your paypal account</th>
</tr>
<tr >
    <td style="padding:20px;">
		<!--<p><input name="paypalacc" type="text" /></p>		
		--> 
		<ul>
            <li><label>First Name:</label><input type="text" name="first_name" value="" /></li>
            <li><label>Last Name:</label><input type="text" name="last_name" value="" /></li>
            <li><label>Address, Line 1:</label><input type="text" name="address1" value="" /></li>
            <li><label>Address, Line 2:</label><input type="text" name="address2" value="" /></li>
            <li><label>City:</label><input type="text" name="city" value="" /></li>
            <li><label>State (2-Letter):</label><input type="text" name="state" value="" /></li>
            <li><label>Zip:</label><input type="text" name="zip" value="" /></li>
            <li><label>Card Type</label><input type="text" name="credit_card_type" value="" /></li>
            <li><label>Card number</label><input type="text" name="credit_card_number" value="" /></li>
		</ul>
		
		<p><input type="submit" name="Add Word" value="Done"/></p>
	</td>	
</tr>	
</tbody>	
</table>    
</form>
 
			</div>


			<!-- end .entry-body -->

			<!-- end .entry-meta -->
            
		</article>
        
       <!-- <p class="info"><strong>Services : You can View the following logs for <strong><?php echo $this->childName; ?> </strong></p> -->
        
 

	</section><!-- end #main -->

	<aside id="sidebar">
    
    
                    
                    <div class="widget">
                    
		<h6 class="widget-title">Twitter Feed</h6>
						<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
                        <script>
                        new TWTR.Widget({
                          version: 2,
                          type: 'profile',
                          rpp: 3,
                          interval: 30000,
                          width:'auto',
                          height: 220,
                          theme: {
                            shell: {
                              background: '#6e6e6e',
                              color: '#ffffff'
                            },
                            tweets: {
                              background: '#575457',
                              color: '#ffffff',
                              links: '#a3a3a3'
                            }
                          },
                          features: {
                            scrollbar: false,
                            loop: false,
                            live: false,
                            behavior: 'all'
                          }
                        }).render().setUser('winwinhost').start();
                        </script>

		</div>


	</aside><!-- end #sidebar -->
	
</section>