<!-- <?php $role = Zend_Auth::getInstance()->getIdentity()->member_role; ?> --><head>
<!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Le styles -->
    <!-- Use new way for google web fonts 
    http://www.smashingmagazine.com/2012/07/11/avoiding-faux-weights-styles-google-web-fonts -->
    <!-- Headings -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css' />  -->
    <!-- Text -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css' /> --> 
    <!--[if lt IE 9]>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:700" rel="stylesheet" type="text/css" />
    <!-- THIS IS DOWNLOADED FROM WWW.SXRIPTGATES.COM - SO THIS IS YOUR NEW SITE FOR DOWNLOAD SCRIPT ;) -->
    <![endif]-->

    <link href="http://new.winwinhost.com/wwwroot/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/bootstrap/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/supr-theme/jquery.ui.supr.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Plugin stylesheets -->
    <link href="http://new.winwinhost.com/wwwroot/plugins/qtip/jquery.qtip.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/jpages/jPages.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/prettify/prettify.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/inputlimiter/jquery.inputlimiter.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/ibutton/jquery.ibutton.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/uniform/uniform.default.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/color-picker/color-picker.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/select/select2.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/validate/validate.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/pnotify/jquery.pnotify.default.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/pretty-photo/prettyPhoto.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/smartWizzard/smart_wizard.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/dataTables/jquery.dataTables.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/elfinder/elfinder.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/plupload/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" rel="stylesheet" />

    <!-- Main stylesheets -->
    <link href="http://new.winwinhost.com/wwwroot/css/main.css" rel="stylesheet" type="text/css" /> 

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/apple-touch-icon-144-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/apple-touch-icon-114-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/apple-touch-icon-72-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-57-precomposed.png" />
    
    <!-- Le javascript
    ================================================== -->

     <!-- Le javascript
    ================================================== -->
  
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/bootstrap/bootstrap.js"></script>  
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/jquery.mousewheel.js"></script>

    <!-- Load plugins -->
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/qtip/jquery.qtip.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.grow.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.pie.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.resize.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.tooltip_0.4.4.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.orderBars.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/knob/jquery.knob.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/fullcalendar/fullcalendar.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/prettify/prettify.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/watermark/jquery.watermark.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/elastic/jquery.elastic.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/inputlimiter/jquery.inputlimiter.1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/maskedinput/jquery.maskedinput-1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/ibutton/jquery.ibutton.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/uniform/jquery.uniform.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/stepper/ui.stepper.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/color-picker/colorpicker.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/timeentry/jquery.timeentry.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/select/select2.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/dualselect/jquery.dualListBox-1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/tiny_mce/jquery.tinymce.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/validate/jquery.validate.min.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/animated-progress-bar/jquery.progressbar.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/pnotify/jquery.pnotify.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/lazy-load/jquery.lazyload.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/jpages/jPages.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/pretty-photo/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/smartWizzard/jquery.smartWizard-2.0.min.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/touch-punch/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/ios-fix/ios-orientationchange-fix.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/dataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/elfinder/elfinder.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/plupload.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/plupload.html4.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/responsive-tables/responsive-tables.js"></script>

    <!-- Init plugins -->
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/statistic.js"></script><!-- Control graphs ( chart, pies and etc) -->

    <!-- Important Place before main.js  -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/main.js"></script>
   
    <script type="text/javascript">
        //adding load class to body and hide page
        document.documentElement.className += 'loadstate';
    </script>
</head>

<?php  if ($role == 1 ): ?>

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>Manage the FAQs Here<span> Add, Edit , Delete</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
              
</div>

<div class="wraper">                
                  
                    <div class="row-fluid">

                        <div class="span12">

                            <div class="box ">

                                <div class="title">

                                    <h4 class="left">
                                        <span class="icon16 brocco-icon-grid"></span>
                                        <span>FAQs</span>
                                    </h4>
                                    
                                    <form class="box-form right" action="" />
                                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'faqs','action' => 'add'));?>" style="padding:10px; margin-top:5px;">
                                        <span class="" >Write New Question</span></a>
                                    </form>
                                    <!--<a href="#" class="minimize">Minimize</a> -->
                                    <div class="clearfix"></div>
                                </div>
                                
                                
                                <div class="content noPad clearfix">
                                    <table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                            <th>ID</th>
                                            <th>Question</th>
                                            <th>Posted</th> 
                                            <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach($this->data as $faqs): ?>
                                            <tr class="">
                                            <td><?php echo $faqs->faq_id; ?></td>
                                            <td><?php echo $faqs->faq_title; ?></td>
                                            <td><?php echo $faqs->faq_posted; ?></td> 
                                                <td class="center">
                                                <div class="controls center">
                                                    <a title="Edit Post" class="tip" href="<?php echo $this->url(array(
													'module' => 'dashboard', 
													'controller' => 'faqs',
													'action' => 'edit',
													'id' => $faqs->faq_id)); ?>"><span class="icon12 icomoon-icon-pencil"></span></a>
																							<a title="Remove Post" class="tip" href="<?php echo $this->url(array(
													'module' => 'dashboard',
													'controller' => 'faqs',
													'action' => 'delete',
													'id' => $faqs->faq_id)); ?>/"><span class="icon12 icomoon-icon-remove"></span></a>
                                                </div>
                                                </td>
                                            </tr>
                                         <?php endforeach; ?>  
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                               <th>ID</th>
                                            <th>Title</th>
                                            <th>Posted</th> 
                                            <th>Actions</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>

                            </div><!-- End .box -->

                        </div><!-- End .span12 -->

                    </div>
 
</div>                    
 
<?php  elseif ($role == 2 ): ?>

<div class="container clearfix fitvids">
<div id="page-heading">
    <h1>Member</h1>	   	
</div>
<!-- /page-heading -->
<div class="post full-width clearfix">
Hello
</div>
<!-- /post -->
<div class="clear"></div>
</div><!-- /container -->

<?php elseif ($role == 3 ): ?>  

<div class="container clearfix fitvids">
<div id="page-heading">
    <h1>Hosting</h1>	   	
</div>
<!-- /page-heading -->
<div class="post full-width clearfix">
Hello
</div>
<!-- /post -->
<div class="clear"></div>
</div><!-- /container -->
	

<?php elseif ($role == 4 ): ?> 

<div class="container clearfix fitvids">
<div id="page-heading">
    <h1>Domain</h1>	   	
</div>
<!-- /page-heading -->
<div class="post full-width clearfix">
Hello
</div>
<!-- /post -->
<div class="clear"></div>
</div><!-- /container -->	


<?php endif; ?>