<head>

<meta name="description" content="">
 
        <script type="text/javascript">
	$(document).ready(function() 
    	{ 
      	  $(".tablesorter").tablesorter(); 
   	 } 
	);
	$(document).ready(function() {

	//When page loads...
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content

	//On Click Event
	$("ul.tabs li").click(function() {

		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content

		var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active ID content
		return false;
	});

});
    </script>

<script>
        $(function() {
    
            $("#first").organicTabs();
            
            $("#second").organicTabs({
                "speed": 150
            });
    
        });
    </script>
      
    <script type="text/javascript" language="javascript">
	addtocart = function(domain_name, id) {
		var url = "<?php echo $this->url(array('controller' => 'index', 'action' => 'addtocart'));?>";
		$.ajax({	
			type: 'POST',
			url: url,
			data: {domain: domain_name}
		}).done(function() { 
			$('#item_' + id).hide();
			$('#status_' + id).show();
		});	
		return false;
	}
	</script>	 
    
     <style>
		.cl-status {
			display: none;
			float: right;

			
			border-radius:3px;
			background-color:#0d9ce0;
			color:#fff;
			text-shadow:0px 0px 0px #066ad0;
			font-size:1.1em;
			text-decoration:none;
			padding:4px 10px 4px 10px;
	
			height:auto;
		
		}
	</style>
    
</head>

<!-- one bt one slider -->
    

        <div class="content_block">
        
         <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>First Check Avialibity of <strong> Domain Name </strong><span> of your choice than proceed to buy it </span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 

        <div class="wraper">
        
        
        
        <section id="main_domaincheck">
  
        <div id="second">
					
    		<ul class="nav">
                <li class="nav-two" style="height:40px;"><a href="#domains" class="current">Register</a></li>
                <!-- <li class="nav-one"><a href="#hosting" > Hosting & Servers </a></li> -->
                <li class="nav-two last"><a href="#domainprices"> Domain Prices </a></li>
                
            </ul>
    		
    		<div class="list-wrap" >
            
    		<?php if(is_null($this->result)): ?>
            
    			<ul id="domains" >
    				
                    <section id="searchbar">
<form class="form-wrapper cf" method="post" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'domaincheck')); ?>">
	<input type="text" placeholder="Search domain name .." name="domain" required autofocus>
    	<select name="extension">
            <option value=".com">.com</option>
            <option value=".info" >.info</option>
            <option value=".net" >.net</option> 
            <option value=".me" >.me</option>
            <option value=".org" >.org</option>
            <option value=".biz" >.biz</option> 
            <option value=".com.co" >.com.co</option>
            <option value=".net.co" >.net.co</option>
            <option value=".nom.co" >.nom.co</option>
            <option value=".mobi" >.mobi</option>
            <option value=".mx" >.mx</option>
            <option value=".com.es" >.com.es</option>
            <option value=".ws" >.ws</option>
            <option value=".us" >.us</option>
            <option value=".nom.es" >.nom.es</option>
            <option value=".es" >.es</option>
            <option value=".org.es" >.org.es</option>
            <option value=".nl" >.nl</option>
            <option value=".in" >.in</option>
            <option value=".com.mx" >.com.mx</option>
            <option value=".bz" >.bz</option>
            <option value=".com.bz" >.com.bz</option>
            <option value=".co.in" >.co.in</option>
            <option value=".firm.in" >.firm.in</option>
            <option value=".gen.in" >.gen.in</option>
            <option value=".ind.in" >ind.in</option>
            <option value=".net.in" >.net.in</option>
            <option value=".org.in" >.org.in</option>
            <option value=".tv" >.tv</option>
		</select>
 
        <input type="submit" name="search" value="Search"/>
    
</form>

	<article>
    <div style="margin-left:auto; margin-right:auto;" > <h4> Domains starting from </h4> </div>
<div class="price" style="margin-left:auto; margin-right:auto;" ><strong>&#36;</strong><span>9</span><sup>.99</sup><em>Annually</em></div>
       
</article>

	</section>

    			</ul>
				
				<?php else: ?>
                
                <ul id="domains"  >
    				
                    <section id="searchbar">
<form class="form-wrapper cf" method="post" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'domaincheck')); ?>">
	<input type="text" placeholder="Search domain name .." name="domain" required autofocus>
    	<select name="extension">
            <option value=".com">.com</option>
            <option value=".info" >.info</option>
            <option value=".net" >.net</option> 
            <option value=".me" >.me</option>
            <option value=".org" >.org</option>
            <option value=".biz" >.biz</option> 
            <option value=".com.co" >.com.co</option>
            <option value=".net.co" >.net.co</option>
            <option value=".nom.co" >.nom.co</option>
            <option value=".mobi" >.mobi</option>
            <option value=".mx" >.mx</option>
            <option value=".com.es" >.com.es</option>
            <option value=".ws" >.ws</option>
            <option value=".us" >.us</option>
            <option value=".nom.es" >.nom.es</option>
            <option value=".es" >.es</option>
            <option value=".org.es" >.org.es</option>
            <option value=".nl" >.nl</option>
            <option value=".in" >.in</option>
            <option value=".com.mx" >.com.mx</option>
            <option value=".bz" >.bz</option>
            <option value=".com.bz" >.com.bz</option>
            <option value=".co.in" >.co.in</option>
            <option value=".firm.in" >.firm.in</option>
            <option value=".gen.in" >.gen.in</option>
            <option value=".ind.in" >ind.in</option>
            <option value=".net.in" >.net.in</option>
            <option value=".org.in" >.org.in</option>
            <option value=".tv" >.tv</option>
		</select>
 
        <input type="submit" name="search" value="Search"/>
    
</form>

	<?php 
    $avilable = current($this->result);
	$domain = key($this->result);
    if($avilable !== '0') {
        $string = '<p>is avilable</p>';
    } else {
        $string = '<p>is taken</p>';
    }
?>
    
    
    <article>
    <?php if($avilable == '0'): ?>
    
    <div style="margin-left:auto; margin-right:auto;" > <h4><?php echo $domain; ?> </h4> </div>
		<div class="price" style="margin-left:auto; margin-right:auto; text-align:center"><?php echo $string; ?>
    </div>
       
       
       <?php elseif($avilable !== '0'): ?>
       
       <div style="margin-left:auto; margin-right:auto;" ><h4><?php echo $domain; ?></h4></div>
		<div class="price" color:#FFF; font-size:10px;"> <?php echo $string; ?> at <strong>&#36;</strong><span><?php if (isset($this->domains_prices[$domain])) {echo $this->domains_prices[$domain];}?></span><sup></sup><em>Annually</em>
   	 </div>
       
		<a style="margin-left:auto; margin-right:auto;" id="item_x" ref="" onclick="addtocart('<?php echo $domain;?>', 'x'); return false;" title="add to cart">Add to cart</a>
        <span id="status_x" class="cl-status">Added</span> 
        
   	   <?php endif; ?>  
    
    
	</article>

	</section>


<section class="encard">

<article>
<h2>Other Options That You Might be Interested In</h2>
	<?php $i = 0;?>
    <?php foreach ($this->suggested_result as $key => $value): ?>
        <div class="otheroptions">
            <?php echo $key; ?>
				<?php if ($value !== '0'):?>
					is <b>available</b><span> only <?php echo $this->domains_prices[$key]; ?> &nbsp; annually</span><a id="item_<?php echo $i?>" ref="" onclick="addtocart('<?php echo $key?>', '<?php echo $i?>'); return false;" title="Add to cart">Add to cart</a><span id="status_<?php echo $i ?>" class="cl-status">Added</span>
					<?php $i++ ?>
				<?php else: ?>
					is <b>taken </b>
				<?php endif; ?>
        </div>
    <?php endforeach; ?>
	
</article>

<article id="recent">
        <h2>Your Recent Searches</h2>
        <?php 
            if(isset($this->rs_search) && count($this->rs_search)) {
                echo '<ul>';
                    foreach ($this->rs_search as $value) {
                        printf('<li>%s</li>', $value);
                    }
                echo '</ul>';
            }
        ?>     
        
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'orderdomain'))?>" title="order domain"> Proceed </a>
        
</article>

</section>

    			</ul>
                
                <?php endif; ?>
                              
                <ul id="hosting" class="hide" >
                    
        		 </ul>

        		 <ul id="domainprices" class="hide" style="padding:15px;">

                    <div class="services_option2 vertical_tabs">
	<div id="tabs">
     <ul class="tab_select">
      <li><a href="#tab-1">General Domains</a></li>
      <li><a href="#tab-2">Internation Domains</a></li>

     </ul>
     <div id="tab-1" style="background-color:#FFF;">
      
      <p><table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th width="6%"></th> 
    				<th width="14%">1 Year</th> 
    				<th width="15%">2 Years</th> 
                    <th width="15%">3 Years</th> 
    				<th width="15%">5 Years</th>
				</tr> 
			</thead> 
			<tbody> 
				<tr> 
   					
    				<td>.COM</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    
				</tr> 
				<tr> 
   					
    				<td>.CO</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
				<tr> 
   					
    				<td>.INFO</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr> 
				<tr> 
   					
    				<td>.NET</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
				<tr> 
   					
    				<td>.ORG</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>  
                <tr> 
   					
    				<td>.COM</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    
				</tr> 
				<tr> 
   					
    				<td>.CO</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
				<tr> 
   					
    				<td>.INFO</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr> 
				<tr> 
   					
    				<td>.NET</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
				<tr> 
   					
    				<td>.ORG</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>  
			</tbody> 
			</table></p>
      
     </div>
     <div id="tab-2" style="background-color:#FFF;">
      
      <p><table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th width="6%"></th> 
    				<th width="14%">1 Year</th> 
    				<th width="15%">2 Years</th> 
                    <th width="15%">3 Years</th> 
    				<th width="15%">5 Years</th>
				</tr> 
			</thead> 
			<tbody> 
				<tr> 
   					
    				<td>.us</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    
				</tr> 
				<tr> 
   					
    				<td>.ca</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
				<tr> 
   					
    				<td>.mx</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr> 
				<tr> 
   					
    				<td>.com.mx</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
				<tr> 
   					
    				<td>.ag</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>  
                <tr> 
   					
    				<td>.net.ag</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
      
                <tr> 
   					
    				<td>.bz</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
                <tr> 
   					
    				<td>.com.bz</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
                <tr> 
   					
    				<td>.gs</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
                 <tr> 
   					
    				<td>.ms</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                     
				</tr>
			</tbody> 
			</table>
            
            </p>
      
     </div>
     
    </div>
  </div>
        		 </ul>	
        		 
    		 </div> 

		 </div>
    
    </section>
 
		</div> 
 
 
 <div class="wraper">
 &nbsp;<br/>
 </div> 
</div>
  
  
  

