

<!--=== Slider ===-->
<div class="slider-inner">
    <div id="da-slider" class="da-slider">
        <div class="da-slide  btn-u btn-u-red">
            <h2><i>Contemporary Ballet</i> <br /> <i>We're Alan and Kelsey</i> <br /> <i>The Artistic Directors</i></h2>
            <p><i> of Texture Contemporary Ballet! </i> <br /> <i>Hire us for a show in your town</i></p>
            <div class="da-img span6">
                <div class="span6">
                    <iframe src="http://player.vimeo.com/video/62767899" width="100%" height="320" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe> 
                </div>
            </div>
        </div>
        <div class="da-slide  btn-u btn-u-blue">
            <h2><i>Contemporary Ballet</i> <br /> <i>We're Alan and Kelsey</i> <br /> <i><a href="" class="btn-u hover-effect">Details</a></i></h2>
            <p> <i>The Artistic Directors</i> <br /> <i> of Texture Contemporary Ballet! </i> <br /> <i>Hire us for a show in your town</i> </p>
            <p></p>
            <div class="da-img span6">
                <div class="span6">
                    <iframe src="http://player.vimeo.com/video/62767899" width="100%" height="320" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe> 
                </div>
            </div>
        </div>
        <div class="da-slide  btn-u btn-u-green">
            <h2><i>Contemporary Ballet</i> <br /> <i>We're Alan and Kelsey</i> <br /> <i>The Artistic Directors</i></h2>
            <p><i> of Texture Contemporary Ballet! </i> <br /> <i>Hire us for a show in your town</i></p>
            <div class="da-img span6">
                <div class="span6">
                    <iframe src="http://player.vimeo.com/video/62767899" width="100%" height="320" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe> 
                </div>
            </div>
        </div>
        <nav class="da-arrows">
            <span class="da-arrows-prev"></span>
            <span class="da-arrows-next"></span>        
        </nav>
    </div> 
</div><!--/slider-->
<!--=== End Slider ===-->

<!-- Purchase Block -->
<div class="row-fluid purchase margin-bottom-30">
    <div class="container">
		<div class="span9">
            <span>Your 1 Stop for Professionals, Remote Hiring, Opportunities  </span>
            <p>Hire a professional, Hire a Team.... or invest in the products of tomarrow. On the Other you have alots of opportunities </p>
        </div>
        <a href="" class="btn-buy hover-effect">Get Started Now</a>
    </div>
</div> 
<!-- End Purchase Block -->

<!--=== Content Part ===-->
<div class="container">		
    <!-- Service Blocks -->
    <div class="row-fluid servive-block ">
        <div class="span4">
            <h4>Looking for Jobs to your requirements?</h4>
            <p><a href="/"><img src="/assets/img/find.png" alt="Hire Remote"/></a></p>
             
        </div>
        <div class="span4">
            <h4>Searching for talented skillful workers?</h4>
            <p><a href="/"><img src="/assets/img/hunt.png" alt="Hire Remote"/></a></i></p>
             
        </div>
        <div class="span4">
            <h4>Hovering around to find great Projects?</h4>
            <p><a href="/"><img src="/assets/img/discover.png" alt="Hire Remote"/></a></p>
             
        </div>
    </div><!--/row-fluid-->
    <!-- //End Service Blokcs -->
    
    
    
    <div class="container">		    
	<div class="row-fluid">
    <div class="span12">
        
            <div class="wrap-title clearfix">
                    <h2 class="title-mark rs"><span class="fc-green"> Latest : Skills Posted </span></h2>
                    <a href="<?php echo $this->url(array('module' => 'default','controller' => 'hunt','action' => 'index'));?>" class="count-project be-fc-orange">See all <span class="fw-b">&nbsp;</span>Skillfull People</a>
            </div>
            
            <div id="home_preview" >
            
            <div class="home_preview">
                <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="200" height="110" poster="videos/poster.png"
                 data-setup="{}">
                 <source src="videos/dance.mp4" type='video/mp4'>
                 <source  type='video/webm'>
                </video>
 				<div class="home_info agent_info">
                <h4>Funny Dancer</h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Avilable after August 2013</a> 
            	</div>
            </div> 
            
            <div class="home_preview">
                <iframe src="http://player.vimeo.com/video/62767899" width="200" height="110" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
 				<div class="home_info agent_info">
                <h4>Classical DANCER </h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Avilable after August 2013</a> 
            	</div>
            </div>
            
            
            <div class="home_preview">
                <iframe width="200" height="110" src="//www.youtube.com/embed/IuTyh7kZV8g" frameborder="0" allowfullscreen></iframe>
 				<div class="home_info agent_info">
                <h4>I am Gardener</h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Busy from May to August 2013</a> 
            	</div>
            </div>
            
            
            <div class="home_preview">
                <iframe width="200" height="110" src="//www.youtube.com/embed/IuTyh7kZV8g" frameborder="0" allowfullscreen></iframe>
 				<div class="home_info agent_info">
                <h4>I am Gardener</h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Busy from May to August 2013</a> 
            	</div>
            </div>
            
            
            <div class="home_preview">
                <iframe src="http://player.vimeo.com/video/62767899" width="200" height="110" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
 				<div class="home_info agent_info">
                <h4>Classical DANCER </h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Avilable after August 2013</a> 
            	</div>
            </div>
            
   
                         
            </div>
    	</div>        
     </div>
     </div>    
     
     
     <div class="container">		    
	 	<div class="row-fluid">
     		<div class="span12">
        
            <div class="wrap-title clearfix">
                    <h2 class="title-mark rs"><span class="fc-blue"> Latest <span class="fc-blue"> Jobs posted</span></h2>
                    <a href="<?php echo $this->url(array('module' => 'default','controller' => 'find','action' => 'index'));?>" class="count-project be-fc-orange">See all <span class="fw-b">&nbsp;</span>Jobs posted</a>
            </div>
        	
            <div id="home_preview">

            <div class="home_preview pledge-detail">
            <img src="/images/clients/winwinhost.png" alt="WinWinHost Inc" />
            <div class="home_info">
            <h4>Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</h4>
            <ul>
            <li>Hourly</li>
            <li>5 people applied</li>
            <li>Interviewing 2 </li>
            <li>post 3 hours ago</li>
            </ul>
            </div>
            <div class="home_footer">
            <a class="sale" href="listing.html">Apply Now</a>
            <span class="home_cost">$20/hour</span>
            </div>		            
            </div> 
            
            <div class="home_preview pledge-detail">
            <img src="/images/clients/winwinhost.png" alt="WinWinHost Inc" />
            <div class="home_info">
            <h4>Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</h4>
            <ul>
            <li>Hourly</li>
            <li>5 people applied</li>
            <li>Interviewing 2 </li>
            <li>post 3 hours ago</li>
            </ul>
            </div>
            <div class="home_footer">
            <a class="sale" href="listing.html">Apply Now</a>
            <span class="home_cost">$20/hour</span>
            </div>		            
            </div>
            
            
            <div class="home_preview pledge-detail">
            <img src="/images/clients/lenevo.png" alt="WinWinHost Inc" />
            <div class="home_info">
            <h4>Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</h4>
            <ul>
            <li>Hourly</li>
            <li>5 people applied</li>
            <li>Interviewing 2 </li>
            <li>post 3 hours ago</li>
            </ul>
            </div>
            <div class="home_footer">
            <a class="sale" href="listing.html">Apply Now</a>
            <span class="home_cost">$20/hour</span>
            </div>		            
            </div> 
            
            
            <div class="home_preview pledge-detail">
            <img src="/images/clients/the-weather-channel.png" alt="WinWinHost Inc" />
            <div class="home_info">
            <h4>Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</h4>
            <ul>
            <li>Hourly</li>
            <li>5 people applied</li>
            <li>Interviewing 2 </li>
            <li>post 3 hours ago</li>
            </ul>
            </div>
            <div class="home_footer">
            <a class="sale" href="listing.html">Apply Now</a>
            <span class="home_cost">$20/hour</span>
            </div>		            
            </div> 
            
            
            <div class="home_preview pledge-detail">
            <img src="/images/clients/microsoft.png" alt="WinWinHost Inc" />
            <div class="home_info">
            <h4>Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</h4>
            <ul>
            <li>Hourly</li>
            <li>5 people applied</li>
            <li>Interviewing 2 </li>
            <li>post 3 hours ago</li>
            </ul>
            </div>
            <div class="home_footer">
            <a class="sale" href="listing.html">Apply Now</a>
            <span class="home_cost">$20/hour</span>
            </div>		            
            </div> 
            
          </div>
    	</div>        
       </div>
     </div>
     
     
     <!-- <div class="home-popular-project">
        <div class="container_12">
            <div class="grid_12 wrap-title">
                <div class="grid_12 wrap-title">
                <h2 class="common-title">Latest Purposed Projects </h2>
                <a class="be-fc-orange" href="<?php echo $this->url(array('module' => 'default','controller' => 'discover','action' => 'index'));?>">View all</a>
            </div>
            </div>
 			<div class="clear"></div>
            <div class="lst-popular-project clearfix">
                <div class="grid_3">
                    <div class="project-short sml-thumb">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/ex/th-292x204-1.jpg" alt="$TITLE">
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="project.html">Project title</a></h3>
                                    <p class="rs tiny-desc">by <a href="profile.html" class="fw-b fc-gray be-fc-orange">John Doe</a></p>
                                    <p class="rs title-description">
                                    <div class="project-runtime">
                                        <div class="box-gray">
                                            <div class="project-date clearfix">
                                                <i class="icon iCalendar"></i>
                                                <span class="val"><span class="fw-b">Launched: </span>Apr 8, 2013</span>
                                            </div>
                                            <div class="project-date clearfix">
                                                <i class="icon iClock"></i>
                                                <span class="val"><span class="fw-b">Funding ends: </span>Apr 8, 2013</span>
                                            </div>
                                            <a class="btn big btn-red" href="#">Buck This Project</a>
                                            <p class="rs description">This project will only be funded if at least $15,000 is pledged by Wednesday May 8, 2:05pm EDT.</p>
                                        </div> 
                                    </div>
                                    </p>
                                    <p class="rs project-location">
                                        <i class="icon iLocation"></i>
                                        New York, NY
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="bottom-project-info clearfix">
                            <div class="line-progress">
                                <div class="bg-progress">
                                    <span  style="width: 50%"></span>
                                </div>
                            </div>
                            <div class="group-fee clearfix">
                                <div class="fee-item">
                                    <p class="rs lbl">Funded</p>
                                    <span class="val">50%</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Pledged</p>
                                    <span class="val">$38,000</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Days Left</p>
                                    <span class="val">25</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                
                <div class="grid_3">
                    <div class="project-short sml-thumb">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/ex/th-192x135-1.jpg" alt="$TITLE">
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="project.html">Project title</a></h3>
                                    <p class="rs tiny-desc"> by <a href="profile.html" class="fw-b fc-gray be-fc-orange">John Doe</a></p>
                                    <p class="rs title-description">
                                    <div class="project-runtime">
                                        <div class="box-gray">
                                            <div class="project-date clearfix">
                                                <i class="icon iCalendar"></i>
                                                <span class="val"><span class="fw-b"> Launched: </span>Apr 8, 2013</span>
                                            </div>
                                            <div class="project-date clearfix">
                                                <i class="icon iClock"></i>
                                                <span class="val"><span class="fw-b"> Funding ends: </span>Apr 8, 2013</span>
                                            </div>
                                            <a class="btn big btn-red" href="#">Buck This Project</a>
                                            <p class="rs description">This project will only be funded if at least $15,000 is pledged by Wednesday May 8, 2:05pm EDT.</p>
                                        </div>
                                    </div>
                                    </p>
                                    <p class="rs project-location">
                                        <i class="icon iLocation"></i>
                                        New York, NY
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="bottom-project-info clearfix">
                        
                            <div class="line-progress">
                                <div class="bg-progress">
                                    <span class="success" style="width: 98%"></span>
                                </div>
                            </div>
                            <div class="group-fee clearfix">
                                <div class="fee-item">
                                    <p class="rs lbl">Funded</p>
                                    <span class="val">98%</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Pledged</p>
                                    <span class="val">$25,000</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Days Left</p>
                                    <span class="val">18</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
                <div class="clear clear-2col"></div>
                <div class="grid_3">
                    <div class="project-short sml-thumb">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/ex/th-192x135-2.jpg" alt="$TITLE">
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="project.html">Project title</a></h3>
                                    <p class="rs tiny-desc">by <a href="profile.html" class="fw-b fc-gray be-fc-orange">John Doe</a></p>
                                    <p class="rs title-description"> 
                                    <div class="project-runtime">
                                        <div class="box-gray">
                                            <div class="project-date clearfix">
                                                <i class="icon iCalendar"></i>
                                                <span class="val"><span class="fw-b">Launched: </span>Apr 8, 2013</span>
                                            </div>
                                            <div class="project-date clearfix">
                                                <i class="icon iClock"></i>
                                                <span class="val"><span class="fw-b">Funding ends: </span>Apr 8, 2013</span>
                                            </div>
                                            <a class="btn big btn-red" href="#">Buck This Project</a>
                                            <p class="rs description">This project will only be funded if at least $15,000 is pledged by Wednesday May 8, 2:05pm EDT.</p>
                                        </div>
                                    </div>
                                    </p>
                                    <p class="rs project-location">
                                        <i class="icon iLocation"></i>
                                        New York, NY
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="bottom-project-info clearfix">
                            <div class="line-progress">
                                <div class="bg-progress">
                                    <span  style="width: 21%"></span>
                                </div>
                            </div>
                            <div class="group-fee clearfix">
                                <div class="fee-item">
                                    <p class="rs lbl">Funded</p>
                                    <span class="val">21%</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Pledged</p>
                                    <span class="val">$850K</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Days Left</p>
                                    <span class="val">2</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
                <div class="grid_3">
                    <div class="project-short sml-thumb">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/ex/th-192x135-3.jpg" alt="$TITLE">
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="project.html">Project title</a></h3>
                                    <p class="rs tiny-desc">by <a href="profile.html" class="fw-b fc-gray be-fc-orange">John Doe</a></p>
                                    <p class="rs title-description">
                                    <div class="project-runtime">
                                        <div class="box-gray">
                                            <div class="project-date clearfix">
                                                <i class="icon iCalendar"></i>
                                                <span class="val"><span class="fw-b">Launched: </span>Apr 8, 2013</span>
                                            </div>
                                            <div class="project-date clearfix">
                                                <i class="icon iClock"></i>
                                                <span class="val"><span class="fw-b">Funding ends: </span>Apr 8, 2013</span>
                                            </div>
                                            <a class="btn big btn-red" href="#">Buck This Project</a>
                                            <p class="rs description">This project will only be funded if at least $15,000 is pledged by Wednesday May 8, 2:05pm EDT.</p>
                                        </div>
                                    </div>
                                    </p>
                                    <p class="rs project-location">
                                        <i class="icon iLocation"></i>
                                        New York, NY
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="bottom-project-info clearfix">
                            <div class="line-progress">
                                <div class="bg-progress">
                                    <span  style="width: 50%"></span>
                                </div>
                            </div>
                            <div class="group-fee clearfix">
                                <div class="fee-item">
                                    <p class="rs lbl">Funded</p>
                                    <span class="val">50%</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Pledged</p>
                                    <span class="val">$138,662</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Days Left</p>
                                    <span class="val">44</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </div> -->
    


    <!-- Our Clients -->
    <div id="clients-flexslider" class="flexslider home clients">
        <div class="headline"><h3>Who Use HireRemote</h3></div>    
        <ul class="slides">
            <li>
                <a href="#">
                    <img src="/assets/img/clients/hp_grey.png" alt="" /> 
                    <img src="/assets/img/clients/hp.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/igneus_grey.png" alt="" /> 
                    <img src="/assets/img/clients/igneus.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/vadafone_grey.png" alt="" /> 
                    <img src="/assets/img/clients/vadafone.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/walmart_grey.png" alt="" /> 
                    <img src="/assets/img/clients/walmart.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="/assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="/assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/aztec_grey.png" alt="" /> 
                    <img src="/assets/img/clients/aztec.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="/assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/cisco_grey.png" alt="" /> 
                    <img src="/assets/img/clients/cisco.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="/assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/cocacola_grey.png" alt="" /> 
                    <img src="/assets/img/clients/cocacola.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="/assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="/assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="/assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="/assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="/assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="/assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="/assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
        </ul>
    </div><!--/flexslider-->
    <!-- //End Our Clients -->
</div><!--/container-->		
<!-- End Content Part -->


<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initSliders();
        App.initBxSlider1();
        Index.initParallaxSlider();
    });
</script>

