
<head>
	<meta charset="utf-8"/>
	<title>Dashboard I Admin Panel</title>
	
	<link rel="stylesheet" href="css/layout.css" type="text/css" media="screen" />
    <style>
		#domainlist {
			height: 80%;
			margin-top: 30px;
			margin-left: 100px;
		}
	</style>	
    
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<!--
	<script src="js/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="js/hideshow.js" type="text/javascript"></script>
	<script src="js/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="js/jquery.equalHeight.js"></script>
    <script type="text/javascript" src="js/organictabs.jquery.js"></script>
	-->
	<script type="text/javascript" language="javascript">
	$(document).ready(function() 
    	{ 
      	  $(".tablesorter").tablesorter(); 
   	 } 
	);
	$(document).ready(function() {

	//When page loads...
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content

	//On Click Event
	$("ul.tabs li").click(function() {

		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content

		var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active ID content
		return false;
	});

});
    </script>
    <script type="text/javascript" language="javascript">
    $(function(){
        $('.column').equalHeight();
    });
</script>

<script>
        $(function() {
    
            $("#first").organicTabs();
            
            $("#second").organicTabs({
                "speed": 150
            });
    
        });
    </script>
<script type="text/javascript" language="javascript">
	addtocart = function(domain_name, id) {
		var url = "<?php echo $this->url(array('controller' => 'wwd', 'action' => 'orderdomain'));?>";
		$.ajax({	
			type: 'POST',
			url: url,
			data: {domain: domain_name}
		}).done(function() { 
			$('#item_' + id).hide();
			$('#status_' + id).show();
		});	
		return false;
	}
</script>	 
	
</head>

<div class="content_block">
	<section id="orderdomain">
	<?php if ($this->error['code'] === 0): ?>
		<h3>SUCCESS.</h3>
		<h3> Domain list </h3>
		<?php if (!empty($this->domainList)): ?>
		<ul>
			<?php foreach ($this->domainList as $domain): ?>
				<li><input type="checkbox" checked="checked" name="domains[]" value="<?php echo $domain ?>"><?php echo $domain?></li>
			<?php endforeach;?> 
		</ul>		
		<?php endif;?>
	<?php elseif ($this->error['code'] === 1): ?>
		<h3><?php echo $this->error['msg'];?></h3>
		<h4> ALL SELECTED DOMAINS</h4>
		<form method="POST" action="<?php echo $this->url(array('action' => 'wwd', 'action' => 'orderdomain'))?>">
			<div id="domainlist">	
				<ul>
					<?php if (!empty($this->domainList)): ?>
						<?php foreach ($this->domainList as $domain): ?>
							<li><input type="checkbox" checked="checked" name="domains[]" value="<?php echo $domain ?>"><?php echo $domain?></li>
						<?php endforeach;?> 
					<?php endif;?>
				</ul>
			</div>	
		<input type="submit" name="proccess" />	
		</form>
		<?php else: ?>
			<form method="POST" action="<?php echo $this->url(array('action' => 'wwd', 'action' => 'orderdomain'))?>">
				<div id="domainlist">	
					<ul>
						<?php if (!empty($this->domainList)): ?>
							<?php foreach ($this->domainList as $domain): ?>
								<li><input type="checkbox" checked="checked" name="domains[]" value="<?php echo $domain ?>"><?php echo $domain?></li>
							<?php endforeach;?> 
						<?php endif;?>
					</ul>
				</div>	
			<input type="submit" name="proccess" />	
			</form>
		<?php endif;?>
	</section>
</div>	

