<head>

	<!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Le styles -->
    <!-- Use new way for google web fonts 
    http://www.smashingmagazine.com/2012/07/11/avoiding-faux-weights-styles-google-web-fonts -->
    <!-- Headings -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css' />  -->
    <!-- Text -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css' /> --> 
    <!--[if lt IE 9]>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:700" rel="stylesheet" type="text/css" />
    <!-- THIS IS DOWNLOADED FROM WWW.SXRIPTGATES.COM - SO THIS IS YOUR NEW SITE FOR DOWNLOAD SCRIPT ;) -->
    <![endif]-->

    <link href="http://new.winwinhost.com/wwwroot/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/bootstrap/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/supr-theme/jquery.ui.supr.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Plugin stylesheets -->
    <link href="http://new.winwinhost.com/wwwroot/plugins/qtip/jquery.qtip.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/jpages/jPages.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/prettify/prettify.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/inputlimiter/jquery.inputlimiter.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/ibutton/jquery.ibutton.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/uniform/uniform.default.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/color-picker/color-picker.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/select/select2.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/validate/validate.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/pnotify/jquery.pnotify.default.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/pretty-photo/prettyPhoto.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/smartWizzard/smart_wizard.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/dataTables/jquery.dataTables.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/elfinder/elfinder.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/plupload/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" rel="stylesheet" />

    <!-- Main stylesheets -->
    <link href="http://new.winwinhost.com/wwwroot/css/main.css" rel="stylesheet" type="text/css" /> 

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/apple-touch-icon-144-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/apple-touch-icon-114-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/apple-touch-icon-72-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-57-precomposed.png" />
    
    <!-- Le javascript
    ================================================== -->

     <!-- Le javascript
    ================================================== -->
  
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/bootstrap/bootstrap.js"></script>  
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/jquery.mousewheel.js"></script>

    <!-- Load plugins -->
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/qtip/jquery.qtip.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.grow.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.pie.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.resize.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.tooltip_0.4.4.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.orderBars.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/knob/jquery.knob.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/fullcalendar/fullcalendar.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/prettify/prettify.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/watermark/jquery.watermark.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/elastic/jquery.elastic.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/inputlimiter/jquery.inputlimiter.1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/maskedinput/jquery.maskedinput-1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/ibutton/jquery.ibutton.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/uniform/jquery.uniform.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/stepper/ui.stepper.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/color-picker/colorpicker.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/timeentry/jquery.timeentry.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/select/select2.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/dualselect/jquery.dualListBox-1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/tiny_mce/jquery.tinymce.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/validate/jquery.validate.min.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/animated-progress-bar/jquery.progressbar.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/pnotify/jquery.pnotify.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/lazy-load/jquery.lazyload.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/jpages/jPages.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/pretty-photo/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/smartWizzard/jquery.smartWizard-2.0.min.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/touch-punch/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/ios-fix/ios-orientationchange-fix.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/dataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/elfinder/elfinder.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/plupload.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/plupload.html4.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/responsive-tables/responsive-tables.js"></script>

    <!-- Init plugins -->
    <script type="text/javascript" src="/statistic.js"></script><!-- Control graphs ( chart, pies and etc) -->

    <!-- Important Place before main.js  -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/main.js"></script>
   
    <script type="text/javascript">
        //adding load class to body and hide page
        document.documentElement.className += 'loadstate';
    </script>
    
    <style>
	
		#domainlist {
			height: 80%;
			margin-top: 30px;
			margin-left: 100px;
		}

		.cl-price-hidden {
			display: none;
		}
		.cl-price-show {
			
		}
		
	</style>	
    
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<!--
	<script src="js/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="js/hideshow.js" type="text/javascript"></script>
	<script src="js/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="js/jquery.equalHeight.js"></script>
    <script type="text/javascript" src="js/organictabs.jquery.js"></script>
	-->
	<script type="text/javascript" language="javascript">
	$(document).ready(function() 
    	{ 
      	  $(".tablesorter").tablesorter(); 
   	 } 
	);
	$(document).ready(function() {

	//When page loads...
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content

	//On Click Event
	$("ul.tabs li").click(function() {

		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content

		var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active ID content
		return false;
	});

});
    </script>
    <script type="text/javascript" language="javascript">
    $(function(){
        $('.column').equalHeight();
    });
</script>

<script>
        $(function() {
    
            $("#first").organicTabs();
            
            $("#second").organicTabs({
                "speed": 150
            });
    
        });
    </script>
<script type="text/javascript" language="javascript">
	addtocart = function(domain_name, id) {
		var url = "<?php echo $this->url(array('controller' => 'wwd', 'action' => 'orderdomain'));?>";
		$.ajax({	
			type: 'POST',
			url: url,
			data: {domain: domain_name}
		}).done(function() { 
			$('#item_' + id).hide();
			$('#status_' + id).show();
		});	
		return false;
	}
</script>	 
	
</head>


<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>Your Domain Order <span>Edit , and place your order here</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
              
</div>


<div class="wraper">                



					<div class="row-fluid">

                                                <div class="span12">
                            
                                                    <div class="box gradient invoice">
                            
                                                        
                                                        <div class="content">
                                                            
                                                            
                                                            <div class="clearfix"></div>
                            
                                                            <table class="responsive table table-bordered">
                                                                <thead>
                                                                  <tr>
                                                                    <th>Domain Name</th>
                                                                    <th>Term(years)</th>
                                                                    <th>Unit cost</th>
                                                                    <th>Total</th>
                                                                  </tr>
                                                                </thead>
                                                                <tbody>
                                                            <?php $total_amount = 0; ?>    
															<?php if ($this->error['code'] === 0): ?>
                                                                <h3>SUCCESS.</h3>
																<h3> Domain list </h3>
																 
																<div id="domainlist">	
																	<ul>
																		<?php if (!empty($this->domainList)): ?>
																			<?php foreach ($this->domainList as $domain): ?>

																		<tr>        
																		<td><input type="checkbox" checked="checked"  value="<?php echo $domain ?>"><?php echo $domain?></td>
																		<td>1</td>
																		<td>$9.99</td>
																		<td>$9.99</td>
																		</tr>
																			<?php endforeach;?> 
																		<?php endif;?>
																	</ul>
																</div>	
																
																

                                                            <?php elseif ($this->error['code'] === 1): ?>
                                                                <h3><?php echo $this->error['msg'];?></h3>
                                                                <h4> ALL SELECTED DOMAINS</h4>
                                                                <form method="POST" action="<?php echo $this->url(array('action' => 'index', 'action' => 'orderdomain'))?>">
                                                                    <div id="domainlist">	
                                                                        <ul>
                                                                            <?php if (!empty($this->domainList)): ?>
                                                                                <?php foreach ($this->domainList as $domain): ?>
                                                                                
                                                                                <tr>
                                                                                <td><input type="checkbox" checked="checked" value="<?php echo $domain ?>"><?php echo $domain?></td>
                                                                                <td>1</td>
                                                                                <td>$9.99</td>
                                                                                <td>$9.99</td>
                                                                                </tr>
                                                                                    
                                                                                <?php endforeach;?> 
                                                                            <?php endif;?>
                                                                        </ul>
                                                                    </div>	
                                                                <input type="submit" name="proccess" />	
                                                                </form>
															<?php else: ?>
                                                                    <form method="POST" action="<?php echo $this->url(array('action' => 'index', 'action' => 'orderdomain'))?>">
																		<h3> Domain list </h3>
																		<script type="text/javascript" language="javascript">
																		js_calculate_total_cost = function(uniq) {
																			if ($('#domain_name_' + uniq).is(':checked')) {
																				var duration = $("#domain_duration_" + uniq).val();
																				var price = 0;
																				switch(duration) {
																					case '1':
																						price =  $("#domain_price_1_" + uniq).val();
																						break;
																					case '2': console.log('case2');
																						price =  $("#domain_price_2_" + uniq).val();
																						break;
																					case '3':
																						price =  $("#domain_price_3_" + uniq).val();
																						break;
																					case '5':
																						price =  $("#domain_price_5_" + uniq).val();
																						break;
																					case '10':
																						price =  $("#domain_price_10_" + uniq).val();
																						break;	
																						
																				}
																				
																				$('#total_price_' + uniq).html(price);
																			} else {
																				$('#total_price_' + uniq).html('');
																			}
																			js_get_total_amount();
																		}
																		
																		js_get_total_amount = function () {
																			var total_amount = 0;
																			$("input[name='domains[]']:checked:enabled").each(function() {
																				var index = $(this).attr('index');
																				var price = $('#total_price_' + index).html(); 
																				if (!isNaN(price)) {
																					total_amount += price;
																				}
																			});
												
																			$('#total_amount').html(parseFloat(total_amount).toFixed(2));
																		}
																		
																		</script>
												
																		<?php if (!empty($this->domainList)): ?>
																		<ul>
																			<?php foreach ($this->domainList as $index => $domain): ?>
																			<?php $total_amount += (!empty($this->domains_prices[$domain]['price_2years']) ? $this->domains_prices[$domain]['price_2years'] : 0); ?>
																			<tr>
																				<td><input type="checkbox" checked="checked" name="domains[]" value="<?php echo $domain ?>" id="domain_name_<?php echo $index; ?>" index="<?php echo $index; ?>" onchange="js_calculate_total_cost('<?php echo $index; ?>');" /><?php echo $domain?></td>
																			<td>
																				<select name="duration" id="domain_duration_<?php echo $index;?>" onchange="js_calculate_total_cost('<?php echo $index; ?>');">
																					<option value="1" />1
																					<option value="2" selected="selected" />2
																					<option value="3" />3
																					<option value="4" />5
																					<option value="10" />10
																				</select>
																				<input type="hidden" id="domain_price_1_<?php echo $index; ?>" value="<?php echo $this->domains_prices[$domain]['price']; ?>" />
																				<input type="hidden" id="domain_price_2_<?php echo $index; ?>" value="<?php echo $this->domains_prices[$domain]['price_2years']; ?>" />
																				<input type="hidden" id="domain_price_3_<?php echo $index; ?>" value="<?php echo $this->domains_prices[$domain]['price_3years']; ?>" />
																				<input type="hidden" id="domain_price_5_<?php echo $index; ?>" value="<?php echo $this->domains_prices[$domain]['price_5years']; ?>" />
																				<input type="hidden" id="domain_price_10_<?php echo $index; ?>" value="<?php echo $this->domains_prices[$domain]['price_10years']; ?>" />

																				
																			</td>
																			<td>
																				<span><?php echo $this->domains_prices[$domain]['price']; ?></span>
																				<span><?php echo $this->domains_prices[$domain]['price_2years']; ?></span>
																				<span><?php echo $this->domains_prices[$domain]['price_3years']; ?></span>
																				<span><?php echo $this->domains_prices[$domain]['price_5years']; ?></span>
																			</td>
																			<td><span id="total_price_<?php echo $index;?>"><?php echo $this->domains_prices[$domain]['price_2years']; ?></span></td>
																			</tr>

																			<?php endforeach;?> 
																		</ul>		
																		<?php endif;?>
																												

																		
																		
																		
																		
                                                                    </form>
                                                                <?php endif;?>
                                    
                                                                </tbody>
                                                            </table>
                            
                                                            <div class="clearfix"></div>
                                                            <br />
                                                            <div class="clearfix"></div>
                                                            <div class="total">
                                                                <h4>Total amount:<span class="red" id="total_amount"><?php echo $total_amount; ?></span></h4>
                                                            </div>
                            
                                                            <div class="clearfix"></div>
                            
                                                        </div>
                            
                                                    </div><!-- End .box -->
                            
                                                </div>
                            
                                            </div>

					
                  
                    <div class="row-fluid">
                    
                    <div class="span12">
                            <div class="box gradient">

                                <div class="title">

                                    <h4>
                                        <span>Your Order</span>
                                    </h4>

                                </div>
                                <div class="content noPad clearfix">
                                   <!-- Smart Wizard -->
                                    <div id="wizard" class="swMain">
                                        <ul>
                                            <li>
                                                <a href="#step-1">
                                                    <label class="stepNumber">1</label>
                                                    <span class="stepDesc">
                                                       Review your order 
                                                    </span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#step-2">
                                                    <label class="stepNumber">2</label>
                                                    <span class="stepDesc">
                                                       Payment 
                                                    </span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#step-3">
                                                    <label class="stepNumber">3</label>
                                                    <span class="stepDesc">
                                                        Next Steps
                                                    </span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#step-4">
                                                    <label class="stepNumber">4</label>
                                                    <span class="stepDesc">
                                                       Finish is here, congrats
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                        <div id="step-1">   
                                            <h3>Step 1 Content</h3>
                                            
                                            
                                           
                                        </div>
                                        
                                        <div id="step-2">
                                           <h3>Step 2 Content</h3>
                                            
                                            <p>Need to take users Login here</p>
                                            <p>if not member of winwinhost yet , need to register on it.</p>
                                        </div>    
       
                                        <div id="step-3">
                                            <h3>Step 3 Content</h3>
                                            
                                            <p>Payment Options are to here.</p>
                                            <p>We can Paypal untill we have </p>                          
                                        </div>
                                        <div id="step-4">
                                            <h3>Step 4 Content</h3>
                                            
                                            <p> We can use this to let user know that payment was successfull to move user to next page</p>                 
                                        </div>
                                    </div><!-- End SmartWizard Content --> 
                                       
                                </div>

                            </div><!-- End .box -->

                        </div>
                    
                    </div>

	
</div>	

</div>