
<div id="wrapper">
    <!--end: #header -->  
    
    <?php echo $this->partial('hunt_search.phtml'); ?>
    
    <div class="layout-2cols">
        
           
           <div class="home-feature-category">
        <div class="content grid_10 clearfix" >
        
            <div class="wrap-title clearfix">
                    <h2 class="title-mark rs"><span class="fc-green"> Latest : Skills Posted </span></h2>
                    <a href="#" class="count-project be-fc-orange">See all <span class="fw-b">&nbsp;</span>Skillfull People</a>
            </div>
        	
            <div id="home_preview">
            
            <div class="home_preview">
                <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="200" height="110" poster="videos/poster.png"
                 data-setup="{}">
                 <source src="videos/dance.mp4" type='video/mp4'>
                 <source  type='video/webm'>
                </video>
 				<div class="home_info agent_info">
                <h4>Funny Dancer</h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Avilable after August 2013</a> 
            	</div>
            </div> 
            
            <div class="home_preview">
                <iframe src="http://player.vimeo.com/video/62767899" width="200" height="110" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
 				<div class="home_info agent_info">
                <h4>Classical DANCER </h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Avilable after August 2013</a> 
            	</div>
            </div>
            
            
            <div class="home_preview">
                <iframe width="200" height="110" src="//www.youtube.com/embed/IuTyh7kZV8g" frameborder="0" allowfullscreen></iframe>
 				<div class="home_info agent_info">
                <h4>I am Gardener</h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Busy from May to August 2013</a> 
            	</div>
            </div>
            
            
            <div class="home_preview">
                <iframe src="http://player.vimeo.com/video/62767899" width="200" height="110" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
 				<div class="home_info agent_info">
                <h4>Classical DANCER </h4>
                <ul>
                <li>Adil Shakar</li>
                <li>Abbottabad,PK</li>
                <li>Independent</li>
                <li>19 Recommendations</li>
                </ul>
                </div>	
                <div class="home_footer">
                <a class="availabe" href="listing.html">Contact</a> <span class="home_cost"> $50<sup>/hour</sup></span>
            	</div>        
                <div class="home_footer">
                <a class="rent" href="listing.html">Avilable after August 2013</a> 
            	</div>
            </div>
            
   
                         
            </div>
    	</div>    
        
            
     </div>

        <div class="sidebar grid_3" >
            <div class="left-list-category">
                <h4 class="rs title-nav">Featured</h4>
                <ul class="rs nav nav-category">
                    <li>
                        <a href="#">
                            Staff Picks
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li class="active">
                        <a href="#">
                            Popular
                            <span class="count-val">(2)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Now Launched
                            <span class="count-val">(212)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Ending Soon
                            <span class="count-val">(35)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Small Project
                            <span class="count-val">(67)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Most Funded
                            <span class="count-val">(23)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Curated Pages
                            <span class="count-val">(52)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                </ul>
            </div><!--end: .left-list-category -->
            <div class="left-list-category">
                <h4 class="rs title-nav">Category</h4>
                <ul class="rs nav nav-category">
                    <li>
                        <a href="#">
                            Art
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li class="active">
                        <a href="#">
                            Comics
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Design
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Fashion
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Film
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Games
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                        <ul class="rs nav-sub-category">
                            <li>
                                <a href="#">
                                    Comedy
                                    <span class="count-val">(12)</span>
                                    <i class="dotSquare"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Animation
                                    <span class="count-val">(12)</span>
                                    <i class="dotSquare"></i>
                                </a>
                            </li>
                        </ul><!--end: .nav-sub-category-->
                    </li>
                    <li>
                        <a href="#">
                            Music
                            <span class="count-val">(12)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Photography
                            <span class="count-val">(35)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Publishing
                            <span class="count-val">(92)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Technology
                            <span class="count-val">(13)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Theater
                            <span class="count-val">(29)</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                </ul>
            </div>
            
            <div class="search_options">
            <form action="search-results.html" />
            <div class="search_results"><span>8</span> results from <span>19</span> total</div>
            <div><input placeholder="Job Title" type="text" /> <select class="property">
            <option value="" disabled="disabled" selected="selected" />Property Type<option />Appartment<option />House<option />Villa</select>
            <div class="separator"></div>
            <select><option value="" disabled="disabled" selected="selected" />Min. Price<option />$100<option />$400<option />$700</select>
            <select><option value="" disabled="disabled" selected="selected" />Max. Price<option />$1000<option />$3000<option />$5000</select>
            <div class="separator"></div>
            <div class="bedrooms">Bedrooms: <input type="text" class="min" value="1" disabled="disabled" /> - <input type="text" class="max" value="5" disabled="disabled" />
            <div class="scroller">
            <div class="scroller_path">
            <div class="scroller_body">
            <div class="scroller_start"></div>
            <div class="scroller_end"></div></div></div></div>
            </div><input type="submit" value="update filters" /></div></form></div>
            
            <!--end: .left-list-category -->
        </div><!--end: .sidebar -->
        <div class="clear"></div>
    </div>
   

</div>


</body>
</html>