<?php
$this->title = "Delete Hosting";
$this->headTitle($this->title);

?>
<p>

  Are you sure that you want to delete hosting
 '<?php echo $this->escape($this->hosting['homepage_hosting_type']); ?>'  
 '<?php echo $this->escape($this->hosting['starting_price_dollars']); ?>'
 '<?php echo $this->escape($this->hosting['starting_price_cents']); ?>'  ?
  
</p>
<form action="<?php echo $this->url(array('action'=>'deletehosting')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->hosting['hosting_id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>

</form>
