<?php
$this->title = "Delete Slider";
$this->headTitle($this->title);

?>
<p>

  Are you sure that you want to delete slider
 '<?php echo $this->escape($this->slider['homepage_slider_text1']); ?>'  
 '<?php echo $this->escape($this->slider['homepage_slider_text2']); ?>'
 '<?php echo $this->escape($this->slider['homepage_slider_text3']); ?>' 
 '<?php echo $this->escape($this->slider['homepage_slider_text4']); ?>' ?
  
</p>
<form action="<?php echo $this->url(array('action'=>'deleteslider')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->slider['slider_id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>

</form>
