<?php
$this->title = "Delete Homepageproject";
$this->headTitle($this->title);

?>
<p>

  Are you sure that you want to delete homepageproject
 '<?php echo $this->escape($this->homepageproject['project_title']); ?>'  
 '<?php echo $this->escape($this->homepageproject['project_summary']); ?>'
 '<?php echo $this->escape($this->homepageproject['project_link']); ?>'  ?
  
</p>
<form action="<?php echo $this->url(array('action'=>'deletehomepageproject')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->homepageproject['homepageproject_id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>

</form>
