<?php
$this->title = "Delete Homepageservice";
$this->headTitle($this->title);

?>
<p>

  Are you sure that you want to delete homepageservice
 '<?php echo $this->escape($this->homepageservice['services_title']); ?>'  
 '<?php echo $this->escape($this->homepageservice['services_title_tag']); ?>'  ?
  
</p>
<form action="<?php echo $this->url(array('action'=>'deletehomepageservice')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->homepageservice['services_id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>

</form>
