<head>

<script type="text/javascript" src="http://new.winwinhost.com/wwwroot/css/stapel.css"></script>
<script type="text/javascript" src="http://new.winwinhost.com/wwwroot/css/custom.css"></script>
<script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/modernizr.custom.63321.js"></script>
<script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/jquery.stapel.js"></script>

		<script type="text/javascript">	
			$(function() {

				var $grid = $( '#tp-grid' ),
					$name = $( '#name' ),
					$close = $( '#close' ),
					$loader = $( '<div class="loader"><i></i><i></i><i></i><i></i><i></i><i></i><span>Loading...</span></div>' ).insertBefore( $grid ),
					stapel = $grid.stapel( {
						onLoad : function() {
							$loader.remove();
						},
						onBeforeOpen : function( pileName ) {
							$name.html( pileName );
						},
						onAfterOpen : function( pileName ) {
							$close.show();
						}
					} );

				$close.on( 'click', function() {
					$close.hide();
					$name.empty();
					stapel.closePile();
				} );

			} );
		</script>
        
</head>s

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>What We can Do for you <strong> you </strong><span>Design , Develop ...</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#">Pages</a></li> --> 
    <li>Pricing</li>
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 
 <div class="wraper">    
 
 
  <!-- features_block -->
<div class="features2_block features3_block features6_block">
   <ul>
   
    <li class="design">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Web Hosting</h4>
     <p><span>Your Hosting Partner</span></p>
     <p>WinWinHost Provides hosting servies at right rates and all the features that should be there with respect to present technology around the web. You can choose from many packages that suits you best.</p>
    </li>
    
    <li class="flexible">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Domains</h4>
     <p><span>World Wide Domains</span></p>
     <p>Register you Brand Names with Us , Domain Names is the gateway to your business on the web. Register today with the lowest rates around and we will help you further you setup your site quickly.</p>
    </li>
    
     <li class="support">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Design</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Lid est laborum dolos rumes fustsirs sit untras. Et harums ser quidem sit rerums facilis est dolores uni nemis sad untras voluptas uners sits amets.  </p>
    </li>
    
    <li class="easy">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Web Apps</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>We are extremely proficient at setting up solutions for our clients. We offer Basic Web sites to Mobile Application Development, Cloud Computing solutions , and many other types of software development services.</p>
    </li>
    
    <li class="updates">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Native Apps</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>At WinWinHost we are now developing Mobile optimized websites and apps for both Android and IOS. Mobile industry is againing shares in the Tech World rapidly , make your Identity in the Mobile World with us.</p>
    </li>
    
    <li class="color">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>SEO</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Search Engine Optimization refers to optimize your site to be easily found by search engines and we have experts who can make your site on top of Google's results , giving your organic traffic so you dont have to spend anything monthly </p>
    </li>
    
    <li class="fonts">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Internet Marketing</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Let the experts get you the largest possible ROI. WinWinHost.com can conduct your Email Marketing Campaigns, manage your PPC campaigns, setup CPA affiliate systems, and even design print advertising.</p>
    </li>
    
    <li class="ultra">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Open Source</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>We are working to provide best Open Source programs to his customers and not only this but now we are offering some open source projects and we hope in future to increase their number and of course to add new features to the existing projects.</p>
    </li>

   </ul>
  </div>       

      
  
  
 </div>
 
 
 <div class="wraper">  
  
  

					<div class="topbar">
                    <h4>Work recent Design Work</h4>
						<span id="close" class="back">Close</span>
						<h4 id="name" style="float:left;"></h4>
					</div>
					
					<ul id="tp-grid" class="tp-grid">

						<!-- roject Name-->
						<li data-pile="Phone Tracker">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/1.jpg" />
							</a>
						</li>
						<li data-pile="Phone Tracker">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/1.jpg" />
							</a>
						</li>
						<li data-pile="Phone Tracker">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/1.jpg" />
							</a>
						</li>
                        <li data-pile="Phone Tracker">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/1.jpg" />
							</a>
						</li>
						<li data-pile="Phone Tracker">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/1.jpg" />
							</a>
						</li>
						<li data-pile="Phone Tracker">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/1.jpg" />
							</a>
						</li>

						
                        
                        
                        <!-- roject Name-->
						<li data-pile="Eonline">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/2.jpg" />
							</a>
						</li>
						<li data-pile="Eonline">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/2.jpg" />
							</a>
						</li>
						<li data-pile="Eonline">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/2.jpg" />
							</a>
						</li>
                        <li data-pile="Eonline">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/2.jpg" />
							</a>
						</li>
						<li data-pile="Eonline">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/2.jpg" />
							</a>
						</li>
						<li data-pile="Eonline">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/2.jpg" />
							</a>
						</li>
                        
                        
                        <!-- roject Name-->
						<li data-pile="disney">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/3.jpg" />
							</a>
						</li>
						<li data-pile="disney">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/3.jpg" />
							</a>
						</li>
						<li data-pile="disney">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/3.jpg" />
							</a>
						</li>
                        
                        <!-- roject Name-->
                        <li data-pile="rubicon">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/4.jpg" />
							</a>
						</li>
						<li data-pile="rubicon">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/4.jpg" />
							</a>
						</li>
						<li data-pile="rubicon">
							<a href="#">
								<span class="tp-info"><span>Front Page</span></span>
								<img src="http://new.winwinhost.com/wwwroot/images/thumbs/4.jpg" />
							</a>
						</li>
                        
                        

					</ul>

  
 </div>
 
 
 
</div>

