<head>

</head>

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>We develop native applications on the desktop and mobiles<span> Visitors won't stay on a website for long if it not good looking & hard to navigate</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->

 <div class="wraper">

<div class="intro_text">
   <div class="bwWrapper" style="border:0;"><img src="http://new.winwinhost.com/wwwroot/images/web-design/web-design.jpg" alt="" /></div>
   <div class="desc">
    <h4>We work with you to create a site that suits your brand</h4>
    <p>Designing for the web is more than making it look great. Design has to be engaging, accessible and drive users to a point of conversion and in practical terms it should adhere to brand guidelines & follow the rules of varying screen resolutions.In addition, and above all, it should be unique and creative.<p>
<br />
<p>We work with our planning, technical and SEO team to push the boundaries of current and future trends, and to inject creative, dynamic and innovative touches so that it's just right for your business.Our team of strategists, designers, researchers, user interface architects, HTML, CSS and JavaScript experts work in collaboration to build the site.</p>
</p>
   </div>
  </div>
  
  <div class="why_choose_explore">
   <h4>Why Choose WinWinHost?</h4>
  <!-- why choose -->
  <div class="why_choose">
   <ul>
    <li><h5>We're the web design experts</h5></li>
    <p>Our talented web design team has years of experience in delivering solutions uniquely tailored towards every type of business.Whatever you're expecting, expect more from us.</p>
    
    <li><h5>We understand your brand</h5></li>
    <p>Whether you're a vast corporation or a relative newcomer, preserving brand integrity online is essential.Trust the job to WinWinHost and we'll find the perfect blend of head-turning looks and unmistakable identity.</p>
    
    <li><h5>We don't waste anybody's time</h5></li>
    <P>Not yours and certainly not your customers'. Our web design team is dedicated to ensuring that your site works to maximum efficiency.That means easy and intuitive navigation, minimal repetition and clear calls to action.</P>

    <li><h5>We listen</h5></li>
    <p>Everybody needs different features and functionality. If you have your own ideas, we're happy to work from a web design brief.<p>

<p> Or, if you'd prefer a little guidance, talk to our web designers - we're always ready to help.</p>

<p>For further inspiration, take a look at our <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'making','action' => 'web-applications'));?>">web application development </a> and <a href="<?php echo $this->url(array('module' => '