<head>

<meta name="description" content="">

        
        <style>
		
		#obo_slider {
			height:305px;
		
		}
		
		.oneByOne1{	
	margin: 0;
	width: 100%;
	height:305px;   
	background: #fff;    
	position: relative;
	overflow: hidden;

} 



					 .oneByOne_item{
	position: absolute;
	width: 960px;
	height: 305px;
	overflow: hidden;
	left: 10px;
					}
					
					.arrowButton{    
						cursor: pointer;  
					}            
					.arrowButton .prevArrow{
						background: url(obo/prev.png) no-repeat; 
						width: 60px;
						height: 60px;      
						position: absolute;
						top: 127px;	 
						left: 50px;        
					} 
					.arrowButton .nextArrow{                 
						background: url(obo/next.png) no-repeat;
						width: 60px;
						height: 60px;
						position: absolute;
						top: 127px;
						right: 50px;
					}

		
		</style>
        
</head>


<div class="wrape homeone">
	 
</div>


<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>You need more than just a <strong> web hosting </strong><span>you needs a partner.</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 
 <div class="wraper">    
 
 <div id="obo_slider" >  				
		<div class="oneByOne_item">
			<img src="http://new.winwinhost.com/wwwroot/images/reseller-hosting/reseller-hosting.png" class="wp1_3 slide1_bot" alt="">		            
			<span class="txt1">with WinWinHost </span>			
			<span class="txt2 blue txt_left2">Web Hosting Fullfill </span>												
			<span class="txt2 ">Your Hosting Needs</span>			
            <span class="txt3">at right price and we promise ,there are no hidden charges </span>										
</div>
                                                                                        
		
		</div>

  <div class="pricing_option pricing_option2" s>
   <h4 class="bord">Plans and Prices</h4>
   
   <ul>
    <li>
     <h4>Starter Windows Reseller Account</h4>
     <div class="price"><strong>&#36;</strong><span>149</span><sup>.99</sup><em>annually</em></div>
     <p>Unlimited Direct Admin Control Panels</p>
     <p>10 GB Disk Space</p>
     <p>500 GB Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </li>
    <li>
    <h4>Starter Linux Reseller Account</h4>
     <div class="price"><strong>&#36;</strong><span>149</span><sup>.99</sup><em>annually</em></div>
     <p>Unlimited Direct Admin Control Panels</p>
     <p>10 GB Disk Space</p>
     <p>500 GB Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </li>
    <li class="active">
    <div class="active_bg">
     <h4>Advance Linux Reseller Account</h4>
     <div class="price"><strong>&#36;</strong><span>299</span><sup>.99</sup><em>annually</em></div>
     <p>Unlimited Direct Admin Control Panels</p>
     <p>25 GB Disk Space</p>
     <p>700 GB Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </div>
    </li>
    <li>
     <h4>Advance Windows Reseller Account</h4>
     <div class="price"><strong>&#36;</strong><span>299</span><sup>.99</sup><em>annually</em></div>
     <p>Unlimited Direct Admin Control Panels</p>
     <p>25 GB Disk Space</p>
     <p>700 GB Bandwidth</p>
     <p>Unlimited Domains </p>
     <p>24x7 Support</p>
     <p>99.9% Uptime Guarantee</p>
     <p>&nbsp;</p>
     <p><a class="btn_m" href="#">Sign Up</a></p>
    </li>
   </ul>
  </div>
  
 </div>
 
</div>

<div class="wraper">


  <div class="features_block">
   <ul>
    <li class="design">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>PLANNING & RESEARCH </span></h4>
     <p>Mood boards, competitor research</p>
    </li>
    <li class="flexible">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>INFORMATION ARCHITECTURE </span></h4>
     <p>Site layout sketches, ideas, content</p>
    </li>
    <li class="support">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>DESIGN </span></h4>
     <p>Graphic design, page mockups</p>
    </li>
    <li class="easy">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>CODING AND TESTING </span></h4>
     <p>CSS, XHTML, Javascript, Flash, Cross Browser Testing, User Testing </p>
    </li>
    <li class="seo">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>IMPLEMENTATION </span></h4>
     <p>Data loading, final testing, backups</p>
    </li>
   </ul>
  </div>
  
  <div class="features2_block services_option">
   <h4>Web Hosting Features</h4>
   <div id="h_tabs" class="c_after">
   <ul class="tab_select left_list">
    <li class="sitemanagement">
     <a class="tlink" href="#htab-1">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Site Management</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="emailfeatures">
     <a class="tlink" href="#htab-2">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Email Features</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="customersupport">
     <a class="tlink" href="#htab-3">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Customer Support</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="scriptsupport<">
     <a class="tlink" href="#htab-4">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Script Support</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="statistics">
     <a class="tlink" href="#htab-6">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Statistics</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>
    <li class="datacenter">
     <a class="tlink" href="#htab-7">&nbsp;</a>
     <a class="circle_link">&nbsp;</a>
     <h4>Data Center</h4>
     <p><span>Subhead Goes Here</span></p>
    </li>

    
    
   </ul>
   <div id="htab-1" class="right_desc">
    <p><em><strong>Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_8.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-2" class="right_desc">
    <p><em><strong>Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_9.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-3" class="right_desc">
    <p><em><strong>500+ Fonts Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_10.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-4" class="right_desc">
    <p><em><strong>Ultra Responsive Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_11.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-5" class="right_desc">
    <p><em><strong>Superb Support Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_12.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-6" class="right_desc">
    <p><em><strong>Easy To Customize Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_13.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   <div id="htab-7" class="right_desc">
    <p><em><strong>Choose Your Color Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_14.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>


    </ul>
   </div>
   <div id="htab-8" class="right_desc">
    <p><em><strong>Constant Updates Very Flexible Lid est laborum dolores rumes fugats untras. Etras sit harums sertes quidem sit sadips atemsi accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. sadips uns.</strong></em></p>
    <p>Ciatis unde omnis iste natus error sit voluptatese accusantium doloremque sitsers lauda ntium sit totam rem aperiam, eaque ipsa quae ab illo inventoreres veritatis etras quasi set architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volupt atemas voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni </p>
    <p class="bwWrapper"><img src="/images/services_process/services_15.png" width="202" height="120" alt="" /></p>
    <ul>
     <li>Cras rutrum leo at odio volutpat ids.</li>
     <li>Donec fermentum porttitor nuncs.</li>
     <li>Maecenas quis nisi in tortor luctus.</li>
     <li>Aenean faucibus sapien odio varius. </li>
    </ul>
   </div>
   </div>
  </div>
  
  
  
  <div class="features2_block features3_block features6_block">
   <ul>
   
    <li class="design">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Web Hosting</h4>
     <p><span>Your Hosting Partner</span></p>
     <p>WinWinHost Provides hosting servies at right rates and all the features that should be there with respect to present technology around the web. You can choose from many packages that suits you best.</p>
    </li>
    
    <li class="flexible">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Domains</h4>
     <p><span>World Wide Domains</span></p>
     <p>Register you Brand Names with Us , Domain Names is the gateway to your business on the web. Register today with the lowest rates around and we will help you further you setup your site quickly.</p>
    </li>
    
     <li class="support">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Design</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Lid est laborum dolos rumes fustsirs sit untras. Et harums ser quidem sit rerums facilis est dolores uni nemis sad untras voluptas uners sits amets.  </p>
    </li>
    
    <li class="easy">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Web Apps</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>We are extremely proficient at setting up solutions for our clients. We offer Basic Web sites to Mobile Application Development, Cloud Computing solutions , and many other types of software development services.</p>
    </li>
    
    <li class="updates">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Native Apps</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>At WinWinHost we are now developing Mobile optimized websites and apps for both Android and IOS. Mobile industry is againing shares in the Tech World rapidly , make your Identity in the Mobile World with us.</p>
    </li>
    
    <li class="color">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>SEO</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Search Engine Optimization refers to optimize your site to be easily found by search engines and we have experts who can make your site on top of Google's results , giving your organic traffic so you dont have to spend anything monthly </p>
    </li>
    
    <li class="fonts">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Internet Marketing</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>Let the experts get you the largest possible ROI. WinWinHost.com can conduct your Email Marketing Campaigns, manage your PPC campaigns, setup CPA affiliate systems, and even design print advertising.</p>
    </li>
    
    <li class="ultra">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4>Open Source</h4>
     <p><span>Subhead Goes HEre</span></p>
     <p>We are working to provide best Open Source programs to his customers and not only this but now we are offering some open source projects and we hope in future to increase their number and of course to add new features to the existing projects.</p>
    </li>

   </ul>
  </div>
  
  
  

<div class="services_option2 vertical_tabs">
   <h4>Features</h4>
	<div id="tabs">
     <ul class="tab_select">
      <li><a href="#tab-1">Site Management</a></li>
      <li><a href="#tab-2">Programming &Database</a></li>
      <li><a href="#tab-3">Email Features</a></li>
      <li><a href="#tab-4">Customer Support</a></li>
      <li><a href="#tab-5">Statistics</a></li>
      <li><a href="#tab-6">Install Quick Apps  </a></li>
     </ul>
     
     
     <div id="tab-1">
      <h3>Manage all things with ease </h3>
      <h5></h5>
    
      <ul>
       <li>Direct Admin Web Control Panel</li>
       <li>Unlimited FTP Accounts (create FTP accounts and set directory permissions for each account.  Anonymous FTP is also supported)</li>
       <li>Online File Manager (A user-friendly and fast alternative to FTP.  Includes every feature needed to build and maintain a web site)</li>
       <li>Subdomains (list, create, delete, and get statistics on subdomains)</li>
       <li>DNS Menu.(add and remove records, change MX settings, and anything else that goes with full DNS control) </li>
       <li>Password Protected Directories</li>
       <li>Site Backup (powerful tool,backup and restore only what they want to.  For example, account data but not web site files)</li>
       <li>High Performance Load Balanced Servers </li>

      </ul>
      <!-- <p><a class="learn_more btn_m" href="#">Learn More</a></p> -->
     </div>
     
     
     <div id="tab-2">
      <h3>No Matter what technology you used to make your apps , we host them all</h3>
      <h5></h5>
      <p></p>
      <ul>
      <li>PHP 5.2 & PHP 5.3	</li>	 
	  <li>CGI, Fast CGI</li>
      <li>Perl </li>
      <li>MySQL Databases with phpMyAdmin Access</li>
      <li>ASP 3.0 (Classic ASP)</li>
	  <li>ASP.NET (.NET 1.1)</li>
      <li>MS SQL Server</li>
      <li>FrontPage Extensions.</li>
      <li>SSH Access and Cron Job Scheduling</li>

      </ul>

     </div>
     

     <div id="tab-3">
      <h3>Make a Win with WinWinHost Super Email Services </h3>
      <h5></h5>
            <p>Create POP/IMAP accounts, catch-all e-mail addresses, forwarders, mailing lists, autoresponders, and webmail.  Filters allow users to block mail by domain, keyword, and size.  Adult Filter is also available.</p>
      <ul>
       <li>Unlimited Email Accounts</li>
       <li>Email Addresses at Your Domain (yourname@yourbusiness.com)</li>
       <li>WebMail (Checking Your Mail Online)</li>
       <li>Auto Responders</li>
       <li>Unlimited Mailing Lists</li>
       <li>Mail Spam Filters</li>
       <li>SMTP/POP3/IMAP</li>
       <li>Mail Forwards</li>
       </ul>
     </div>
     
     
     <div id="tab-4">
      <h3>Providing Unbeatable Support</h3>
      <h5></h5>

      <ul>
       <li>24/7 Technical Support ( Ticket Support System , Email , Live Chat , Phone )</li>
       <li>Online User Manuals</li> 
       <li>24/7 Server Monitoring</li>
       <li>99.9% Uptime Guarantee</li>
      </ul>
      
     </div>
     
     
     <div id="tab-5">
      <h3>Get idea about How your site is being used?</h3>
      <h5></h5>
      <p>Have available every possible statistic about their account.  More advanced options and Webalizer are also included. </p>
      <ul>
       <li>Visitor Statistics/Site Traffic Reporting</li>
       <li>Bandwidth Usage</li>
       <li>Error Logs</li>
       <li>Raw Access Logs</li>
      </ul>

     </div>
     
     
     
     <div id="tab-6">
      <h3>Dont bother about downloading and  than uploading commonly used Applications</h3>
      <h5></h5>
	  <ul>
      
      <li>Install SSL certificates</li>
      <li>View sever information, installed perl modules</li>
      <li>Set cron jobs, mime types, and apache handlers</li>
      <li>Enable site redirection and domain pointers</li>
      <li>WordPress Hosting - Host your WordPress sites with ease</li>
	  <li>Joomla Hosting & Drupal Hosting </li>
	  <li>Magento Hosting - Free E-commerce platform for your online store</li>	
       
      </ul>
     <!--  <p><a class="learn_more btn_m" href="#">Learn More</a></p> -->

     </div>
     
     
     
     
     
    </div>
  </div>
  

  </div>
