<head>

</head>

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2> We design engaging, accessible and search engine friendly web designs <span> Visitors won't stay on a website for long if it not good looking & hard to navigate</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->
 
 <div class="wraper">
 
<div class="intro_text">
   <div class="bwWrapper" style="border:0;"><img src="http://new.winwinhost.com/wwwroot/images/web-design/web-design-stack.jpg" alt="web design Stack" title="web design stack" /></div>
   <div class="desc">
    <h4>We work with you to create a site that suits your brand</h4>
    <p>Designing for the web is more than making it look great. Design has to be engaging, accessible and drive users to a point of conversion and in practical terms it should adhere to brand guidelines & follow the rules of varying screen resolutions.In addition, and above all, it should be unique and creative.<p>
<br />
<p>We work with our planning, technical and SEO team to push the boundaries of current and future trends, and to inject creative, dynamic and innovative touches so that it's just right for your business.Our team of strategists, designers, researchers, user interface architects, HTML, CSS and JavaScript experts work in collaboration to build the site.</p>
</p>
   </div>
  </div>
  
  <div class="why_choose_explore">
   <h4>Why Choose WinWinHost?</h4>
  <!-- why choose -->
  <div class="why_choose">
   <ul>
    <li><h5>We're the web design experts</h5></li>
    <p>Our talented web design team has years of experience in delivering solutions uniquely tailored towards every type of business.Whatever you're expecting, expect more from us.</p>
    
    <li><h5>We understand your brand</h5></li>
    <p>Whether you're a vast corporation or a relative newcomer, preserving brand integrity online is essential.Trust the job to WinWinHost and we'll find the perfect blend of head-turning looks and unmistakable identity.</p>
    
    <li><h5>We don't waste anybody's time</h5></li>
    <P>Not yours and certainly not your customers'. Our web design team is dedicated to ensuring that your site works to maximum efficiency.That means easy and intuitive navigation, minimal repetition and clear calls to action.</P>

    <li><h5>We listen</h5></li>
    <p>Everybody needs different features and functionality. If you have your own ideas, we're happy to work from a web design brief.<p>

<p> Or, if you'd prefer a little guidance, talk to our web designers - we're always ready to help.</p>

<p>For further inspiration, take a look at our <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'making','action' => 'web-applications'));?>">web application development </a> and <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'making','action' => 'native-applications'));?>">native application development </a>  solutions </p>

   </ul>
   </div>

  <!-- /why choose -->
   
  <!-- features_explore -->
  <div class="features_explore">
   <ul>
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-design/ux-design.jpg" width="94" height="65" alt="User Experience" /></a></div>
     <p><h5>User Experience</h5>We make web design with users in mind.To ensure a good return on investment it should be easy for visitors to do what they want – whether it's browsing through services , products, getting advice or donating money. </p>
    </li>
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-design/responsive-design.jpg" width="94" height="65" alt="responsive web design" /></a></div>
     <p><h5>Web Design For Any Device</h5>You can no longer design for a desktop screen with more and more people accessing the Web through their mobile devices. We have to design for four corners, no matter the size, no matter the device. </p>
    </li>
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-design/accessibility.jpg" width="94" height="65" alt="web site accessibility" /></a></div>
     <p><h5>Accessibility</h5>We really care about making websites and applications which are usable by every visitor. Why put up artificial barriers when, with a little planning up front, you can maximise your audience? </p>
    </li>
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-design/seo-friendly.jpg" width="94" height="65" alt="search engine friendly" /></a></div>
     <p><h5>Search Engine Friendly</h5>Our websites are built following accepted web standards and using semantic markup that means that they are highly discoverable and will not put up any barriers to search engines. </p>
    </li>
   </ul>
  </div>

  <!-- /features_explore -->
  
  </div>
  </div>
    
   <div class="wraper">  
  
<div class="features_block">

<h4>Our web design Process </h4>

   <ul>
    <li class="design">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>PLANNING & RESEARCH </span></h4>
     <p>Mood boards, competitor research</p>
    </li>
    <li class="flexible">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>INFORMATION ARCHITECTURE </span></h4>
     <p>Site layout sketches, ideas, content</p>
    </li>
    <li class="support">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>DESIGN </span></h4>
     <p>Graphic design, page mockups</p>
    </li>
    <li class="easy">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>CODING AND TESTING </span></h4>
     <p>CSS, HTML, Javascript, Cross Browser Testing, User Testing </p>
    </li>
    <li class="seo">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>IMPLEMENTATION </span></h4>
     <p>Data loading, final testing, backups</p>
    </li>
   </ul>
  </div>

  </div>
  
  <div class="wraper">
  
    <div class="send_quote send_quote_marg">
   <h4>Would you like us to send you a quote?</h4>
   <p>Click the button, fill out the form and we'll be right with you!<a class="btn_col" href="#">Get A Quote</a></p>
  </div>
  
 </div>
 
</div>