<head>
       
</head>

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>We make browser-based web applications <span> that are are evenly optimized for desktops, tablets and smartphones.</span></h2>
     
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>--> 
   </ul>
  </div>
 </div>
 <!-- /top_title -->

 <div class="wraper">
 
<div class="intro_text">
   <div class="bwWrapper" style="border:0;"><img src="http://new.winwinhost.com/wwwroot/images/web-applications/web-application-development-stack.jpg" title="Web application development technologies stack" alt="Web application development technologies stack" /></div>
   <div class="desc">
    <h4>What is web application?</h4>
    <div class="bwWrapper" style="border:none;"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-applications/web-application-icon.jpg" width="94" height="65" alt="web site accessibility" /></a></div>
    <p>A web application is an application that is accessed via web browser over the Internet or an intranet. In that sense a web application is like a website. But a web application is much more powerful as it is dynamic, typically allows users to login, view and manage content, etc. Examples of web applications include online banking systems, Google mail, Customer web portals, Google docs, etc.</p>
   	    <br />
        
        <h4>One App , Good for all Devices</h4>
        <div class="bwWrapper" style="border:none;"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-applications/responsive-design.jpg" width="94" height="65" alt="web site accessibility" /></a></div>
    <p>We have to design for four corners, no matter the size, no matter the device. So even people can access and use the app through their mobile devices as app made for their device.  </p>
   	    <br />
        
    <h4>Yes we make all sorts of web applications</h4>
    
   <p> We are experienced in developing advanced systems with complex business logic dealing with large amounts of data and transactions. We are able to supply you with an innovative, trustworthy web application to complement your business ideas.</p>

   </div>
  </div>
  
  <div class="why_choose_explore">
   <h4>Why Choose WinWinHost?</h4>
  <!-- why choose -->
  <div class="why_choose">
   <ul>
    <li><h5 style="text-transform:uppercase;">Staying agile</h5></li>
    <p>Our approach to web development is agile and iterative: we get going quickly, listen to what you say and develop a bespoke system accordingly. We don't believe in spending your money writing long-winded project specifications and stuffy documentation that no-one will read beyond the development of the project. We would rather use the time to get the first release live, and develop the system based on actual user feedback rather than guess work.</p>
    
    <li><h5 style="text-transform:uppercase;">Test driven development</h5></li>
    <p>We love test driven development because it encourages simple design and good quality maintainable code. Problems are caught earlier in the development thus reducing the amount of debugging required. New features can quickly be tested to detect conflicts with existing functionality. Test cases act as a living breathing specification that clearly define how the application should work.</p>
    
    <li><h5 style="text-transform:uppercase;">Content management</h5></li>
    <P>We also like to provide you with the tools to keep your website up-to-date without the need for our input. This maybe a custom Content Management System (CMS) designed to work exactly as you want it or it could be using a pre-built solution that can be easily plugged into. Ultimately, it's about delivering a solution at a level that you are comfortable with.</P>

<br />
<p>Above all, you can relax, knowing your project is in safe hands.</p>

   </ul>
   </div>

  <!-- /why choose -->
  
  <!-- features_explore -->
  <div class="features_explore">
   <ul>
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-applications/open-source-frame-works.jpg" width="94" height="65" alt="" /></a></div>
     <p><h5 style="text-transform:uppercase;">FRAMEWORKS & TECHNOLOGY USED</h5>We are passionate about web technologies and constantly keep an eye out for new technologies that make us more efficient. We use open source technologies such as PHP and MySQL & extensively use Zend Framework, jQuery & AJAX.</p>

    </li>
  
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-applications/web2.0.jpg" width="94" height="65" alt="responsive web design" /></a></div>
     <p><h5 style="text-transform:uppercase;">WEB 2.0 BASED DEVELOPMENT</h5>A Web 2.0 web app allows users to interact and collaborate with each other. Criteria is: Usable and rich interface with technologies like AJAX ,Let other systems integrate like Web Services, Tools to let users share thoughts and experiences.</p>
    </li>
    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-applications/html5.jpg" width="94" height="65" alt="web site accessibility" /></a></div>
     <p><h5 style="text-transform:uppercase;">HTML5 WEB DEVELOPMENT</h5>HTML5 is the next major revision of the HTML standard.It enables: Offline web applications,HTML5 video to avoid the need for plugins like Flash to play basic videos. Push technology to send updates from the server (Web sockets).
</p>
    </li>

    <li>
     <div class="bwWrapper"><a href="#"><img src="http://new.winwinhost.com/wwwroot/images/web-applications/open-source-custom-solutions.jpg" width="94" height="65" alt="web site accessibility" /></a></div>
     <p><h5 style="text-transform:uppercase;">Open source custom solutions</h5>We are here to serve you with the most comprehensive open source custom solutions. Our experience and expertise in this field guarantee you excellent quality customization , We specialize in Magento, WordPress etc.</p>

    </li>

   </ul>
  </div>

  <!-- /features_explore -->
  
  </div>
  </div>

   <div class="wraper">  
  
<div class="features_block">

<h4>Our web application development Process  </h4>
 
   <ul>
    <li class="strategy">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>STRATEGY </span></h4>
     <p>We work closely with you, offering expert advice throughout. It can be about the technical nuts and bolts or the best approach to branding and online marketing. All our know-how is available to you.</p>
    </li>
    <li class="appdesign">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>DESIGN </span></h4>
     <p>Once the project has been mapped out, we'll provide a working design   that will storyboard the operation of your new website. For further information, take a look at our  <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'making','action' => 'web-design'));?>"> web design approach </a>.</p>
    </li>
    <li class="development">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>DEVELOPMENT </span></h4>
     <p>We complete the majority of our projects using industry-leading, object-orientated PHP with MySQL, it's a common combination, offering greater flexibility and robustness and we offer the most suitable solution.</p>
    </li>
    <li class="testing">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>TESTING </span></h4>
     <p>We thoroughly test everything before it goes out, in the unlikely event that you still find the odd bug. We'll correct it.Test cases act as a living breathing specification that clearly define how the application should work.</p>
    </li>
    <li class="management">
     <a class="circle_link" href="#">&nbsp;</a>
     <h4><span>ONGOING MANGEMENT </span></h4>
     <p>We don't just deliver a project and leave you to it. We'll also provide regular support and maintenance. At WinWinHost, we believe in a lasting working relationship.</p>
    </li>
   </ul>
  </div>

  </div>

  <div class="wraper">
  
    <div class="send_quote send_quote_marg">
   <h4>Would you like us to send you a quote?</h4>
   <p>Click the button, fill out the form and we'll be right with you!<a class="btn_col" href="#">Get A Quote</a></p>
  </div>
  
 </div>
 
</div>