<head>

<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="http://new.winwinhost.com/wwwroot/css/style.css">
<link rel="stylesheet" href="http://new.winwinhost.com/wwwroot/css/responsive.css">
<link rel="stylesheet" href="http://new.winwinhost.com/wwwroot/css/prettyPhoto.css">
<link rel="stylesheet" href="http://new.winwinhost.com/wwwroot/css/flexslider.css">

<script src="http://new.winwinhost.com/wwwroot/scripts/jquery.min.js"></script>
<script src="http://new.winwinhost.com/wwwroot/scripts/jquery.bxSlider.min.js"></script>
<script src="http://new.winwinhost.com/wwwroot/scripts/jquery.faq.js"></script>
<script src="http://new.winwinhost.com/wwwroot/scripts/jquery.blackandwhite.min.js"></script>
<script src="http://new.winwinhost.com/wwwroot/scripts/js_func.js"></script>


<script>
$(function(){
	$('.clients_slider').bxSlider({
		auto: false,
		controls : false,
		mode: 'fade',
		pager: true
	});	
	$('.post_slider').bxSlider({
		auto: false,
		speed : 1000
	});
	$('.recent_slider').bxSlider({
		auto: false,
		displaySlideQty: 1,
		moveSlideQty: 1,
    	speed : 1000
	});
	$('#faq').dltoggle();
	$("#open").click(function(event){
      $('#faq').dltoggle_show();
      return false;
	});
	$("#close").click(function(event){
      $('#faq').dltoggle_hide();
      return false;
	});
    $('.bwWrapper').BlackAndWhite({
        hoverEffect : true,
        webworkerPath : false,
        responsive:true,
        invertHoverEffect:false
    });
})
</script>


</head>

<!-- pager_nav -->
   <div class="pager_nav">
   
   <?php if ($this->pageCount): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
 of <?php echo $this->totalItemCount; ?>
 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    First
  </a> |
<?php else: ?>
  <span class="disabled">First</span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a class="bx-prev" href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a class="bx-next" href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Next &gt;</span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    Last
  </a>
<?php else: ?>
  <span class="disabled">Last</span>
<?php endif; ?>
<!-- Go to page -->
<?php if ($this->pageCount): ?>
	<span>|&nbsp;Go to: </span><select id="paginationControl" size="1" style="width: 40px; height: 18px; padding: 0px 0px 0px 5px">
	<?php foreach ($this->pagesInRange as $page): ?>
	<?php $selected = ($page == $this->current) ? ' selected="selected"' : ''; ?>
	<option value="<?php
			echo $this->url(array('page' => $page));?>"<?php echo $selected ?>>
		<?php echo $page; ?>
	</option>
	<?php endforeach; ?>
	</select>
<?php endif; ?>
</div>
<?php endif; ?>
 
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.2/prototype.js">
</script>
<script type="text/javascript">
$('paginationControl').observe('change', function() {
    window.location = this.options[this.selectedIndex].value;
})
</script>

</div>