<head>

</head>


<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h1 class="page-title">Thank you for writing us, we will reply as soon as possible.</h1>

  </div>
 </div>
 <!-- /top_title -->
 <div class="wraper">
  <!-- contact_us -->
  <div class="contact_us">
   
   <h1>Your message has been received.</h1>
   <h1>Thank you for writing us, we will reply you as soon as possible.</h1>
   
   <br />
   <br />
   
   <h4>Ask us More </h4>
   <ul>          
    <li>Address:<br /><br />Phone:<br />Email:Fax:<br />Fax:</li>
    <li><strong>12830 Burbank Blvd<br />Valley Vlg, CA 91607<br />(800) 880-4295<br />support@winwinhost.com<br />-------------- </strong></li>
    <li>We always love to hear from you. If you have any question in mind , just ask us. Thank You </li>
   </ul> 
 
   
  

   	<?php echo $this->ContactForm; ?>

	<?php if(isset($this->message)): ?>
	<?php echo $this->message; ?>
  	<?php endif;?>
  
  	<br />
    <br>
  </div>
  <!-- /contact_us -->
  <!-- sidebar -->
  <div class="sidebar">
  
  <div class="fb-like-box" data-href="http://www.facebook.com/phonetrackerdotnet" data-width="200" data-height="300"  data-show-faces="true" data-border-color="white" data-stream="false" data-header="false"></div>
  
  
   <!-- most popular -->
   <div class="most_popular">
    <h4>Recent Posts from out Blog</h4>
    <ul>
    <?php
               $this->blog();
               ?>
                
     <?php
        foreach ($this->latestblg as $data) {
                    ?> 
                    <li>
      <a href="<?php
                echo $this->url(array('module' => 'default',
                    'controller' => 'blog',
                    'action' => 'detail',
                    'post_title' => $data['news_title'],
                ));  ?>">
                    <div class="bwWrapper"><img src="http://new.winwinhost.com/wwwroot/uploads/newsimages/<?php echo $data['image']; ?>" width="60" height="55" alt="" /></div>
      <div class="desc">
       <p><strong><?php echo $data['news_title']; ?></strong></p>
       <p> </p>
       <p><span> <a href="<?php
                echo $this->url(array('module' => 'default',
                    'controller' => 'blog',
                    'action' => 'detail',
                    'post_title' => $data['news_title'],
                ));  ?>"><?php echo $data['news_posted']; ?><a> </span></p>
      </div>
     </li>
     <?php } ?> 
     
    
    </ul>
   </div>


  </div>
  <!-- /sidebar -->
 </div>
</div>
