<!DOCTYPE html>
<!--[if IE 7]> <html lang="en" class="ie7"> <![endif]-->  
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->  
<head>
    <title>HireRemote</title>

    <!-- Meta -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- CSS Global Compulsory-->
    <link rel="stylesheet" href="/assets/plugins/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/assets/css/style.css" />
    <link rel="stylesheet" href="/assets/css/headers/header2.css" />
    <link rel="stylesheet" href="/assets/plugins/bootstrap/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="/assets/css/style_responsive.css" />
    <link rel="shortcut icon" href="/favicon.jpg" />        
    <!-- CSS Implementing Plugins -->    
    <link rel="stylesheet" href="/assets/plugins/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/assets/plugins/flexslider/flexslider.css" type="text/css" media="screen" />      
    <link rel="stylesheet" href="/assets/plugins/parallax-slider/css/parallax-slider.css" type="text/css" />
    <link rel="stylesheet" href="/assets/plugins/bxslider/jquery.bxslider.css" />
    <!-- CSS Theme -->    
    <link rel="stylesheet" href="/assets/css/themes/default.css" id="style_color" />
    <link rel="stylesheet" href="/assets/css/themes/headers/default.css" id="style_color-header-2" />  
    
    <link rel="stylesheet" href="/assets/more/css/style.css" />
    <link href="/assets/more/css/select2.css" rel="stylesheet" />
     
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/assets/css/normalize.css"/>
    <link rel="stylesheet" href="/assets/css/jquery.sidr.light.css"/>
	<link rel="stylesheet" href="/assets/css/animate.min.css"/>
	<link rel="stylesheet" href="/assets/css/md-slider.css"/>
    <link rel="stylesheet" href="/assets/css/style2.css"/>
    <link rel="stylesheet" href="/more/assets/css/style.css"/>
    <!--[if lte IE 7]>
    <link rel="stylesheet" href="css/ie7.css"/>
    <![endif]-->
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="css/ie8.css"/>
    <![endif]-->
    <link rel="stylesheet" href="/assets/css/responsive.css"/>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="js/html5.js"></script>
    <![endif]-->
    
    <script type="text/javascript" src="/assets/js/raphael-min.js"></script>
    <script type="text/javascript" src="/assets/js/jquery-1.9.1.min.js"></script>
	<script type="text/javascript" src="/assets/js/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.touchwipe.min.js"></script>
	<script type="text/javascript" src="/assets/js/md_slider.min.js"></script>
	<script type="text/javascript" src="/assets/js/jquery.sidr.min.js"></script>
    <script type="text/javascript" src="/assets/js/twitter.min.js"></script>
    <script type="text/javascript" src="/assets/js/pie.js"></script>
    <script type="text/javascript" src="/assets/js/script.js"></script>
    <script type="text/javascript" src="/assets/more/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" src="/assets/js/responsiveslides.min.js"></script>

    <!--[if lt IE 9]><script src="js/html5.js"></script><![endif]--><!--[if IE 7]><link href="css/ie7.css" rel="stylesheet"><![endif]--><!--[if IE 8]><link href="css/ie8.css" rel="stylesheet"><![endif]--><!--[if IE 9]><link href="css/ie9.css" rel="stylesheet"><![endif]-->

	<link href="http://vjs.zencdn.net/4.1/video-js.css" rel="stylesheet">
	<script src="http://vjs.zencdn.net/4.1/video.js"></script>
    
    <script src="/assets/more/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/assets/more/js/select2.min.js"></script>
          
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head> 

<body>

   
<?php echo $this->partial('header.phtml'); ?>

<!-- end #header -->

<?php echo $this->layout()->content; ?>
<!-- end #content -->

<?php echo $this->partial('footer.phtml'); ?>
<!-- end #footer -->


<!-- JS Global Compulsory -->           
<script type="text/javascript" src="/assets/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="/assets/js/modernizr.custom.js"></script>        
<script type="text/javascript" src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script> 
<!-- JS Implementing Plugins -->           
<script type="text/javascript" src="/assets/plugins/flexslider/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="/assets/plugins/parallax-slider/js/modernizr.js"></script>
<script type="text/javascript" src="/assets/plugins/parallax-slider/js/jquery.cslider.js"></script> 
<script type="text/javascript" src="/assets/plugins/bxslider/jquery.bxslider.js"></script>
<script type="text/javascript" src="/assets/plugins/back-to-top.js"></script>
<!-- JS Page Level -->           
<script type="text/javascript" src="/assets/js/app.js"></script>
<script type="text/javascript" src="/assets/js/pages/index.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initSliders();
        App.initBxSlider1();
        Index.initParallaxSlider();
    });
</script>
<!--[if lt IE 9]>
    <script src="/assets/js/respond.js"></script>
<![endif]-->


</body>
</html>