<!--<?php $role = Zend_Auth::getInstance()->getIdentity()->member_role;?> --><head>

<!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Le styles -->
    <!-- Use new way for google web fonts 
    http://www.smashingmagazine.com/2012/07/11/avoiding-faux-weights-styles-google-web-fonts -->
    <!-- Headings -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css' />  -->
    <!-- Text -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css' /> --> 
    <!--[if lt IE 9]>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:700" rel="stylesheet" type="text/css" />
    <!-- THIS IS DOWNLOADED FROM WWW.SXRIPTGATES.COM - SO THIS IS YOUR NEW SITE FOR DOWNLOAD SCRIPT ;) -->
    <![endif]-->

    <link href="http://new.winwinhost.com/wwwroot/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/bootstrap/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/supr-theme/jquery.ui.supr.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Plugin stylesheets -->
    <link href="http://new.winwinhost.com/wwwroot/plugins/qtip/jquery.qtip.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/jpages/jPages.css" rel="stylesheet" type="text/css" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/prettify/prettify.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/inputlimiter/jquery.inputlimiter.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/ibutton/jquery.ibutton.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/uniform/uniform.default.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/color-picker/color-picker.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/select/select2.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/validate/validate.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/pnotify/jquery.pnotify.default.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/pretty-photo/prettyPhoto.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/smartWizzard/smart_wizard.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/dataTables/jquery.dataTables.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/elfinder/elfinder.css" type="text/css" rel="stylesheet" />
    <link href="http://new.winwinhost.com/wwwroot/plugins/plupload/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" rel="stylesheet" />

    <!-- Main stylesheets -->
    <link href="http://new.winwinhost.com/wwwroot/css/main.css" rel="stylesheet" type="text/css" /> 

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/apple-touch-icon-144-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/apple-touch-icon-114-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/apple-touch-icon-72-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-57-precomposed.png" />
     
    <!-- Le javascript
    ================================================== -->

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/jquery.mousewheel.js"></script>
    <!-- THIS IS DOWNLOADED FROM WWW.SXRIPTGATES.COM - SO THIS IS YOUR NEW SITE FOR DOWNLOAD SCRIPT ;) -->
    <!-- Load plugins -->
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/qtip/jquery.qtip.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.grow.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.pie.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.resize.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.tooltip_0.4.4.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/flot/jquery.flot.orderBars.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/knob/jquery.knob.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/fullcalendar/fullcalendar.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/prettify/prettify.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/watermark/jquery.watermark.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/elastic/jquery.elastic.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/inputlimiter/jquery.inputlimiter.1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/maskedinput/jquery.maskedinput-1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/ibutton/jquery.ibutton.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/uniform/jquery.uniform.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/stepper/ui.stepper.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/color-picker/colorpicker.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/timeentry/jquery.timeentry.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/select/select2.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/dualselect/jquery.dualListBox-1.3.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/tiny_mce/jquery.tinymce.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/validate/jquery.validate.min.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/animated-progress-bar/jquery.progressbar.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/pnotify/jquery.pnotify.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/lazy-load/jquery.lazyload.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/jpages/jPages.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/pretty-photo/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/smartWizzard/jquery.smartWizard-2.0.min.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/ios-fix/ios-orientationchange-fix.js"></script>

    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/dataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/elfinder/elfinder.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/plupload.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/plupload.html4.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>

    <!-- Init plugins -->
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/statistic.js"></script><!-- Control graphs ( chart, pies and etc) -->

    <!-- Important Place before main.js  -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/plugins/touch-punch/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="http://new.winwinhost.com/wwwroot/js/main.js"></script>

    <script type="text/javascript">
        //adding load class to body and hide page
        document.documentElement.className += 'loadstate';
    </script>
    
    
   <!-- Load all Google JS libraries -->
  <script src="https://www.google.com/jsapi"></script>
  <script src="http://new.winwinhost.com/wwwroot/js/gadash-1.0.js"></script>
  <script src="https://apis.google.com/js/client.js?onload=gadashInit"></script>
  <script>
    
    // Configure these parameters before you start.
    var API_KEY = 'AIzaSyCNUtrzUFxmzd_XMBVPWhiGyV70PZBn_Ms';
    var CLIENT_ID = '1186879564-jq3neof8q91of7h31oubdruna8tggudb.apps.googleusercontent.com';
    var TABLE_ID = 'ga:50137426';
    // Format of table ID is ga:50137426 where xxx is the profile ID.

    gadash.configKeys({
      'apiKey': API_KEY,
      'clientId': CLIENT_ID
    });

    // Create a new Chart that queries visitors for the last 30 days and plots
    // visualizes in a line chart.
    var chart1 = new gadash.Chart({
      'type': 'LineChart',
      'divContainer': 'line-chart-example',
      'last-n-days':30,
      'query': {
        'ids': TABLE_ID,
        'metrics': 'ga:visitors, ga:pageviews',
        'dimensions': 'ga:date'
      },
      'chartOptions': {
        height:600,
        title: 'This is Phone Tracker Stats from Google Analytics',
        hAxis: {title:'Date'},
        vAxis: {title:'Visits'},
        curveType: 'function'
      }
    }).render();
	
	
	 // Create a new Chart that queries visitors for the last 30 days and plots
    // visualizes in a line chart.
	//var sourceMediumTable = new gadash.Chart(
	//{
     // 'type': 'Table',
     // 'divContainer': 'sourceMediumTableConfig',
	 // 'last-n-days':30,
    //  'query': {
     // 'dimensions': 'ga:source,ga:medium',
     // 'sort': '-ga:visitors',
    //  'max-results': 100
   // },
     // 'chartOptions': {
     //   height:600,
	//	width:700,
     //   title: 'Traffic Sources',
    //  }
   // }
	
	//).render();
	
	
  
  </script>
  

</head>

<?php  if ($role == 1 ): ?>


<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>Dash Board for Admin<span> overview of stats and management notifications </span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>-->
   </ul>
  </div>
 </div>
 <!-- /top_title -->
              
</div>


<!-- Add Google Analytics authorization button -->
                          <button id="authorize-button" style="visibility: hidden">
                                Authorize Analytics</button>
                        
                          <!-- Div element where the Line Chart will be placed -->
                          <div id='line-chart-example'></div>
                          <!-- <div id='sourceMediumTableConfig'></div> -->


<div class="wraper">

						  

<div class="row-fluid">

                    <!-- <div class="span9">

                        <div class="box chart gradient">

                            <div class="title">

                                <h4>
                                    <span class="icon16 icomoon-icon-bars"></span>
                                    <span>Visitors Chart</span>
                                </h4>
                                <a href="#" class="minimize">Minimize</a>
                            </div>
                            <div class="content" style="padding-bottom:0;">
                               <div class="visitors-chart" style="height: 230px;width:100%;margin-top:15px; margin-bottom:15px;"></div>
                               <ul class="chartShortcuts">
                                    <li>
                                        <a href="#">
                                            <span class="head">Total Domains</span>
                                            <span class="number">509</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Domains today</span>
                                            <span class="number">309</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Domains today</span>
                                            <span class="number">109</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Domains today</span>
                                            <span class="number">325</span>
                                        </a>
                                    </li>
                                </ul>
                               
                            </div>

                        </div>

                    </div> -->

                    <!-- <div class="span3">

                        <div class="sparkStats">
                            <h4>389 people visited this site <a href="#" class="icon tip" title="Configure"><span class="icon16 iconic-icon-cog"></span></a></h4>
                            <ul class="unstyled">
                                <li><span class="sparkLine1 "></span> Visits: <span class="number">509</span></li>
                                <li>
                                    <span class="sparkLine2"></span>
                                    Unique Visitors: 
                                    <span class="number">389</span>
                                </li>
                                <li><span class="sparkLine3"></span> 
                                    Pageviews: 
                                    <span class="number">731</span>
                                </li>
                                <li><span class="sparkLine4"></span>
                                    Pages / Visit: 
                                    <span class="number">1.44</span>
                                </li>
                                <li><span class="sparkLine5"></span>
                                    Avg. Visit Duration: 
                                    <span class="number">00:01:21</span>
                                </li>
                                <li><span class="sparkLine6"></span>
                                    Bounce Rate: <span class="number">68.37%</span>
                                </li>
                                <li><span class="sparkLine7"></span>
                                    % New Visits: 
                                    <span class="number">76.23%</span>
                                </li>

                            </ul>
                            <div class="right" style="padding: 15px 0">
                                <a href="charts.html" class="btn btn-info">View full statistic <span class="icon16 icomoon-icon-arrow-right white"></span></a>
                            </div>
                        </div>
                        

                    </div> -->

                </div>

               <!-- <div class="row-fluid">

                    <div class="span12">
                        <div class="centerContent">
                  
                            <ul class="bigBtnIcon">
                                <li>
                                    <a href="#" title="I`m with gradient" class="tipB">
                                        <span class="icon entypo-icon-users"></span>
                                        <span class="txt">Users</span>
                                        <span class="notification">5</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="icon icomoon-icon-support"></span>
                                        <span class="txt">Support tickets</span>
                                        <span class="notification blue">12</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="I`m with pattern" class="pattern tipB">
                                        <span class="icon icomoon-icon-comments-2"></span>
                                        <span class="txt">New Comments</span>
                                        <span class="notification green">23</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="icon icomoon-icon-basket"></span>
                                        <span class="txt">Orders</span>
                                        <span class="notification">+5</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="icon icomoon-icon-history"></span>
                                        <span class="txt">Backups</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="icon icomoon-icon-meter-fast"></span>
                                        <span class="txt">Site Usage</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

              </div> -->
        </div>
              
              
              
              
    


<?php elseif ($role == 2 ): ?>  

<div class="content_block">
 <!-- top_title -->
 <div class="top_title">
  <div class="wraper">
   <h2>Welcome <span>Manage Your Domains here</span></h2>
   <ul>
    <!-- <li><a href="#">Home</a></li>
    <li><a href="#"></a></li> 
    <li></li>-->
   </ul>
  </div>
 </div>
 <!-- /top_title -->
              
</div>


<div class="wraper">




                <div class="row-fluid">
                
                   <div class="span6">
                            <div class="reminder">

                                <div class="title">
                                    <h4>
                                        <span class="icon16 entypo-icon-settings"></span>
                                        <span>Your Account Settings</span>
                                    </h4>
                                </div>
                                <div class="content noPad">
                                    <ul class="activity">
                                        <li>
                                            <span class="icon16 icomoon-icon-user-2 blue"></span>
                                            User: <strong>Adil Shakar</strong>
                                            <a href="#" class="btn btn-mini">edit</a>
                                        </li>
                                        <li>
                                            <span class="icon16 iconic-icon-mail blue"></span>
                                            Email address: <strong>adilshakar@gmail.com</strong>
                                            <a href="#" class="btn btn-mini">edit</a>                                        
                                        </li>
                                        <li>
                                            <span class="icon16 icomoon-icon-calculate blue"></span>
                                            Balance: <strong> $153 </strong>
                                            <a href="#" class="btn btn-mini">make a payment</a>
                                        </li>
                                        <li>
                                            <span class="icon16 entypo-icon-address blue"></span>
                                            Billing address: <strong>Adil Shakar , CB 48 , Gulshan Iqbal , Abbottabad ,Pakistan </strong>
                                            <a href="#" class="btn btn-mini">edit</a>
                                        </li>
                                        <li>
                                            <span class="icon16 entypo-icon-address blue"></span>
                                            Support address: <strong>Adil Shakar , CB 48 , Gulshan Iqbal , Abbottabad ,Pakistan </strong>
                                            <a href="#" class="btn btn-mini">edit</a>
                                        </li>
                                    </ul>
                                </div>

                            </div><!-- End .box -->
                        </div>

                    <div class="span6">

                        <div class="reminder">
                            <h4>Your Domains
                                 <a href="#" class="icon tip " title="Configure"><span class="icon16 entypo-icon-settings"></span></a>
                            </h4>
                            <ul>
                                <li class="clearfix">
                       				 <div class="icon">
                                        <span class="icon32 icomoon-icon-clock green"></span>
                                    </div>
                                    <span class="number"> <a alt="Days left" title="Days left"> 356 </a></span> 
                                    <span class="txt"><strong>winwinhost.com</strong></span>
                                    <a class="btn btn-info">GO</a>
                                </li>
                                
                                <li class="clearfix">
                                    <div class="icon">
                                        <span class="icon32 icomoon-icon-clock green"></span>
                                    </div>
                                    <span class="number"> <a alt="Days left" title="Days left"> 326 </a></span> 
                                    <span class="txt"><strong>phone-tracker.net</strong></span>
                                    <a class="btn btn-info">GO</a>
                                </li>
                                <li class="clearfix">
                                    <div class="icon">
                                        <span class="icon32 icomoon-icon-clock green"></span>
                                    </div>
                                    <span class="number"> <a alt="Days left" title="Days left">143 </a></span>
                                    <span class="txt"><strong>digitalspying.com</strong></span>
                                    <a class="btn btn-info">GO</a>
                                </li>
                                <li class="clearfix">
                                    <div class="icon">
                                        <span class="icon32 icomoon-icon-clock green"></span>
                                    </div>
                                    <span class="number"> <a alt="Days left" title="Days left">133</a></span>  
                                    <span class="txt"><strong>webdesigner.la</strong></span> 
                                    <a class="btn btn-info">GO</a>
                                </li>
                                <li class="clearfix">
                                    <div class="icon">
                                        <span class="icon32 icomoon-icon-history red"></span>
                                    </div>
                                    <span class="number"> <a alt="Days left" title="Days left">-21 </a></span> 
                                    <span class="txt"><strong>astoreforbeauty.com</strong></span>
                                    <a class="btn btn-info">GO</a>
                                </li>                                   
                            </ul>
                        </div><!-- End .reminder -->

                    </div><!-- End .span4 -->                   
                           
                    </div>

                </div>
                
                <div class="row-fluid">

                    <div class="span12">

                        <div class="box chart gradient">

                            <div class="title">

                                <h4>

                                     <span class="icon16 entypo-icon-thumbs-up"></span>
                                    <span>winwinhost.com<span class="label label-success">days left<span class="icomoon-icon-arrow-up white"></span>346</span></span>
                                    
                                </h4>
                                <a href="#" class="minimize">Minimize</a>
                            </div>
                            <div class="content" style="padding-bottom:0;">
                               
                               <ul class="chartShortcuts">
                                    <li>
                                        <a href="#">
                                            <span class="head">Contact</span>
                                            <span class="number">Adil Shakar</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Expiration</span>
                                            <span class="number">12-09-2014</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Name Servers</span>
                                            <span class="number">ns1.winwinhost.com</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Transfer To another </span>
                                            <span class="number">Registerar</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Renew </span>
                                            <span class="number">Domain</span>
                                        </a>
                                    </li>
                                </ul>
                               
                            </div>

                        </div><!-- End .box -->

                    </div>

                </div>
                
                <div class="row-fluid">

                    <div class="span12">

                        <div class="box chart gradient">

                            <div class="title">

                                <h4>
                                
                                     <span class="icon16 entypo-icon-thumbs-up"></span>
                                     <span>Phone-Tracker.net<span class="label label-success">days left<span class="icomoon-icon-arrow-up white"></span>211</span></span>
                                       
                                </h4>
                                <a href="#" class="minimize">Minimize</a>
                            </div>
                            <div class="content" style="padding-bottom:0;">
                               
                               <ul class="chartShortcuts">
                                    <li>
                                        <a href="#">
                                            <span class="head">Contact</span>
                                            <span class="number">Robert</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Expiration</span>
                                            <span class="number">12-09-2014</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Name Servers</span>
                                            <span class="number">ns1.winwinhost.com</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Transfer To another </span>
                                            <span class="number">Registerar</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span class="head">Renew </span>
                                            <span class="number">Domain</span>
                                        </a>
                                    </li>
                                </ul>
                               
                            </div>

                        </div><!-- End .box -->

                    </div>

                </div>                              

                <!-- End .row-fluid --><!-- End .row-fluid --><!-- End .row-fluid --><!-- End .row-fluid --></div><!-- End contentwrapper -->

<?php elseif ($role == 3 ):  ?>  

<?php endif; ?>


