<!-- Region 3 Wrap -->

<div class="container region3wrap">  


    <!-- Content Top -->  
    <div class="row content_top">

        <div class="nine columns">

            <h1>
                <?php
                if ($this->ErrorMsg == 'Error') {
                    echo 'Oops......';
                } else {
                    echo 'Thanks';
                }
                ?>

            </h1>

        </div>
    </div>
    <!-- End Content Top -->

</div>

<!-- End Region 3 Wrap -->

<!-- Region 4 Wrap -->

<div class="container region4wrap">

    <div class="row maincontent">

        <div class="twelve columns">

            <div class="page_title">

                <div class="row">

                    <div class="twelve columns">
                        <h1><small>
                               <?php
                                if ($this->ErrorMsg == 'Error') {
                                    echo 'Invalid Information. Please enter valid information.';
                                } else {
                                    echo ' You have added successfully on newsletter receiver lisk.';
                                }
                                ?>
                               
                            </small></h1>

                    </div>

                </div>

            </div>

        </div> 
        <div class="twelve columns">

<!--            <h3><small>Please check your email and click on the verification link in order to activate your account , Thank you</small></h3>-->

            <!-- Pricing Table -->


            <!-- End Pricing Table -->

        </div>

    </div>

</div>


</div>

</div>

<!-- End Region 4 Wrap -->