
<body class="home blog">

<div class="home-wrap clearfix">

<!-- slider here -->
<div class="callbacks_container">
      <ul class="rslides" id="slider3">
        <li>
          <img src="images/slides/1.jpg" alt="" />
          <p class="caption">Enjoy access to our WinWinHost Hosting Offers</p>
        </li>
        <li>
          <img src="images/slides/2.jpg" alt="" />
          <p class="caption">Whatever the Technology is , We finish up the projects upto your requirements </p>
        </li>
        <li>
          <img src="images/slides/3.jpg" alt="" />
          <p class="caption">With us you can help yourself bring traffic, customers, and a strong return on investment</p>
        </li>
      </ul>
    </div>
    
    

		<div id="home-tagline" class="clearfix">
		<a href="#"> WinWinHost</a> is a <a href="#">PERFECT</a> for all the web services.</div>
    <!-- /home-tagline -->
	

        


<div id="home-highlights" class="clearfix">
	
            <div class="heading">
                            <h2><a href="" title="What We Do"><span>What We Do</span></a></h2>
                    </div>
        <!-- /heading -->
        
		
	<div class="hp-highlight">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_webhosting.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Web Hosting">Hosting</a></h3>
		<p>WinWinHost Provides hosting servies at right rates and all the features that should be there with respect to present technology around the web. You can choose from many packages that suits you best.</p>
	</div>
    <!-- /hp-highlight -->
		
	<div class="hp-highlight  ">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_domains.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Domains Names">Domains</a></h3>
		<p>Register you Brand Names with Us , Domain Names is the gateway to your business on the web. Register today with the lowest rates around and we will help you further you setup your site quickly.  </p>
	</div>
    <!-- /hp-highlight -->
		
	<div class="hp-highlight highlight-third ">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_webdevelopment.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Web Development">Web Development</a></h3>
		<p>We are extremely proficient at setting up solutions for our clients. We offer Basic Web sites to Mobile Application Development, Cloud Computing solutions , and many other types of software development services.</p>
	</div> 
    <!-- /hp-highlight -->
		
	<div class="hp-highlight  ">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_mobile.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Mobile Development">Mobile Development</a></h3>
		<p>At WinWinHost we are now developing Mobile optimized websites and apps for both Android and IOS. Mobile industry is againing shares in the Tech World rapidly , make your Identity in the Mobile World with us.</p>
	</div>
    <!-- /hp-highlight -->
		
	<div class="hp-highlight highlight-third highlightw-fifth">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_opensource.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Open Source">Open Source</a></h3>
		<p>We are working to provide best Open Source programs to his customers and not only this but now we are offering some open source projects and we hope in future to increase their number and of course to add new features to the existing projects.</p>
	</div>
    <!-- /hp-highlight -->
		
	<div class="hp-highlight  ">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_seo.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Search Engine Optimization">SEO Optimization</a></h3>
		<p>Search Engine Optimization refers to optimize your site to be easily found by search engines and we have experts who can make your site on top of Google's results , giving your organic traffic so you dont have to spend anything monthly</p>
	</div>
    <!-- /hp-highlight -->
		
	<div class="hp-highlight highlight-third ">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_marketing.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Online Marketing">Online Marketing</a></h3>
		<p>Let the experts get you the largest possible ROI. WinWinHost.com can conduct your Email Marketing Campaigns, manage your PPC campaigns, setup CPA affiliate systems, 
and even design print advertising.</p>
	</div>
    <!-- /hp-highlight -->
		
	<div class="hp-highlight  ">
		<h3 class="heading-with-icon" style="background-image: url(images/highlight-icons/home_wordpress.png);padding-left: 47px;height: 32px;line-height: 32px;"><a href="#" title="Word Press development">Word Press</a></h3>
		<p>At WinWinHost we are also building things for Word Press , either its theme Development or Plugin Development even customizing earlier themes and plugins.We are also making Plugins in general use for people around the web.</p>
	</div>
    <!-- /hp-highlight -->
	
</div>
<!-- END #home-highlights -->      	


        


<div id="home-projects" class="home-projects-carousel clearfix">

	        <div class="heading">
                            <h2><a href="" title="Recent Work"><span>Recent Work</span></a></h2>
                    </div>
        <!-- /heading -->
    
	<div id="home-portfolio-carousel-wrp" class="clearfix">
    	<div id="home-portfolio-carousel" class="fredcarousel">
		        
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/disneymovies.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/linkdirectoryplugin.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/eonline.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
               <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/disneymovies.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/linkdirectoryplugin.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/eonline.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
               <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/disneymovies.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/linkdirectoryplugin.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                
                
                </div>
        <!-- /home-portfolio-carousel -->
        <div id="carousel-prev"></div>
        <div id="carousel-next"></div>
        
        <div id="carousel-pagination" class="pagination"></div>
    </div>
    <!-- /home-portfolio-carousel-wrp -->


</div>
<!-- /home-projects -->      	


        


<div id="home-projects-responsive" class="home-projects-responsive clearfix">

	        <div class="heading">
                            <h2><a href="" title="Recent Work"><span>Recent Work</span></a></h2>
                    </div>
        <!-- /heading -->
    
	<div id="portfolio-wrap" class="clearfix">
		        
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/disneymovies.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/linkdirectoryplugin.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/eonline.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/disneymovies.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/linkdirectoryplugin.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/eonline.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/disneymovies.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                <div class="portfolio-item">
            <a href="" title=""><img src="images/portfolio/linkdirectoryplugin.jpg" height="140" width="215" alt="" /></a>
            <h3></h3>
        </div>
        <!-- /portfolio-item -->
                
                
                </div>
        <!-- /portfolio-wrap -->

</div>
<!-- /home-projects-responsive -->      	


  

<div id="home-blog" class="clearfix">

	        <div class="heading">
                            <h2><a href="" title="From The Blog"><span>WinWinHost news</span></a></h2>
                    </div>
        <!-- /heading -->
    	
	
    

    
    
    
	<?php foreach($this->data as $data): ?>	
     
	<div class="home-entry">
    				<a href="" title="Mauris orci nibh, laoreet nec dictum"><img src="" alt="Mauris orci nibh, laoreet nec dictum" /></a>
        		<h3><a href="" title="Mauris orci nibh, laoreet nec dictum"><?php echo $data->news_title; ?>&nbsp;<?php echo $data->news_posted; ?></a></h3>
				<?php echo $data->news_text; ?></div>
	<?php endforeach; ?>
		
	
	
		
	
	
	
</div>
<!-- END #home-blog -->      	


</div>

