
<div class="breadcrumbs margin-bottom-40  btn-u-blue">
	<div class="container">
        <h1 class="color-green pull-left "><a href="/"><img src="/images/find.png" alt="Hire Remote"/></a></h1>
        <ul class="pull-right breadcrumb">
                                 <form class="form-search">
                                    <input type="text" class="border-radius-none input-medium search-query" />
                                    <button type="submit" class="btn-u">Search</button>
                                </form>  
        </ul>
    </div><!--/container-->
</div>

<div class="container">		    
	<div class="row-fluid">
    <div class="span9">
    
            <div class="search-result-page">
                <div class="top-lbl-val ">
                    <h3 class="common-title">Find Job / <span class="fc-orange">Search</span></h3>
                    <div class="count-result">
                        <span class="fw-b fc-black">560</span> Jobs found for "<span class="fw-b fc-black">Web Design</span>"
                    </div>
                    <div class="confirm-search">Were you looking for projects in <a href="#" class="fw-b be-fc-orange">Web Design</a>?</div>
                </div>
                <div id="list-search-ajax" class="list-project-result">
                    <div class="project-short larger">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/clients/winwinhost.png" alt="WinWinHost Inc" >
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="#">Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</a></h3>
                                    <p class="rs tiny-desc">by <a href="#" class="fw-b fc-gray be-fc-orange">WinWinHost</a> in <span class="fw-b fc-gray">Los Angeles , CA</span></p>
                                    <p class="rs title-description">We need someone very skilled in CSS and graphic optimization to resolve some issues for us:The following images served from</p>

                                </div>
                                <p class="rs clearfix comment-view">
                                    <a href="#" class="fc-gray be-fc-orange">212 Applicants</a>
                                    <span class="sep">|</span>
                                    <a href="#" class="fc-gray be-fc-orange">45 interviewing</a>
                                </p>
                            </div>
                        </div><!--end: .top-project-info --> 
                        <div class="bottom-project-info clearfix">
                        <div class="project-progress sys_circle_progress" data-percent="15">
                            <div class="sys_holder_sector"></div>
                            <p class="rs lbl">Verified Client</p>
                        </div>
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                                <p class="rs lbl">Applications</p>
                                <span class="val">270</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Hiring &nbsp;&nbsp;</p>
                                <span class="val">Open</span>
                                
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Workspace</p>
                                <span class="val">Virtual</span>
                           	    
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                           	    <p class="rs lbl">Posted</p>
                                <span class="val">19 minutes ago</span>
                            </div>
                        </div>
                        
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                            	<p class="rs lbl">Short Listed</p>
                                <span class="val">16</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item"> 
                                <p class="rs lbl">Bugdet</p>
                                <span class="val">$38,00</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                                <p class="rs lbl">Type</p>
                                <span class="val">Fixed Price</span>
                            </div>
                        </div>
                        <a class="btn btn-red btn-buck-project" href="#">Details</a>
                         <a class="btn btn-red btn-buck-project" href="#">Apply</a>
                        
                        <div class="clear"></div>
                    </div>
                    </div>
                    
                    
                    <div class="project-short larger">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/clients/microsoft.png" alt="WinWinHost Inc" >
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="#">Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</a></h3>
                                    <p class="rs tiny-desc">by <a href="#" class="fw-b fc-gray be-fc-orange">WinWinHost</a> in <span class="fw-b fc-gray">Los Angeles , CA</span></p>
                                    <p class="rs title-description">We need someone very skilled in CSS and graphic optimization to resolve some issues for us:The following images served from</p>

                                </div>
                                <p class="rs clearfix comment-view">
                                    <a href="#" class="fc-gray be-fc-orange">212 Applicants</a>
                                    <span class="sep">|</span>
                                    <a href="#" class="fc-gray be-fc-orange">45 interviewing</a>
                                </p>
                            </div>
                        </div><!--end: .top-project-info --> 
                        <div class="bottom-project-info clearfix">
                        <div class="project-progress sys_circle_progress" data-percent="15">
                            <div class="sys_holder_sector"></div>
                            <p class="rs lbl">Verified Client</p>
                        </div>
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                                <p class="rs lbl">Applications</p>
                                <span class="val">270</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Hiring &nbsp;&nbsp;</p>
                                <span class="val">Open</span>
                                
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Workspace</p>
                                <span class="val">Virtual</span>
                           	    
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                           	    <p class="rs lbl">Posted</p>
                                <span class="val">19 minutes ago</span>
                            </div>
                        </div>
                        
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                            	<p class="rs lbl">Short Listed</p>
                                <span class="val">16</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item"> 
                                <p class="rs lbl">Bugdet</p>
                                <span class="val">$38,00</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                                <p class="rs lbl">Type</p>
                                <span class="val">Fixed Price</span>
                            </div>
                        </div>
                        <a class="btn btn-red btn-buck-project" href="#">Details</a>
                         <a class="btn btn-red btn-buck-project" href="#">Apply</a>
                        
                        <div class="clear"></div>
                    </div>
                    </div>
                    
                    
                    
                    <div class="project-short larger">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/clients/winwinhost.png" alt="WinWinHost Inc" >
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="#">Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</a></h3>
                                    <p class="rs tiny-desc">by <a href="#" class="fw-b fc-gray be-fc-orange">WinWinHost</a> in <span class="fw-b fc-gray">Los Angeles , CA</span></p>
                                    <p class="rs title-description">We need someone very skilled in CSS and graphic optimization to resolve some issues for us:The following images served from</p>

                                </div>
                                <p class="rs clearfix comment-view">
                                    <a href="#" class="fc-gray be-fc-orange">212 Applicants</a>
                                    <span class="sep">|</span>
                                    <a href="#" class="fc-gray be-fc-orange">45 interviewing</a>
                                </p>
                            </div>
                        </div><!--end: .top-project-info --> 
                        <div class="bottom-project-info clearfix">
                        <div class="project-progress sys_circle_progress" data-percent="15">
                            <div class="sys_holder_sector"></div>
                            <p class="rs lbl">Verified Client</p>
                        </div>
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                                <p class="rs lbl">Applications</p>
                                <span class="val">270</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Hiring &nbsp;&nbsp;</p>
                                <span class="val">Open</span>
                                
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Workspace</p>
                                <span class="val">Virtual</span>
                           	    
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                           	    <p class="rs lbl">Posted</p>
                                <span class="val">19 minutes ago</span>
                            </div>
                        </div>
                        
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                            	<p class="rs lbl">Short Listed</p>
                                <span class="val">16</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item"> 
                                <p class="rs lbl">Bugdet</p>
                                <span class="val">$38,00</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                                <p class="rs lbl">Type</p>
                                <span class="val">Fixed Price</span>
                            </div>
                        </div>
                        <a class="btn btn-red btn-buck-project" href="#">Details</a>
                         <a class="btn btn-red btn-buck-project" href="#">Apply</a>
                        
                        <div class="clear"></div>
                    </div>
                    </div>
                    
                    
                    
                    <div class="project-short larger">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/clients/winwinhost.png" alt="WinWinHost Inc" >
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="#">Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</a></h3>
                                    <p class="rs tiny-desc">by <a href="#" class="fw-b fc-gray be-fc-orange">WinWinHost</a> in <span class="fw-b fc-gray">Los Angeles , CA</span></p>
                                    <p class="rs title-description">We need someone very skilled in CSS and graphic optimization to resolve some issues for us:The following images served from</p>

                                </div>
                                <p class="rs clearfix comment-view">
                                    <a href="#" class="fc-gray be-fc-orange">212 Applicants</a>
                                    <span class="sep">|</span>
                                    <a href="#" class="fc-gray be-fc-orange">45 interviewing</a>
                                </p>
                            </div>
                        </div><!--end: .top-project-info --> 
                        <div class="bottom-project-info clearfix">
                        <div class="project-progress sys_circle_progress" data-percent="15">
                            <div class="sys_holder_sector"></div>
                            <p class="rs lbl">Verified Client</p>
                        </div>
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                                <p class="rs lbl">Applications</p>
                                <span class="val">270</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Hiring &nbsp;&nbsp;</p>
                                <span class="val">Open</span>
                                
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Workspace</p>
                                <span class="val">Virtual</span>
                           	    
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                           	    <p class="rs lbl">Posted</p>
                                <span class="val">19 minutes ago</span>
                            </div>
                        </div>
                        
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                            	<p class="rs lbl">Short Listed</p>
                                <span class="val">16</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item"> 
                                <p class="rs lbl">Bugdet</p>
                                <span class="val">$38,00</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                                <p class="rs lbl">Type</p>
                                <span class="val">Fixed Price</span>
                            </div>
                        </div>
                        <a class="btn btn-red btn-buck-project" href="#">Details</a>
                         <a class="btn btn-red btn-buck-project" href="#">Apply</a>
                        
                        <div class="clear"></div>
                    </div>
                    </div>
                    
                    
                    
                    <div class="project-short larger">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="#" class="thumb-img">
                                    <img src="/images/clients/winwinhost.png" alt="WinWinHost Inc" >
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="#">Web Developer with skills of HTML5 , CSS3 , Zend , Laravel</a></h3>
                                    <p class="rs tiny-desc">by <a href="#" class="fw-b fc-gray be-fc-orange">WinWinHost</a> in <span class="fw-b fc-gray">Los Angeles , CA</span></p>
                                    <p class="rs title-description">We need someone very skilled in CSS and graphic optimization to resolve some issues for us:The following images served from</p>

                                </div>
                                <p class="rs clearfix comment-view">
                                    <a href="#" class="fc-gray be-fc-orange">212 Applicants</a>
                                    <span class="sep">|</span>
                                    <a href="#" class="fc-gray be-fc-orange">45 interviewing</a>
                                </p>
                            </div>
                        </div><!--end: .top-project-info --> 
                        <div class="bottom-project-info clearfix">
                        <div class="project-progress sys_circle_progress" data-percent="15">
                            <div class="sys_holder_sector"></div>
                            <p class="rs lbl">Verified Client</p>
                        </div>
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                                <p class="rs lbl">Applications</p>
                                <span class="val">270</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Hiring &nbsp;&nbsp;</p>
                                <span class="val">Open</span>
                                
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                            	<p class="rs lbl">Workspace</p>
                                <span class="val">Virtual</span>
                           	    
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                           	    <p class="rs lbl">Posted</p>
                                <span class="val">19 minutes ago</span>
                            </div>
                        </div>
                        
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                            	<p class="rs lbl">Short Listed</p>
                                <span class="val">16</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item"> 
                                <p class="rs lbl">Bugdet</p>
                                <span class="val">$38,00</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                                <p class="rs lbl">Type</p>
                                <span class="val">Fixed Price</span>
                            </div>
                        </div>
                        <a class="btn btn-red btn-buck-project" href="#">Details</a>
                         <a class="btn btn-red btn-buck-project" href="#">Apply</a>
                        
                        <div class="clear"></div>
                    </div>
                    </div>

                </div>
                <p class="rs ta-c">
                    <a id="showmoreresults" class="btn btn-black btn-load-more" href="#">Show more projects</a>
                </p>
            </div>
           </div>

        <div class="span3 ">
        
        <div class="project-runtime">
        
        <div class="project-author">
          
                      
    
         </div>
         <div class="clear"></div>
         
                
            </div>
            
            
            

            <div class="clear clear-2col"></div>
            <div class="wrap-nav-pledge">
                                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount">Marketing </span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
                <ul class="rs nav nav-pledge accordion">
                                    <li>
                                        <div class=" pledge-label accordion-label clearfix">
                                            <i class="icon iPlugGray"></i>
                                            <span class="pledge-amount"> Advertising</span>
                                            <span class="count-val">(12 of 31)</span>
                                        </div>
                                        <div class=" pledge-content accordion-content">
                                            <div class="pledge-detail">
                                            <ul class="rs nav-category">
                                    <li>
                                        <a href="#" >
                                            Advertising Writers
                                            <span class="count-val">(12)</span>
                                            <i class="icon iPlugGrays "></i>
                                        </a>
                                    </li>
                                    <li class="active">
                                        <a href="#" class="fc-blue"  >
                                            Advertising Executives
                                            <span class="count-val">(2)</span>
                                            <i class="icon iPlugGray "></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Auctioneers
                                            <span class="count-val">(212)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Buying Officers
                                            <span class="count-val">(35)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                             Purchasing Officers 
                                            <span class="count-val">(67)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            contract officers
                                            <span class="count-val">(23)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Estate Agents
                                            <span class="count-val">(52)</span>
                                            <i class="icon iPlugGray"></i>
                                        </a>
                                    </li>
                                </ul>
 
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        
                        
                    </li><!--end: pledge-item -->
                </ul>
                
            </div><!--end: .wrap-nav-pledge -->
        </div>

    </div>
    
    </div>
    
