 <div class="layout-2cols">
        <div class="content grid_8">
            <div class="project-detail"> 
                <div class="project-short big-thumb">
                    <div class="top-project-info">
                        <div class="content-info-short clearfix">
                        <h2 class="rs project-title"> CSS Sprites / Website Optimization </h2>
                            <p class="rs post-by">by <a href="#" class="fw-b fc-gray be-fc-orange">Ray Sumser</a> in <span class="fw-b fc-gray">New York, NY</span></p>   
                        </div>
                    </div><!--end: .top-project-info -->
                    <div class="bottom-project-info clearfix">
                        <div class="project-progress sys_circle_progress" data-percent="15">
                            <div class="sys_holder_sector"></div>
                            <p class="rs lbl">Verified Client</p>
                        </div>
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                                <p class="rs lbl">Applications</p>
                                <span class="val">270</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                                <p class="rs lbl">Posted</p>
                                <span class="val">19 minutes ago</span>
                                
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                           	    <p class="rs lbl">Type</p>
                                <span class="val">Fixed Price</span>
                                
                            </div>
                        </div>
                        
                        <div class="group-fee clearfix">
                            <div class="fee-item">
                            	<p class="rs lbl">Short Listed</p>
                                <span class="val">16</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item"> 
                                <p class="rs lbl">Bugdet</p>
                                <span class="val">$38,00</span>
                            </div>
                            <div class="sep"></div>
                            <div class="fee-item">
                                <p class="rs lbl">Workspace</p>
                                <span class="val">Virtual</span>
                            </div>
                        </div>
                        
                        
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="project-tab-detail tabbable accordion">
                    <ul class="nav nav-tabs clearfix">
                      <li class="active"><a href="#">Description</a></li>
                      <li><a href="#" class="be-fc-orange">Updates (0)</a></li>
                      <li><a href="#" class="be-fc-orange">Backers (270)</a></li>
                      <li><a href="#" class="be-fc-orange">Comments (2)</a></li>
                    </ul>
                    <div class="tab-content">
                        <div>
                            <h3 class="rs alternate-tab accordion-label"> Description</h3>
                            <div class="tab-pane active accordion-content">
                                <div class="editor-content">
                                    <h3 class="rs title-inside">CSS Sprites / Website Optimization</h3>
                               
                                    <p>We need someone very skilled in CSS and graphic optimization to resolve some issues for us:<br />
                                      <br />
                                      The following images served from avianweb.com should be combined into as few images as possible using CSS sprites.<br />
                                      <a target="_blank" href="http://www.avianweb.com/">http://www.avianweb.com/</a><br />
                                      <a target="_blank" href="http://www.avianweb.com/parrotindex.htm">http://www.avianweb.com/parrotindex.htm</a><br />
                                      <a target="_blank" href="http://www.avianweb.com/breeder.htm">http://www.avianweb.com/breeder.htm</a><br />
                                      <br />
                                      as well as resolving other problems as identified on this page:<br />
                                      <a target="_blank" href="http://www.avianweb.com/dJf0ovSx" _blank>www.avianweb.com/dJf0ovSx</a>&quot;&gt;http://gtmetrix.com/reports/<a target="_blank" href="http://www.avianweb.com/dJf0ovSx">www.avianweb.com/dJf0ovSx</a><br />
                                      <br />
                                    Please note, we won't be providing access to the actual website, so ideally, a testing website with the templates and css files can be provided at your end (with the same folder structure as ours), or we could potentially provide that.</p>
                                    <div class="social-sharing">
                                        <!-- AddThis Button BEGIN -->
                                        <div class="addthis_toolbox addthis_default_style">
                                        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                                        <a class="addthis_button_tweet"></a>
                                        <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
                                        <a class="addthis_counter addthis_pill_style"></a>
                                      </div>
                                        <script type="text/javascript" src="../../../s7.addthis.com/js/300/addthis_widget.js#pubid=undefined"></script>
                                        <!-- AddThis Button END -->
                                  </div>
                                </div>
                                <div class="project-btn-action">
                                    <a class="btn big btn-red" href="#">Ask a question</a>
                                    <a class="btn big btn-black" href="#">Report this project</a>
                                </div>
                            </div><!--end: .tab-pane(About) -->
                        </div>
                        <div>
                            <h3 class="rs alternate-tab accordion-label">Updates (0)</h3>
                            <div class="tab-pane accordion-content">
                                <div class="tab-pane-inside">
                                    <div class="list-last-post">
                                        <div class="media other-post-item">
                                            <a href="#" class="thumb-left">
                                                <img src="/images/ex/th-90x90-1.jpg" alt="$TITLE">
                                            </a>
                                            <div class="media-body">
                                                <h4 class="rs title-other-post">
                                                    <a href="#" class="be-fc-orange fw-b">John Doe</a>
                                                </h4>
                                                <p class="rs fc-gray time-post pb10">posted 5 days ago</p>
                                                <p class="rs description">Nam nec sem ac risus congue varius. Maecenas interdum ipsum tempor ipsum fringilla eu vehicula urna vehicula.</p>
                                            </div>
                                        </div><!--end: .other-post-item -->
                                        <div class="media other-post-item">
                                            <a href="#" class="thumb-left">
                                                <img src="/images/ex/th-90x90-2.jpg" alt="$TITLE">
                                            </a>
                                            <div class="media-body">
                                                <h4 class="rs title-other-post">
                                                    <a href="#" class="be-fc-orange fw-b">John Doe</a>
                                                </h4>
                                                <p class="rs fc-gray time-post pb10">posted 5 days ago</p>
                                                <p class="rs description">Nam nec sem ac risus congue varius. Maecenas interdum ipsum tempor ipsum fringilla eu vehicula urna vehicula.</p>
                                            </div>
                                        </div><!--end: .other-post-item -->
                                        <div class="media other-post-item">
                                            <a href="#" class="thumb-left">
                                                <img src="/images/ex/th-90x90-3.jpg" alt="$TITLE">
                                            </a>
                                            <div class="media-body">
                                                <h4 class="rs title-other-post">
                                                    <a href="#" class="be-fc-orange fw-b">John Doe</a>
                                                </h4>
                                                <p class="rs fc-gray time-post pb10">posted 5 days ago</p>
                                                <p class="rs description">Nam nec sem ac risus congue varius. Maecenas interdum ipsum tempor ipsum fringilla eu vehicula urna vehicula.</p>
                                            </div>
                                        </div><!--end: .other-post-item -->
                                        <div class="media other-post-item">
                                            <a href="#" class="thumb-left">
                                                <img src="/images/ex/th-90x90-4.jpg" alt="$TITLE">
                                            </a>
                                            <div class="media-body">
                                                <h4 class="rs title-other-post">
                                                    <a href="#" class="be-fc-orange fw-b">John Doe</a>
                                                </h4>
                                                <p class="rs fc-gray time-post pb10">posted 5 days ago</p>
                                                <p class="rs description">Nam nec sem ac risus congue varius. Maecenas interdum ipsum tempor ipsum fringilla eu vehicula urna vehicula.</p>
                                            </div>
                                        </div><!--end: .other-post-item -->
                                        <div class="media other-post-item">
                                            <a href="#" class="thumb-left">
                                                <img src="/images/ex/th-90x90-1.jpg" alt="$TITLE">
                                            </a>
                                            <div class="media-body">
                                                <h4 class="rs title-other-post">
                                                    <a href="#" class="be-fc-orange fw-b">John Doe</a>
                                                </h4>
                                                <p class="rs fc-gray time-post pb10">posted 5 days ago</p>
                                                <p class="rs description">Nam nec sem ac risus congue varius. Maecenas interdum ipsum tempor ipsum fringilla eu vehicula urna vehicula.</p>
                                            </div>
                                        </div><!--end: .other-post-item -->
                                    </div>
                                </div>
                            </div><!--end: .tab-pane(Updates) -->
                        </div>
                        <div>
                            <h3 class="rs alternate-tab accordion-label">Backers (270)</h3>
                            <div class="tab-pane accordion-content">
                                <div class="tab-pane-inside">
                                    <div class="project-author pb20">
                                        <div class="media">
                                            <a href="#" class="thumb-left">
                                                <img src="/images/ex/th-90x90-1.jpg" alt="$USER_NAME"/>
                                            </a>
                                            <div class="media-body">
                                                <h4 class="rs pb10"><a href="#" class="be-fc-orange fw-b">John Doe</a></h4>
                                                <p class="rs">Chicago, IL</p>
                                                <p class="rs fc-gray">5 projects</p>
                                            </div>
                                        </div>
                                    </div><!--end: .project-author -->
                                    <div class="project-author pb20">
                                        <div class="media">
                                            <a href="#" class="thumb-left">
                                                <img src="/images/ex/th-90x90-1.jpg" alt="$USER_NAME"/>
                                            </a>
                                            <div class="media-body">
                                                <h4 class="rs pb10"><a href="#" class="be-fc-orange fw-b">John Doe</a></h4>
                                                <p class="rs">Chicago, IL</p>
                                                <p class="rs fc-gray">5 projects</p>
                                            </div>
                                        </div>
                                    </div><!--end: .project-author -->
                                </div>
                                <div class="project-btn-action">
                                    <a class="btn btn-red" href="#">Ask a question</a>
                                    <a class="btn btn-black" href="#">Report this project</a>
                                </div>
                            </div><!--end: .tab-pane(Backers) -->
                        </div>
                        <div>
                            <h3 class="rs active alternate-tab accordion-label">Comments (2)</h3>
                            <div class="tab-pane accordion-content">
                                <div class="box-list-comment">
                                    <div class="media comment-item">
                                        <a href="#" class="thumb-left">
                                            <img src="/images/ex/th-90x90-1.jpg" alt="$TITLE">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="rs comment-author">
                                                <a href="#" class="be-fc-orange fw-b">John Doe</a>
                                                <span class="fc-gray">say:</span>
                                            </h4>
                                            <p class="rs comment-content"> Fusce tellus. Sed metus augue, convallis et, vehicula ut, pulvinar eu, ante. Integer orci tellus, tristique vitae, consequat nec, porta vel, lectus</p>
                                            <p class="rs time-post">5 days ago</p>
                                        </div>
                                    </div><!--end: .comment-item -->
                                    <div class="media comment-item">
                                        <a href="#" class="thumb-left">
                                            <img src="/images/ex/th-90x90-2.jpg" alt="$TITLE">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="rs comment-author">
                                                <a href="#" class="be-fc-orange fw-b">Eminem</a>
                                                <span class="fc-gray">say:</span>
                                            </h4>
                                            <p class="rs comment-content">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere felis nec tortor. Pellentesque faucibus. Ut accumsan ultricies elit.</p>
                                            <p class="rs time-post">5 days ago</p>
                                        </div>
                                    </div><!--end: .comment-item -->
                                    <div class="media comment-item lv2">
                                        <a href="#" class="thumb-left">
                                            <img src="/images/ex/th-90x90-3.jpg" alt="$TITLE">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="rs comment-author">
                                                <a href="#" class="be-fc-orange fw-b">Snoop Dogg</a>
                                                <span class="fc-gray">say:</span>
                                            </h4>
                                            <p class="rs comment-content">Nam nec sem ac risus congue varius. Maecenas interdum ipsum tempor ipsum fringilla eu vehicula urna vehicula.</p>
                                            <p class="rs time-post">5 days ago</p>
                                        </div>
                                    </div><!--end: .comment-item -->
                                    <div class="media comment-item lv2">
                                        <a href="#" class="thumb-left">
                                            <img src="/images/ex/th-90x90-4.jpg" alt="$TITLE">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="rs comment-author">
                                                <a href="#" class="be-fc-orange fw-b">Obama</a>
                                                <span class="fc-gray">say:</span>
                                            </h4>
                                            <p class="rs comment-content">Curabitur vel dolor ultrices ipsum dictum tristique. Praesent vitae lacus. Ut velit enim, vestibulum non, fermentum nec,</p>
                                            <p class="rs time-post">5 days ago</p>
                                        </div>
                                    </div><!--end: .comment-item -->
                                    <div class="media comment-item lv3">
                                        <a href="#" class="thumb-left">
                                            <img src="/images/no-avatar.png" alt="$TITLE">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="rs comment-author">
                                                <a href="#" class="be-fc-orange fw-b">Mark Lenon</a>
                                                <span class="fc-gray">say:</span>
                                            </h4>
                                            <p class="rs comment-content">Nam nec sem ac risus congue varius. Maecenas interdum ipsum tempor ipsum fringilla eu vehicula urna vehicula.</p>
                                            <p class="rs time-post">5 days ago</p>
                                        </div>
                                    </div><!--end: .comment-item -->
                                    <div class="media comment-item">
                                        <a href="#" class="thumb-left">
                                            <img src="/images/ex/th-90x90-1.jpg" alt="$TITLE">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="rs comment-author">
                                                <a href="#" class="be-fc-orange fw-b">Dr. Dre</a>
                                                <span class="fc-gray">say:</span>
                                            </h4>
                                            <p class="rs comment-content"> Morbi eget arcu. Morbi porta, libero id ullamcorper nonummy, nibh ligula pulvinar metus, eget consectetuer augue nisi quis lacus. Ut ac mi quis lacus mollis aliquam. Curabitur iaculis tempus eros. Curabitur vel mi sit amet magna malesuada ultrices</p>
                                            <p class="rs time-post">5 days ago</p>
                                        </div>
                                    </div><!--end: .comment-item -->
                                </div>
                            </div><!--end: .tab-pane(Comments) -->
                        </div>
                      </div>
                </div><!--end: .project-tab-detail -->
            </div>
        </div><!--end: .content -->
        <div class="sidebar grid_4">
        
        <div class="project-runtime">
        
        <div class="project-author">
          
                        <a href="/"><img src="/images/find.png" alt="Hire Remote"/></a>
         </div>
         
                <div class="box-gray">
                     <div class="project-detail">
                <div class="project-tab-detail tabbable accordion">
                     
                    <div class="tab-content">
                        <div>
                            <h3 class="rs alternate-tab accordion-label">Find Skillful people</h3>
                            <div class="tab-pane accordion-content active">
                                    <div class="tab_wrapper">
                                <div class="for_sale tab_block tab_block_1 active"> 
                                <form action="search-results.html" />
                                <div> 
                                <input placeholder="Search a term" type="text" />  <input type="submit" value="" />
                                </div> 
                                </form>
                                </div>  
                            </div>
                            </div><!--end: .tab-pane -->
                        </div>
                        
                        
                      </div>
                </div><!--end: .project-tab-detail -->
            </div>
                </div>
            </div>
            
            
            
            <div class="project-runtime">
                <div class="box-gray">
                    <div class="project-date clearfix">
                        <i class="icon iCalendar"></i>
                        <span class="val"><span class="fw-b">Launched: </span>Apr 8, 2013</span>
                    </div>
                    <div class="project-date clearfix">
                        <i class="icon iClock"></i>
                        <span class="val"><span class="fw-b">Funding ends: </span>Apr 8, 2013</span>
                    </div>
                    <a class="btn btn-green btn-buck-project" href="#">
            			<span class="lbl sys_show_popup_login">Apply</span>
                        <span class="desc">$1 minimum pledge</span>
                    </a>
                    <p class="rs description">This project will only be funded if at least $15,000 is pledged by Wednesday May 8, 2:05pm EDT.</p>
                </div>
            </div><!--end: .project-runtime -->
            <div class="project-author">
                <div class="box-gray">
                    <h3 class="title-box">Project by</h3>
                    <div class="media">
                        <a href="#" class="thumb-left">
                            <img src="/images/ex/th-90x90-1.jpg" alt="$USER_NAME"/>
                        </a>
                        <div class="media-body">
                            <h4 class="rs pb10"><a href="#" class="be-fc-orange fw-b">John Doe</a></h4>
                            <p class="rs">Chicago, IL</p>
                            <p class="rs fc-gray">5 projects</p>
                        </div>
                    </div>
                    <div class="author-action">
                        <a class="btn btn-red" href="#">Contact me</a>
                        <a class="btn btn-white" href="#">See full bio</a>
                    </div>
                </div>
            </div><!--end: .project-author -->
            <div class="clear clear-2col"></div>
            <div class="wrap-nav-pledge">
                <ul class="rs nav nav-pledge accordion">
                    <li>
                        <div class=" pledge-label accordion-label clearfix">
                            <i class="icon iPlugGray"></i>
                            <span class="pledge-amount">Pledge $17 or more</span>
                            <span class="count-val">(12 of 31)</span>
                        </div>
                        <div class=" pledge-content accordion-content">
                            <div class="pledge-detail">
                                <p class="rs pledge-description">Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
                                <p class="rs fw-b pb20">Ocupated (2 of 10)</p>
                                <p class="rs"><span class="fw-b">Estimated delivery:</span> Aug 2013</p>
                                <p class="rs fw-thin fc-gray pb20">Ships within the US only</p>
                                <p class="rs ta-c"><a class="btn big btn-red" href="#">Buck this project</a></p>
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        <div class=" pledge-label accordion-label clearfix">
                            <i class="icon iPlugGray"></i>
                            <span class="pledge-amount">Pledge $32 or more</span>
                            <span class="count-val">(42 of 111)</span>
                        </div>
                        <div class=" pledge-content accordion-content">
                            <div class="pledge-detail">
                                <p class="rs pledge-description">Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
                                <p class="rs fw-b pb20">Ocupated (2 of 10)</p>
                                <p class="rs"><span class="fw-b">Estimated delivery:</span> Aug 2013</p>
                                <p class="rs fw-thin fc-gray pb20">Ships within the US only</p>
                                <p class="rs ta-c"><a class="btn big btn-red" href="#">Buck this project</a></p>
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        <div class="active pledge-label accordion-label clearfix">
                            <i class="icon iPlugGray"></i>
                            <span class="pledge-amount">Pledge $50 or more</span>
                            <span class="count-val">(7 of 13)</span>
                        </div>
                        <div class="active pledge-content accordion-content">
                            <div class="pledge-detail">
                                <p class="rs pledge-description">Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
                                <p class="rs fw-b pb20">Ocupated (2 of 10)</p>
                                <p class="rs"><span class="fw-b">Estimated delivery:</span> Aug 2013</p>
                                <p class="rs fw-thin fc-gray pb20">Ships within the US only</p>
                                <p class="rs ta-c"><a class="btn big btn-red" href="#">Buck this project</a></p>
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        <div class=" pledge-label accordion-label clearfix">
                            <i class="icon iPlugGray"></i>
                            <span class="pledge-amount">Pledge $54 or more</span>
                            <span class="count-val">(2 of 10)</span>
                        </div>
                        <div class=" pledge-content accordion-content">
                            <div class="pledge-detail">
                                <p class="rs pledge-description">Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
                                <p class="rs fw-b pb20">Ocupated (12 of 30)</p>
                                <p class="rs"><span class="fw-b">Estimated delivery:</span> Aug 2013</p>
                                <p class="rs fw-thin fc-gray pb20">Ships within the US only</p>
                                <p class="rs ta-c"><a class="btn big btn-red" href="#">Buck this project</a></p>
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        <div class=" pledge-label accordion-label clearfix">
                            <i class="icon iPlugGray"></i>
                            <span class="pledge-amount">Pledge $130 or more</span>
                            <span class="count-val">(23 of 47)</span>
                        </div>
                        <div class=" pledge-content accordion-content">
                            <div class="pledge-detail">
                                <p class="rs pledge-description">Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
                                <p class="rs fw-b pb20">Ocupated (2 of 10)</p>
                                <p class="rs"><span class="fw-b">Estimated delivery:</span> Aug 2013</p>
                                <p class="rs fw-thin fc-gray pb20">Ships within the US only</p>
                                <p class="rs ta-c"><a class="btn big btn-red" href="#">Buck this project</a></p>
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                    <li>
                        <div class=" pledge-label accordion-label clearfix">
                            <i class="icon iPlugGray"></i>
                            <span class="pledge-amount">Pledge $110 or more</span>
                            <span class="count-val">(23 of 39)</span>
                        </div>
                        <div class=" pledge-content accordion-content">
                            <div class="pledge-detail">
                                <p class="rs pledge-description">Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
                                <p class="rs fw-b pb20">Ocupated (2 of 10)</p>
                                <p class="rs"><span class="fw-b">Estimated delivery:</span> Aug 2013</p>
                                <p class="rs fw-thin fc-gray pb20">Ships within the US only</p>
                                <p class="rs ta-c"><a class="btn big btn-red" href="#">Buck this project</a></p>
                            </div>
                        </div>
                    </li><!--end: pledge-item -->
                </ul>
            </div><!--end: .wrap-nav-pledge -->
        </div><!--end: .sidebar -->
        <div class="clear"></div>
    </div>
  