
<head>
	<meta charset="utf-8"/>
	<title>Dashboard I Admin Panel</title>
	
	<link rel="stylesheet" href="css/layout.css" type="text/css" media="screen" />
    <style>
		.cl-status {
			display: none;
			float: right;
			color: #004000;
		}
	</style>	
    
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<!--
	<script src="js/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="js/hideshow.js" type="text/javascript"></script>
	<script src="js/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="js/jquery.equalHeight.js"></script>
    <script type="text/javascript" src="js/organictabs.jquery.js"></script>
	-->
	<script type="text/javascript" language="javascript">
	$(document).ready(function() 
    	{ 
      	  $(".tablesorter").tablesorter(); 
   	 } 
	);
	$(document).ready(function() {

	//When page loads...
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content

	//On Click Event
	$("ul.tabs li").click(function() {

		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content

		var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active ID content
		return false;
	});

});
    </script>
    <script type="text/javascript" language="javascript">
    $(function(){
        $('.column').equalHeight();
    });
</script>

<script>
        $(function() {
    
            $("#first").organicTabs();
            
            $("#second").organicTabs({
                "speed": 150
            });
    
        });
    </script>
<script type="text/javascript" language="javascript">
	addtocart = function(domain_name, id) {
		var url = "<?php echo $this->url(array('controller' => 'wwd', 'action' => 'addtocart'));?>";
		$.ajax({	
			type: 'POST',
			url: url,
			data: {domain: domain_name}
		}).done(function() { 
			$('#item_' + id).hide();
			$('#status_' + id).show();
		});	
		return false;
	}
</script>	 
	
</head>

	
	<!-- end of sidebar -->
<div class="content_block">	
	<section id="main_domaincheck">

<?php if(is_null($this->result)): ?>
        <div id="second">
    		<ul class="nav">
                <li class="nav-one"><a href="#featured2" class="current">New Domains</a></li>
                <li class="nav-two last"><a href="#core2">Domain Transfer</a></li>      
            </ul>
    		
    		<div class="list-wrap">
    		
    			<ul id="featured2">
    				
                    <section id="searchbar">
<form class="form-wrapper cf" method="post" action="<?php echo $this->url(array('controller' => 'wwd', 'action' => 'index')); ?>">
	<input type="text" placeholder="Search your desired domain name .." name="domain" required autofocus>
    	<select name="extension">
            <option value=".com">.com</option>
            <option value=".info" >.info</option>
            <option value=".net" >.net</option> 
            <option value=".me" >.me</option>
            <option value=".org" >.org</option>
            <option value=".biz" >.biz</option> 
            <option value=".com.co" >.com.co</option>
            <option value=".net.co" >.net.co</option>
            <option value=".nom.co" >.nom.co</option>
            <option value=".mobi" >.mobi</option>
            <option value=".mx" >.mx</option>
            <option value=".com.es" >.com.es</option>
            <option value=".ws" >.ws</option>
            <option value=".us" >.us</option>
            <option value=".nom.es" >.nom.es</option>
            <option value=".es" >.es</option>
            <option value=".org.es" >.org.es</option>
            <option value=".nl" >.nl</option>
            <option value=".in" >.in</option>
            <option value=".com.mx" >.com.mx</option>
            <option value=".bz" >.bz</option>
            <option value=".com.bz" >.com.bz</option>
            <option value=".co.in" >.co.in</option>
            <option value=".firm.in" >.firm.in</option>
            <option value=".gen.in" >.gen.in</option>
            <option value=".ind.in" >ind.in</option>
            <option value=".net.in" >.net.in</option>
            <option value=".org.in" >.org.in</option>
            <option value=".tv" >.tv</option>
		</select>
        <input type="submit" name="search" value="Search"/>
</form>
	</section>
                    
                    
    			</ul>
        		 
        		 <ul id="core2" class="hide">
                    <section id="searchbar">
<form class="form-wrapper cf" method="post" action="<?php echo  $this->url(array('controller' => 'wwd', 'action' => 'index')); ?>">
	<input type="text" placeholder="Search your desired domain name .." name="domain" required autofocus>
    	<select name="extension">
            <option value=".com">.com</option>
            <option value=".info" >.info</option>
            <option value=".net" >.net</option> 
            <option value=".me" >.me</option>
            <option value=".org" >.org</option>
            <option value=".biz" >.biz</option> 
            <option value=".com.co" >.com.co</option>
            <option value=".net.co" >.net.co</option>
            <option value=".nom.co" >.nom.co</option>
            <option value=".mobi" >.mobi</option>
            <option value=".mx" >.mx</option>
            <option value=".com.es" >.com.es</option>
            <option value=".ws" >.ws</option>
            <option value=".us" >.us</option>
            <option value=".nom.es" >.nom.es</option>
            <option value=".es" >.es</option>
            <option value=".org.es" >.org.es</option>
            <option value=".nl" >.nl</option>
            <option value=".in" >.in</option>
            <option value=".com.mx" >.com.mx</option>
            <option value=".bz" >.bz</option>
            <option value=".com.bz" >.com.bz</option>
            <option value=".co.in" >.co.in</option>
            <option value=".firm.in" >.firm.in</option>
            <option value=".gen.in" >.gen.in</option>
            <option value=".ind.in" >ind.in</option>
            <option value=".net.in" >.net.in</option>
            <option value=".org.in" >.org.in</option>
            <option value=".tv" >.tv</option>
		</select>
 
        <input type="submit" name="search" value="Transfer"/>  
</form>

	</section>
        		 </ul>
    		 </div> <!-- END List Wrap -->
		 </div>
    
    <article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Domain Prices</h3>
		<ul class="tabs">
   			<li><a href="#tab1">General Domains</a></li>
    		<li><a href="#tab2">Internanal Domains</a></li>
		</ul>
		</header>

		<div class="tab_container">
			<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					
    				<th width="15%">Per Year Pricing</th> 
    				<th width="14%">1 Year</th> 
    				<th width="15%">2 Years</th> 
                    <th width="15%">3 Years</th> 
    				<th width="15%">5 Years</th> 
    				<th width="20%">10 Years</th> 
				</tr> 
			</thead> 
			<tbody> 
				<tr> 
   					 
    				<td>.COM</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td> 
				</tr> 
				<tr> 
   					 
    				<td>.CO</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
				<tr> 
   					 
    				<td>.INFO</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr> 
				<tr> 
   					 
    				<td>.NET</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
				<tr> 
   					 
    				<td>.ORG</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.ME</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>  
                <tr> 
   					 
    				<td>.MOBI</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr> 
                <tr> 
   					 
    				<td>.US</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr> 
                <tr> 
   					 
    				<td>.BIZ</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr> 
                <tr> 
   					 
    				<td>.CA</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.CC</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.XXX</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.TV</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.WS</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.ASIA</td> 
    				<td>$19.99*</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr> 
			</tbody> 
			</table>
			</div><!-- end of #tab1 -->
			
			<div id="tab2" class="tab_content">
			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					
    				<th width="15%">Per Year Pricing</th> 
    				<th width="14%">1 Year</th> 
    				<th width="15%">2 Years</th> 
                    <th width="15%">3 Years</th> 
    				<th width="15%">5 Years</th> 
    				<th width="20%">10 Years</th> 
				</tr> 
			</thead> 
			<tbody> 
				<tr> 
   					 
    				<td>.us</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td> 
				</tr> 
				<tr> 
   					 
    				<td>.ca</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
				<tr> 
   					 
    				<td>.mx</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr> 
				<tr> 
   					 
    				<td>.com.mx</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
				<tr> 
   					 
    				<td>.ag</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>  
                <tr> 
   					 
    				<td>.com.ag</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.net.ag</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.org.ag</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.org.ag</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.bz</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.com.bz</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                <tr> 
   					 
    				<td>.gs</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
                 <tr> 
   					 
    				<td>.ms</td> 
    				<td>$12.99</td> 
    				<td>$21.49</td> 
    				<td>$24.33</td> 
                    <td>$26.59</td> 
                    <td>--</td>  
				</tr>
			</tbody> 
			</table>

			</div><!-- end of #tab2 -->
			
		</div><!-- end of .tab_container -->
		
		</article>

<?php else: ?> 
        <div id="second">		
    		<ul class="nav">
                <li class="nav-one"><a href="#featured2" class="current">New Domains</a></li>
                <li class="nav-two last"><a href="#core2">Domain Transfer</a></li>  
            </ul>
    		
    		<div class="list-wrap_2">
    			<ul id="featured2">
    				
                    <section id="searchbar">
<form class="form-wrapper cf" method="post" action="<?php echo $this->url(array('controller' => 'wwd', 'action' => 'index')) ?>">
	<input type="text" placeholder="Search your desired domain name .." name="domain" required autofocus>
    	<select name="extension">
            <option value=".com">.com</option>
            <option value=".info" >.info</option>
            <option value=".net" >.net</option> 
            <option value=".me" >.me</option>
            <option value=".org" >.org</option>
            <option value=".biz" >.biz</option> 
            <option value=".com.co" >.com.co</option>
            <option value=".net.co" >.net.co</option>
            <option value=".nom.co" >.nom.co</option>
            <option value=".mobi" >.mobi</option>
            <option value=".mx" >.mx</option>
            <option value=".com.es" >.com.es</option>
            <option value=".ws" >.ws</option>
            <option value=".us" >.us</option>
            <option value=".nom.es" >.nom.es</option>
            <option value=".es" >.es</option>
            <option value=".org.es" >.org.es</option>
            <option value=".nl" >.nl</option>
            <option value=".in" >.in</option>
            <option value=".com.mx" >.com.mx</option>
            <option value=".bz" >.bz</option>
            <option value=".com.bz" >.com.bz</option>
            <option value=".co.in" >.co.in</option>
            <option value=".firm.in" >.firm.in</option>
            <option value=".gen.in" >.gen.in</option>
            <option value=".ind.in" >ind.in</option>
            <option value=".net.in" >.net.in</option>
            <option value=".org.in" >.org.in</option>
            <option value=".tv" >.tv</option>
		</select>
        <input type="submit" name="search" value="Search"/>
</form>

<?php 
    $avilable = current($this->result);
    if($avilable !== '0') {
        $string = '<p>is avilable</p>';
    } else {
        $string = '<p>is taken</p>';
    }
?>
<article><b><?php echo key($this->result); ?> </b> <p><?php echo $string; ?></p>
    <?php if($avilable !== '0'): ?>
	<a id="item_x" ref="" onclick="addtocart('<?php echo key($this->result);?>', 'x'); return false;" title="add to cart">add to cart</a><span id="status_x" class="cl-status">Added</span> 
    <?php endif; ?>    
</article>
</section>     
    			</ul>
        		 <ul id="core2" class="hide">
                    <section id="searchbar">
<form class="form-wrapper cf" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
	<input type="text" placeholder="Search your desired domain name .." name="domain" required autofocus>
    	<select name="extension">
            <option value=".com">.com</option>
            <option value=".info" >.info</option>
            <option value=".net" >.net</option> 
            <option value=".me" >.me</option>
            <option value=".org" >.org</option>
            <option value=".biz" >.biz</option> 
            <option value=".com.co" >.com.co</option>
            <option value=".net.co" >.net.co</option>
            <option value=".nom.co" >.nom.co</option>
            <option value=".mobi" >.mobi</option>
            <option value=".mx" >.mx</option>
            <option value=".com.es" >.com.es</option>
            <option value=".ws" >.ws</option>
            <option value=".us" >.us</option>
            <option value=".nom.es" >.nom.es</option>
            <option value=".es" >.es</option>
            <option value=".org.es" >.org.es</option>
            <option value=".nl" >.nl</option>
            <option value=".in" >.in</option>
            <option value=".com.mx" >.com.mx</option>
            <option value=".bz" >.bz</option>
            <option value=".com.bz" >.com.bz</option>
            <option value=".co.in" >.co.in</option>
            <option value=".firm.in" >.firm.in</option>
            <option value=".gen.in" >.gen.in</option>
            <option value=".ind.in" >ind.in</option>
            <option value=".net.in" >.net.in</option>
            <option value=".org.in" >.org.in</option>
            <option value=".tv" >.tv</option>
		</select>
        <input type="submit" name="search" value="Transfer"/>  
</form>
	</section>
        		 </ul>	 
    		 </div> <!-- END List Wrap --> 
		 </div>
<section class="encard">

<article>
<h2>Other Options That You Might be Interested In</h2>
	<?php $i = 0;?>
    <?php foreach ($this->suggested_result as $key => $value): ?>
        <div class="otheroptions">
            <?php echo $key; ?>
				<?php if ($value !== '0'):?>
					is <b>available</b><a id="item_<?php echo $i?>" ref="" onclick="addtocart('<?php echo $key?>', '<?php echo $i?>'); return false;" title="add to cart">add to cart</a><span id="status_<?php echo $i ?>" class="cl-status">Added</span>
					<?php $i++ ?>
				<?php else: ?>
					is <b>taken </b>
				<?php endif; ?>
        </div>
    <?php endforeach; ?>
	<a href="<?php echo $this->url(array('controller' => 'wwd', 'action' => 'orderdomain'))?>" title="order domain">ORDER DOMAINS</a>
</article>

<article id="recent">
        <h2>Your Recent Searches</h2>
        <?php 
            if(isset($this->rs_search) && count($this->rs_search)) {
                echo '<ul>';
                    foreach ($this->rs_search as $value) {
                        printf('<li>%s</li>', $value);
                    }
                echo '</ul>';
            }
        ?>
</article>
    
</section>
	<?php endif; ?>

		</section>
	</div>	

