
 <section id="content" class="container clearfix">

	<header class="page-header">
		
			<h1 class="page-title">Manage Your hot words here
            
             </h1>
			
		</header><!-- end .page-header -->
	
	<section id="main">
    <article class="entry single clearfix">
    
<h3 class="title"><a href="#"></a></h3>
				<h6><a href="#">Please add a new hot word here</a></h6>
                
                

<form name="addhotword" action="<?php echo $this->baseurl; ?>/dashboard/hotword/add/" method="post" >
<table id="customers">
<tbody><tr>
<th>Please Enter hot word Name with priority</th>
</tr>
<tr >
    <td style="
padding:20px;"><p><input name="hotword" type="text" />
 Priority: 
 <select name="priority">
	<option value=1>
		1
	</option>
 </select>
</p><p><input type="submit" name="Add Word" value="Done"/></p></td> 
</tr>	
</tbody>	
</table>    
</form>
 
			</div>


			<!-- end .entry-body -->

			<!-- end .entry-meta -->
            
		</article>
        
       <!-- <p class="info"><strong>Services : You can View the following logs for <strong><?php echo $this->childName; ?> </strong></p> -->
        
 

	</section><!-- end #main -->

	<aside id="sidebar">
    
    
                    
                    <div class="widget">
                    
		<h6 class="widget-title">Twitter Feed</h6>
						<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
                        <script>
                        new TWTR.Widget({
                          version: 2,
                          type: 'profile',
                          rpp: 3,
                          interval: 30000,
                          width:'auto',
                          height: 220,
                          theme: {
                            shell: {
                              background: '#6e6e6e',
                              color: '#ffffff'
                            },
                            tweets: {
                              background: '#575457',
                              color: '#ffffff',
                              links: '#a3a3a3'
                            }
                          },
                          features: {
                            scrollbar: false,
                            loop: false,
                            live: false,
                            behavior: 'all'
                          }
                        }).render().setUser('winwinhost').start();
                        </script>

		</div>


	</aside><!-- end #sidebar -->
	
</section>