

 <section id="content" class="container clearfix">

	<header class="page-header">
		
			<h1 class="page-title">Manage Your HOT word here
            
             </h1>
			
		</header><!-- end .page-header -->
	
	<section id="main">
    <article class="entry single clearfix">
    
<h3 class="title"><a href="#"></a></h3>
				<h6><a href="#">You can Add , Delete and Edit a HOT word from here</a></h6>
                
                
<table id="customers">
<tbody><tr>
<th>ID</th>
<th>Module name</th>
<th>Priority</th>
<th>Hot word</th>
<th>Action</th>
</tr>
<?php foreach($this->data as $key => $data): ?>  
<tr <?php if ($key %2 == 0) echo "class=\"alt\"";?>>
    <td><?php  echo $data['id']; ?>  </td>
	<td style="text-transform:uppercase"><strong><?php echo $data['module']; ?><strong></td>
	<td><?php echo $data['priority']; ?></td>
    <td><?php echo $data['word']; ?></td>
	<td><a style="margin-left:10px;" class="button"  href="<?php  echo $this->baseurl; ?>/dashboard/hotword/edit/id/<?php echo $data['id']; ?>">Edit</a>&nbsp; 
	<a style="margin-left:10px;" class="button"  href="<?php echo $this->baseurl; ?>/dashboard/hotword/delete/id/<?php echo $data['id']; ?>">Delete</a> 
	</td>
</tr>	
<?php endforeach; ?>
</tbody>	
</table>


			

			</div>


			<!-- end .entry-body -->

			<!-- end .entry-meta -->
            
		</article>
        
       <!-- <p class="info"><strong>Services : You can View the following logs for <strong><?php echo $this->childName; ?> </strong></p> -->
        
        
        
        
        

	</section><!-- end #main -->

	<aside id="sidebar">
    
    <div class="widget">
                   
                            <div class="infobox">
                    
                                <h3>Want to Add a Hot word?</h3>
                    
                                <p><a class="button" href="<?php echo $this->baseurl; ?>/dashboard/hotword/add">Click Here </a></p>
                    
                            </div><!-- end .infobox -->
                    </div>
                    
                    <div class="widget">
                    
		<h6 class="widget-title">Twitter Feed</h6>
						<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
                        <script>
                        new TWTR.Widget({
                          version: 2,
                          type: 'profile',
                          rpp: 3,
                          interval: 30000,
                          width:'auto',
                          height: 220,
                          theme: {
                            shell: {
                              background: '#6e6e6e',
                              color: '#ffffff'
                            },
                            tweets: {
                              background: '#575457',
                              color: '#ffffff',
                              links: '#a3a3a3'
                            }
                          },
                          features: {
                            scrollbar: false,
                            loop: false,
                            live: false,
                            behavior: 'all'
                          }
                        }).render().setUser('winwinhost').start();
                        </script>

		</div>


	</aside><!-- end #sidebar -->
	
</section>
 