
<!-- <?php $role = Zend_Auth::getInstance()->getIdentity()->member_role; ?> -->

<!--

	 	  <?php foreach($this->data as $dd): ?> 
 
		  <?php endforeach; ?>
 
	 36.44090201 -115.5987506	
	  -->
 
    
    <?php foreach($this->datachild as $datachild): ?> 	

<?php endforeach; ?>


	</head>

<section id="content" class="container clearfix">

	<header class="page-header">
		
			


    
    <h1 class="page-title">Web Browsing History of 
			
			<?php echo $this->childName; ?> 
            
             </h1>
			
		</header><!-- end .page-header -->
	
	<section id="main">
    <article class="entry single clearfix">
    
				<h3 class="title"><a href="#">Web Browsing History of <?php echo $this->childName; ?></a></h3>
				<h5><a href="#"><!-- Drag the pin above in map anywhere on the map to know the approximate address of that point.--></a></h5>

<table id="customers">
<tbody><tr>
<th>Date/Time</th>
 
<th>URL</th> 
</tr>

<?php foreach($this->data as $dd): ?> 
<tr>
    
	<td style="width:50px;  height:auto; padding:5px; " ><?php echo $dd['url'] ?></td>
    
    <!-- <td style="width:150px; max-width:150px; height:auto; padding:5px;"><?php echo $dd['title'] ?></td> -->
    
	<td style="width:150px;  height:auto; "><?php echo $dd['date_time'] ?></td>  
</tr>	

<?php endforeach; ?>

</tbody>	

</table> 
			<!-- end .entry-body -->

			<!-- end .entry-meta --> 
            
            <h5> Please select the date in fields below to view call-log of Past days</h5> 
            
            <form name="location" action="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>" method="post" >
            <table id="customers">
            <tbody>
            <tr>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Action</th>
            </tr>
            <tr>
            
                <td><input style="width:80%; max-width:90;" type="text" id="datepicker3" name="start_date" width="100%" value="Select" /></td>
                <td><input style="width:80%; max-width:90;" type="text" id="datepicker4" name="end_date" width="100%" value="Select" /></td>	
                <td><input style="width:80%; max-width:90;" type="submit" value="Go"/></td>
            </tr>
            </tbody>	
            </table> 
            </form>
            
            
            
		</article>
        
       <p class="info"><strong>Services :</strong> You can also view the following logs for <strong><?php echo $this->childName; ?> </strong></p>
        
        
        <?php if ($role == 2 ): ?>
    
    
    <section id="portfolio-items" class="clearfix">

        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-location.png" alt="">
        
                    <a class="project-meta" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">
                        <h5 class="title">Latest Location</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
	
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-tracks.png" alt="">
        
                    
                    <a class="project-meta" title="Recent Movement Track" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Movement Tracks</h5>
                    </a>
                    
                 </article>
                 
                 <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a class="project-meta" title="view Safety Maps" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Safty Maps</h5>
                    </a>
                    
                 </article>
                 
                 <!-- end .one-fourth (Altered) -->
       <!-- <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a href="#" class="project-meta">
                        <h5 class="title">Safty Map</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                <!-- <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-surfing.png" alt="">
        
                    <a href="#" class="project-meta">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 
                 
                 
                 <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-surfing.png" alt="">
        
        
                    <a class="project-meta" title="Web Browsing History of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 
                 
                 
       <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">Phone Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">

                        <h5 class="title">Email Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
     <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-calllog.png" alt="">
        
                    <a class="project-meta" title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">In-Coming/Outgoing Call Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <!-- end .one-fourth (Altered) -->
        
        
         <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-texts.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">In-Coming/Outing SMS Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-video.png" alt="">
        
                    <a class="project-meta" title="View Video files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Video Track List</h5>
                    </a>
                    
                 </article>
                 
                 
              
                 
              <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-audio.png" alt="">
        
                    <a class="project-meta" title="Listen Audio files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Audio Files</h5>
                    </a>
                    
                 </article>
                 
                 
        
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-multimedia.png" alt="">
        
                   <a class="project-meta" title="View Image files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Image Files List</h5>
                    </a>
                    
                 </article>
                 

		

	</section>
    
    
    <?php elseif ($role == 3 ): ?>
    
    <section id="portfolio-items" class="clearfix">

        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-location.png" alt="">
        
                    <a class="project-meta" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">
                        <h5 class="title">Latest Location</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
	
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-tracks.png" alt="">
        
                    
                    <a class="project-meta" title="Recent Movement Track" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Movement Tracks</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 <!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a class="project-meta" title="view Safety Maps" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Safty Maps</h5>
                    </a>
                    
                 </article>

                 
                 
                 <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-surfing.png" alt="">
        
        
                    <a class="project-meta" title="Web Browsing History of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 
                 
                 
       <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">Phone Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Email Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
     <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-calllog.png" alt="">
        
                    <a class="project-meta" title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">In-Coming/Outgoing Call Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <!-- end .one-fourth (Altered) -->
        
        
         <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-texts.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">In-Coming/Outing SMS Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 
                 
                  <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-hotwords.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'showhword','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">SMS including Hot Words</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->

                 
        <!-- end .one-fourth (Altered) -->
      <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-video.png" alt="">
        
                    <a class="project-meta" title="View Video files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Video Track List</h5>
                    </a>
                    
                 </article>
                 
                 
              
                 
              <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-audio.png" alt="">
        
                    <a class="project-meta" title="Listen Audio files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Audio Files</h5>
                    </a>
                    
                 </article>
                 
                 
        
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-multimedia.png" alt="">
        
                   <a class="project-meta" title="View Image files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Image Files List</h5>
                    </a>
                    
                 </article>
                 

		

	</section>
    
    
    <?php elseif ($role == 5 ): ?>
    
    <section id="portfolio-items" class="clearfix">

        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-location.png" alt="">
        
                    <a class="project-meta" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">
                        <h5 class="title">Latest Location</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
	
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-tracks.png" alt="">
        
                    
                    <a class="project-meta" title="Recent Movement Track" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Movement Tracks</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 <!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-dangers.png" alt="">
        
                    <a class="project-meta" title="view Safety Maps" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Safty Maps</h5>
                    </a>
                    
                 </article>

                 
                 
                 <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-surfing.png" alt="">
        
        
                    <a class="project-meta" title="Web Browsing History of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Web Browsing History</h5>
                    </a>
                    
                 </article>
                 
                 
                 
                 
                 
                 
       <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">Phone Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-contacts.png" alt="">
        
                    <a class="project-meta" title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Email Contacts</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
     <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-calllog.png" alt="">
        
                    <a class="project-meta" title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>"> 
                        <h5 class="title">In-Coming/Outgoing Call Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
        <!-- end .one-fourth (Altered) -->
        
        
         <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-texts.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">In-Coming/Outing SMS Log</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->
                 
                 
                 
                  <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-hotwords.png" alt="">
        
                    <a class="project-meta" title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'showhword','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">SMS including Hot Words</h5>
                    </a>
                    
                 </article><!-- end .one-fourth (Altered) -->

                 
        <!-- end .one-fourth (Altered) -->
      <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-video.png" alt="">
        
                    <a class="project-meta" title="View Video files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Video Track List</h5>
                    </a>
                    
                 </article>
                 
                 
              
                 
              <article class="one-fifth" data-categories="illustration design">
        

                        <img src="/images/icon-post-format-audio.png" alt="">
        
                    <a class="project-meta" title="Listen Audio files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Audio Files</h5>
                    </a>
                    
                 </article>
                 
                 
        
        <article class="one-fifth" data-categories="illustration design">
        
                        <img src="/images/icon-post-format-multimedia.png" alt="">
        
                   <a class="project-meta" title="View Image files of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">
                        <h5 class="title">Image Files List</h5>
                    </a>
                    
                 </article>
                 

		

	</section>
    
      <?php endif; ?> 
        
        

	</section><!-- end #main -->

	<aside id="sidebar">
    
    
    <div class="widget">
    <?php if ($role == 2 ): ?>
    <div class="infobox"> 
        <h4 style=" text-transform:uppercase" class="name"><a title="view phone data of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'child','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>"><?php echo $datachild->child_name; ?></a></h4>
        
        
        <ul class="social-links">
        <li class="location"></li>

            	<li class="location"><a title="View Latest Location of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">Location</a></li>
        
        		<li class="track"><a title="View Recent Movement Track of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Movement Track</a></li>
                
                <li class="safetymap"><a title="View Safety Maps for <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Safety Maps</a></li>
                
                <li class="phonecontacts"><a title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Phone Contacts</a></li>
        
                 <li class="emailcontacts"><a title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Email Contacts</a></li>
                 
                  <li class="calllog"><a title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Call Log</a></li>
                  
                  <li class="smslog"><a title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">SMS Log</a></li>
     
                  <li class="smsloghotwords"><a title="View SMS Log of <?php echo $datachild->child_name; ?> including Hot Words" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'showhword','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Hot Words</a></li>
                
                
                <li class="webhistory"><a title="View Web Browsing History of <?php echo $datachild->child_name; ?> including Hot Words" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Web History</a></li>
                
                
               <li class="audiolist"><a title="View Audio List of <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Audio List</a></li>
                
                
               <li class="videolist"><a title="View Video List of <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Video List</a></li>
                
                
                <li class="imagelist"><a title="View Image List of <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Image List</a></li>

		</ul>
        </div>
        
        <?php elseif ($role == 5 ): ?>

        
    <div class="infobox"> 
        <h4 style=" text-transform:uppercase" class="name"><a title="view phone data of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'child','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>"><?php echo $datachild->child_name; ?></a></h4>
        
        
        <ul class="social-links">
        <li class="location"></li>

            	<li class="location"><a title="View Latest Location of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'location','action' => 'index', 'id'=>$datachild->id, 'name'=> $datachild->child_name));?>">Location</a></li>
        
        		<li class="track"><a title="View Recent Movement Track of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'tracker','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Movement Track</a></li>
                
                <li class="safetymap"><a title="View Safety Maps for <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'advance','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Safety Maps</a></li>
                
                <li class="phonecontacts"><a title="View Phone Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'phonecontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Phone Contacts</a></li>
        
                 <li class="emailcontacts"><a title="View Email Contacts of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'emailcontacts','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Email Contacts</a></li>
                 
                  <li class="calllog"><a title="View Call Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'calllog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Call Log</a></li>
                  
                  <li class="smslog"><a title="View SMS Log of <?php echo $datachild->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'smslog','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">SMS Log</a></li>
     
                  <li class="smsloghotwords"><a title="View SMS Log of <?php echo $datachild->child_name; ?> including Hot Words" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'showhword','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Hot Words</a></li>
                
                
                <li class="webhistory"><a title="View Web Browsing History of <?php echo $datachild->child_name; ?> including Hot Words" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'browsinghistory','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Web History</a></li>
                
                
               <li class="audiolist"><a title="View Audio List of <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'audiolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Audio List</a></li>
                
                
               <li class="videolist"><a title="View Video List of <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'videolist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Video List</a></li>
                
                
                <li class="imagelist"><a title="View Image List of <?php echo $datachild->child_name; ?> " href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'imagelist','action' => 'index', 'id'=>$datachild->id,'name'=> $datachild->child_name));?>">Image List</a></li>

		</ul>
        </div>
        
        <?php endif; ?> 
        
    
    </div>
    
    
    <div class="widget">
    <p class="info"><strong>other Family Members </strong></p>        



	<?php foreach($this->datachild2 as $datachild2): ?> 		
 
 
        <ul class="circle">
				
				<li><h4 class="name"><a title="view phone data of <?php echo $datachild2->child_name; ?>" href="<?php echo $this->url(array('module' => 'dashboard','controller' => 'child','action' => 'index', 'id'=>$datachild2->id, 'name'=> $datachild2->child_name));?>"><?php echo $datachild2->child_name; ?></a></h4></li>
                
				
			</ul>
 
			<?php endforeach; ?>
			
			</div>
            
            

		<!-- end .widget -->


		<!-- end .widget -->


	</aside><!-- end #sidebar -->
	
</section>



