<div class="container clearfix fitvids">
    

<div id="page-heading">
    <h1>Web Hosting </h1>	
    	
</div>
<!-- /page-heading -->

<div class="post full-width clearfix">

	<div class="entry clearfix">
		<p><strong>Enjoy access to our WinWinHost Hosting Offers!</strong></p>
<div class="clear"></div>
<hr class="" style="margin-top: px; margin-bottom:px;" />
<ul class="pricing-table clearfix">
<li class="pricing pricing-third  ">
<div class="pricing-header">
<h4>Reseller Hosting </h4>
<div class="price">$99.95 / year</div>
</div>
<div class="pricing-content">
<ul>
<li>Unlimited Disk Space</li>
<li>Unlimited Bandwidth</li>
<li>Unlimited Domains</li>
<li>Unlimited FTP Accounts</li>
<li>Helm Control Panel</li>
</ul>
</div>
<div class="pricing-button">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="H4NX9J6LG4QH4">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
<br /><br />
<a href="#" class="button gray"><span>More Details</span></a>
</div>
</li>
<li class="pricing pricing-third yes featured-pricing">
<div class="pricing-header">
<h4>Unlimited Hosting</h4>
<div class="price">$49.95 / year </div>
</div>
<div class="pricing-content">
<ul>
<li>Unlimited Disk Space</li>
<li>Unlimited Bandwidth</li>
<li>Unlimited Domains</li>
<li>Unlimited FTP Accounts</li>
<li>Unlimited Email Accounts</li>

</ul>
</div>
<div class="pricing-button">
<!--
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="D3DNE49FHVNP4">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>-->

<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="QNVU39SDZDQZY">
<input type="hidden" name="notify_url" value="http://new.winwinhost.com/directadmin/httpsocket/ipn_unlimit.php">
<input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
<br /><br />
<a href="#" class="button gray"><span>More Details</span></a>
</div>
</li>
<li class="pricing pricing-third no ">
<div class="pricing-header">
<h4>Dedicated Server</h4>
<div class="price">$80 / month</div>
</div>
<div class="pricing-content">
<ul>
<li>Managed Windows Server</li>
<li>Pentium 4 2.4 Ghz CPU</li>
<li>1 GB RAM</li>
<li>HELM control panel</li>
<li>80 GB</li>
</ul>
</div>
<div class="pricing-button">

<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="A83SYKC7GSJL4">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
<br /><br />
<a href="#" class="button gray"><span>More Details</span></a>
</div>
</li>
</ul>
<div class="clear"></div>
<div class="clear"></div>
<hr class="" style="margin-top: px; margin-bottom:px;" /a>

<div class="clear"></div>
<div class="clear"></div>

	</div>
	<!-- /entry -->
    
	    
</div>
<!-- /post -->


<div class="clear"></div>
</div><!-- /container -->
