<head>

<meta name="description" content="Phone Tracker app news and updates. Get updated what new mobile spy features are added to Phone Tracker and what else is going around the mobile/cell world">

</head>
       
<section id="content" class="container clearfix">
	<header class="page-header">
	
		<h1 class="page-title">Welcome to our blog</h1>
		
	</header><!-- end .page-header -->
	
	<section id="main">			 
		<article class="entry clearfix">

			<div class="entry-body">

					<h1 class="title"><?php echo  $this->data->news_title; ?></h1>

				<p><?php echo $this->data->news_text; ?></p>

			</div><!-- end .entry-body -->

			<div class="entry-meta">

				<ul>
					<li><span class="title">Posted:</span> <a href="#"> <?php echo  $this->data->news_posted; ?> </a></li>
				</ul>

			</div><!-- end .entry-meta -->

		</article><!-- end .entry -->
	</section><!-- end #main -->

	<aside id="sidebar">

    			<div class="widget">
                   
                            <div class="infobox">
                    
                                <h3>Have you not Downloaded the Phone Tracker's Android app Yet?</h3>
                    
                               <p><a target="_blank" title="Phone Track app free download" href="https://play.google.com/store/apps/details?id=phone_tracker.net"><img src="/images/androidmarket.png" alt="Download phone tracker android app from Google Play" title="Download phone tracker android app from Google Play"></a>
                                   
                                </p>
                    
                            </div><!-- end .infobox -->
                    </div>	
                    
                    <script type="text/javascript"><!--
google_ad_client = "ca-pub-4906488699730089";
/* phonetracker real sqaure */
google_ad_slot = "9271220908";
google_ad_width = 200;
google_ad_height = 200;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
			
            <div class="fb-like-box" data-href="http://www.facebook.com/phonetrackerdotnet" data-width="240" data-show-faces="true" data-border-color="white" data-stream="false" data-header="true"></div>

                    <div class="widget">
                    <h6 class="widget-title">Twitter Feed</h6>
						<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
                        <script>
                        new TWTR.Widget({
                          version: 2,
                          type: 'profile',
                          rpp: 3,
                          interval: 30000,
                          width:'auto',
                          height: 240,
                          theme: {
                            shell: {
                              background: '#6e6e6e',
                              color: '#ffffff'
                            },
                            tweets: {
                              background: '#575457',
                              color: '#ffffff',
                              links: '#a3a3a3'
                            }
                          },
                          features: {
                            scrollbar: false,
                            loop: false,
                            live: false,
                            behavior: 'all'
                          }
                        }).render().setUser('winwinhost').start();
                        </script>

		</div><!-- end .widget -->

	</aside><!-- end #sidebar -->
	
</section>

